apiVersion: v1
kind: ConfigMap
metadata:
  name: metasfresh-{{ .Release.Name }}-db-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{ (.Files.Glob "configs/db/postgresql.conf").AsConfig | indent 2 }}
  
