apiVersion: v1
kind: Secret
metadata:
  name: metasfresh-{{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  postgrespw: {{ .Values.db.postgrespw | b64enc }}
  