apiVersion: v1
kind: Secret
metadata:
  name: metasfresh-{{ .Release.Name }}-rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
  