-- 2019-07-16T14:18:02.597Z
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
/* DDL */ CREATE TABLE public.PayPal_Log (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10), C_Payment_Reservation_ID NUMERIC(10), Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, PayPal_Log_ID NUMERIC(10) NOT NULL, RequestBody TEXT, RequestHeaders TEXT, RequestMethod VARCHAR(40), RequestPath VARCHAR(2000), ResponseBody TEXT, ResponseCode NUMERIC(10), ResponseHeaders TEXT, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT COrder_PayPalLog FOREIGN KEY (C_Order_ID) REFERENCES public.C_Order DEFERRABLE INITIALLY DEFERRED, CONSTRAINT PayPal_Log_Key PRIMARY KEY (PayPal_Log_ID))
;

-- 2019-07-16T14:18:31.021Z
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
/* DDL */ CREATE TABLE public.PayPal_Config (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(2000), IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, PayPal_BaseUrl VARCHAR(255), PayPal_ClientId VARCHAR(255) NOT NULL, PayPal_ClientSecret VARCHAR(255) NOT NULL, PayPal_Config_ID NUMERIC(10) NOT NULL, PayPal_Sandbox CHAR(1) DEFAULT 'N' CHECK (PayPal_Sandbox IN ('Y','N')) NOT NULL, PayPal_WebUrl VARCHAR(255), Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT PayPal_Config_Key PRIMARY KEY (PayPal_Config_ID))
;

-- 2019-07-16T14:18:40.221Z
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
/* DDL */ CREATE TABLE public.PayPal_Order (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Payment_Reservation_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, ExternalId VARCHAR(40), IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, PayPal_AuthorizationId VARCHAR(40), PayPal_Order_ID NUMERIC(10) NOT NULL, PayPal_OrderJSON TEXT DEFAULT '0' NOT NULL, PayPal_PayerApproveUrl VARCHAR(255), Status VARCHAR(20) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT CPaymentReservation_PayPalOrder FOREIGN KEY (C_Payment_Reservation_ID) REFERENCES public.C_Payment_Reservation DEFERRABLE INITIALLY DEFERRED, CONSTRAINT PayPal_Order_Key PRIMARY KEY (PayPal_Order_ID))
;

