/**
 *  FILTER TYPES ACTIONS
 */

export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';

export const CREATE_FILTER = 'CREATE_FILTER';

export const DELETE_FILTER = 'DELETE_FILTER';

export const UPDATE_ACTIVE_FILTERS = 'UPDATE_ACTIVE_FILTERS';

export const FILTER_UPDATE_WIDGET_SHOWN = 'FILTER_UPDATE_WIDGET_SHOWN';

export const UPDATE_FLAG_NOTVALIDFIELDS = 'UPDATE_FLAG_NOTVALIDFIELDS';

export const CLEAR_STATIC_FILTERS = 'CLEAR_STATIC_FILTERS';
