export const SET_QUICKINPUT_LAYOUT = 'SET_QUICKINPUT_LAYOUT';
export const SET_QUICKINPUT_DATA = 'SET_QUICKINPUT_DATA';
export const UPDATE_QUICKINPUT_DATA = 'UPDATE_QUICKINPUT_DATA';
export const PATCH_QUICKINPUT_PENDING = 'PATCH_QUICKINPUT_PENDING';
export const PATCH_QUICKINPUT_DONE = 'PATCH_QUICKINPUT_DONE';
export const DELETE_QUICKINPUT = 'DELETE_QUICKINPUT';
