-- Name: M_HU_PI LU matching M_HU_PI_Item_Product_ID
-- 2025-10-02T07:02:54.687Z
UPDATE AD_Val_Rule SET Code='EXISTS (SELECT 1 FROM M_HU_PI_Version lu_piv INNER JOIN M_HU_PI_Item lu_pii ON lu_pii.M_HU_PI_Version_ID = lu_piv.M_HU_PI_Version_ID WHERE lu_piv.M_HU_PI_ID = M_HU_PI.M_HU_PI_ID AND lu_piv.IsActive = ''Y'' AND lu_piv.IsCurrent = ''Y'' AND lu_piv.HU_UnitType = ''LU'' AND lu_pii.IsActive = ''Y'' AND lu_pii.ItemType = ''HU'' AND lu_pii.included_hu_pi_id IN (SELECT tu_pi.m_HU_PI_ID FROM M_HU_PI_Item_Product tu_piip INNER JOIN M_HU_PI_Item tu_pii ON tu_pii.M_HU_PI_Item_ID = tu_piip.M_HU_PI_Item_ID INNER JOIN M_HU_PI_Version tu_piv ON tu_piv.M_HU_PI_Version_ID = tu_pii.M_HU_PI_Version_ID INNER JOIN M_HU_PI tu_pi ON tu_pi.M_HU_PI_ID = tu_piv.M_HU_PI_ID WHERE tu_piip.M_HU_PI_Item_Product_ID = (CASE WHEN @M_HU_PI_Item_Product_ID/0@ > 0 THEN @M_HU_PI_Item_Product_ID/0@ ELSE 101 END) AND tu_pii.IsActive = ''Y'' AND tu_piv.IsActive = ''Y'' AND tu_piv.IsCurrent = ''Y'' AND tu_piv.HU_UnitType IN (''TU'', ''V'') AND tu_pi.IsActive = ''Y''))',Updated=TO_TIMESTAMP('2025-10-02 07:02:54.685000','YYYY-MM-DD HH24:MI:SS.US')::timestamp without time zone AT TIME ZONE 'UTC',UpdatedBy=100 WHERE AD_Val_Rule_ID=540746
;

-- Name: M_HU_PI_Item_Product_For_Product_and_MovementDate
-- 2025-10-02T09:36:15.333Z
UPDATE AD_Val_Rule SET Code='(M_HU_PI_Item_Product.M_Product_ID =@M_Product_ID@ OR M_HU_PI_Item_Product.isAllowAnyProduct = ''Y'') AND (M_HU_PI_Item_Product.C_BPartner_ID = @C_BPartner_ID/0@ OR M_HU_PI_Item_Product.C_BPartner_ID IS NULL) AND M_HU_PI_Item_Product.ValidFrom <= ''@MovementDate@'' AND (M_HU_PI_Item_Product.ValidTo >= ''@MovementDate@'' OR M_HU_PI_Item_Product.ValidTo IS NULL) AND EXISTS (SELECT 1 FROM M_HU_PI_Item pii INNER JOIN M_HU_PI_Version piv ON piv.M_HU_PI_Version_ID = pii.M_HU_PI_Version_ID INNER JOIN M_HU_PI pi ON pi.M_HU_PI_ID = piv.M_HU_PI_ID WHERE pii.M_HU_PI_Item_ID = M_HU_PI_Item_Product.M_HU_PI_Item_ID AND pii.IsActive = ''Y'' AND piv.IsActive = ''Y'' AND piv.IsCurrent = ''Y'' AND piv.HU_UnitType IN (''TU'',''V'') AND pi.IsActive = ''Y'')',Updated=TO_TIMESTAMP('2025-10-02 09:36:15.330000','YYYY-MM-DD HH24:MI:SS.US')::timestamp without time zone AT TIME ZONE 'UTC',UpdatedBy=100 WHERE AD_Val_Rule_ID=540745
;

