
-- 2018-01-31T15:18:30.271
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
/* DDL */ CREATE TABLE public.M_Product_PlanningSchema (
AD_Client_ID NUMERIC(10) NOT NULL, 
AD_Org_ID NUMERIC(10) NOT NULL, 
AD_Workflow_ID NUMERIC(10), 
C_BPartner_ID NUMERIC(10), 
Created TIMESTAMP WITH TIME ZONE NOT NULL, 
CreatedBy NUMERIC(10) NOT NULL, 
DD_NetworkDistribution_ID NUMERIC(10), 
DeliveryTime_Promised NUMERIC, 
IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, 
IsAttributeDependant CHAR(1) DEFAULT 'N' CHECK (IsAttributeDependant IN ('Y','N')) NOT NULL, 
IsCreatePlan CHAR(1) DEFAULT 'Y' CHECK (IsCreatePlan IN ('Y','N')) NOT NULL, 
IsDocComplete CHAR(1) DEFAULT 'N' CHECK (IsDocComplete IN ('Y','N')) NOT NULL, 
IsManufactured CHAR(1) DEFAULT 'N' NOT NULL, IsMPS CHAR(1) DEFAULT 'N' CHECK (IsMPS IN ('Y','N')) NOT NULL, 
IsPhantom CHAR(1) DEFAULT 'N' CHECK (IsPhantom IN ('Y','N')) NOT NULL, 
IsPickDirectlyIfFeasible CHAR(1) DEFAULT 'N' CHECK (IsPickDirectlyIfFeasible IN ('Y','N')) NOT NULL, 
IsPurchased CHAR(1) DEFAULT 'N' NOT NULL, 
IsTraded CHAR(1) DEFAULT 'N' NOT NULL, 
M_AttributeSetInstance_ID NUMERIC(10), 
M_Product_PlanningSchema_ID NUMERIC(10) NOT NULL, 
M_ProductPlanningSchema_Selector CHAR(1) NOT NULL, 
M_Warehouse_ID NUMERIC(10), 
Order_Max NUMERIC, 
Order_Min NUMERIC, 
Order_Pack NUMERIC, 
Order_Period NUMERIC, 
Order_Policy VARCHAR(3) DEFAULT 'LFL', 
Order_Qty NUMERIC, 
Planner_ID NUMERIC(10), 
PP_POQ_AggregateOnBPartnerLevel CHAR(1) DEFAULT 'N' CHECK (PP_POQ_AggregateOnBPartnerLevel IN ('Y','N')) NOT NULL,
S_Resource_ID NUMERIC(10),
SafetyStock NUMERIC, 
SeqNo NUMERIC(10), 
StorageAttributesKey VARCHAR(1024), 
TimeFence NUMERIC, TransfertTime NUMERIC, 
Updated TIMESTAMP WITH TIME ZONE NOT NULL, 
UpdatedBy NUMERIC(10) NOT NULL, 
WorkingTime NUMERIC, 
Yield NUMERIC(10) DEFAULT 100, 

CONSTRAINT ADWorkflow_MProductPlanningSch FOREIGN KEY (AD_Workflow_ID) REFERENCES public.AD_Workflow DEFERRABLE INITIALLY DEFERRED,
 CONSTRAINT CBPartner_MProductPlanningSche FOREIGN KEY (C_BPartner_ID) REFERENCES public.C_BPartner DEFERRABLE INITIALLY DEFERRED, 
CONSTRAINT DDNetworkDistribution_MProduct FOREIGN KEY (DD_NetworkDistribution_ID) REFERENCES public.DD_NetworkDistribution DEFERRABLE INITIALLY DEFERRED, 
CONSTRAINT MAttributeSetInstance_MProduct FOREIGN KEY (M_AttributeSetInstance_ID) REFERENCES public.M_AttributeSetInstance DEFERRABLE INITIALLY DEFERRED,
 CONSTRAINT M_Product_PlanningSchema_Key PRIMARY KEY (M_Product_PlanningSchema_ID), 
CONSTRAINT MWarehouse_MProductPlanningSch FOREIGN KEY (M_Warehouse_ID) REFERENCES public.M_Warehouse DEFERRABLE INITIALLY DEFERRED, 
CONSTRAINT Planner_MProductPlanningSchema FOREIGN KEY (Planner_ID) REFERENCES public.AD_User DEFERRABLE INITIALLY DEFERRED, 
CONSTRAINT SResource_MProductPlanningSche FOREIGN KEY (S_Resource_ID) REFERENCES public.S_Resource DEFERRABLE INITIALLY DEFERRED)
;
