

DROP TABLE IF EXISTS migration_data.i_product_inserts_products_only
;

CREATE TABLE migration_data.i_product_inserts_products_only AS
SELECT 1000000                                                         AS ad_client_id,
       1000000                                                         AS ad_org_id,
       'Y'                                                             AS isactive,
       NOW()                                                           AS created,
       99                                                              AS createdby,
       NOW()                                                           AS updated,
       99                                                              AS updatedby,
       'N'                                                             AS i_isimported,
       NULL                                                            AS i_errormsg,
       NULL::numeric                                                   AS m_product_id,
       T_Item."No_"                                                    AS value,
       T_Item."Search Description"                                     AS name,
       T_Item."Description"                                            AS description,
       NULL                                                            AS documentnote,
       NULL                                                            AS help,
       NULL                                                            AS upc,
       NULL                                                            AS sku,
       CASE T_Item."Base Unit of Measure" -- x12de355: Map Grundhöfer Produktiv "Base Unit of Measure"
           WHEN 'KG' THEN 'KGM'
           WHEN 'ST' THEN 'PCE'
                     ELSE uom.x12de355
       END                                                             AS x12de355,
       NULL::numeric                                                   AS c_uom_id,
       'Standard'                                                      AS productcategory_value,
       NULL::numeric                                                   AS m_product_category_id,
       CASE T_Item."Type" -- producttype: Map Grundhöfer Produktiv Type (0 for Item, 1 for Service)
           WHEN 0 THEN 'I'
           WHEN 1 THEN 'S'
                  ELSE 'I'
       END                                                             AS producttype,
       NULL                                                            AS classification,
       T_Item."Unit Volume"                                            AS volume,
       T_Item."Gross Weight"                                           AS weight,
       NULL::numeric                                                   AS shelfwidth,
       NULL::numeric                                                   AS shelfheight,
       NULL::numeric                                                   AS shelfdepth,
       T_Item."Units per Parcel"                                       AS unitsperpallet,
       'N'                                                             AS discontinued,
       NULL::timestamp without time zone                               AS discontinuedby,
       NULL                                                            AS imageurl,
       NULL                                                            AS descriptionurl,
       NULL                                                            AS bpartner_value,
       NULL::numeric                                                   AS c_bpartner_id,
       NULL                                                            AS iso_code,
       NULL::numeric                                                   AS pricelist,
       NULL::numeric                                                   AS pricepo,
       NULL::numeric                                                   AS royaltyamt,
       NULL::timestamp without time zone                               AS priceeffective,
       NULL                                                            AS vendorproductno,
       NULL                                                            AS vendorcategory,
       T_Item."Minimum Order Quantity"                                 AS order_min,
       T_Item."Order Multiple"                                         AS order_pack,
       0                                                               AS costperorder,
       NULL::numeric                                                   AS deliverytime_promised,
       NULL                                                            AS processing,
       'N'                                                             AS processed,
       NULL::numeric                                                   AS pricestd,
       NULL::numeric                                                   AS pricelimit,
       CASE
           WHEN T_Item."VAT Prod_ Posting Group" ILIKE '%19%' THEN (SELECT c_taxcategory_id
                                                                    FROM c_taxcategory
                                                                    WHERE internalname = 'Normal')
           WHEN T_Item."VAT Prod_ Posting Group" ILIKE '%7%'  THEN (SELECT c_taxcategory_id
                                                                    FROM c_taxcategory
                                                                    WHERE internalname = 'Reduced')
                                                              ELSE (SELECT c_taxcategory_id FROM c_taxcategory WHERE internalname = 'TaxFree')
       END                                                             AS c_taxcategory_id,
       NULL                                                            AS c_taxcategory_name,
       NULL                                                            AS m_pricelist_version_name,
       NULL::numeric                                                   AS package_uom_id,
       NULL                                                            AS packagesize,
       NULL                                                            AS productmanufacturer,
       CASE T_Item."Blocked" WHEN 1 THEN 'N' ELSE 'Y' END              AS issold,
       CASE T_Item."Type" WHEN 0 THEN 'Y' ELSE 'N' END                 AS isstocked,
       NULL                                                            AS a00pgeinh,
       'N'                                                             AS isprescription,
       'N'                                                             AS isnarcotic,
       'N'                                                             AS istfg,
       'N'                                                             AS iscoldchain,
       NULL                                                            AS fam_zub,
       NULL::numeric                                                   AS m_indication_id,
       NULL                                                            AS m_indication_name,
       NULL::numeric                                                   AS m_dosageform_id,
       NULL                                                            AS a00darfo,
       NULL                                                            AS m_productplanningschema_selector,
       NULL::numeric                                                   AS c_dataimport_id,
       NULL                                                            AS pharmaproductcategory_name,
       NULL::numeric                                                   AS m_pharmaproductcategory_id,
       NULL::numeric                                                   AS a01aep,
       NULL::numeric                                                   AS a01apu,
       NULL::numeric                                                   AS apu_price_list_id,
       NULL::numeric                                                   AS aep_price_list_id,
       NULL::numeric                                                   AS manufacturer_id,
       NULL::numeric                                                   AS ad_issue_id,
       NULL::numeric                                                   AS i_lineno,
       NULL                                                            AS i_linecontent,
       NULL::numeric                                                   AS c_dataimport_run_id,
       T_Item."No_"                                                    AS externalid,
       T_Item."Net Weight"                                             AS netweight,
       T_Item."Country_Region of Origin Code"                          AS rawmaterialorigincountrycode,
       T_Item."Tariff No_"                                             AS customstariff,
       NULL::numeric                                                   AS m_customstariff_id,
       NULL::numeric                                                   AS rawmaterialorigin_id,
       'N'                                                             AS isscaleprice,
       NULL::numeric                                                   AS qty,
       NULL                                                            AS trademark,
       NULL                                                            AS pzn,
       NULL                                                            AS manufacturingmethod,
       'N'                                                             AS iscommissioned,
       'N'                                                             AS ispurchased,
       NULL                                                            AS diettype,
       NULL::numeric                                                   AS dosageqty,
       NULL::numeric                                                   AS dosageuom_id,
       CASE
           WHEN T_Item."Net Weight" <> 0
               THEN (SELECT c_uom_id FROM c_uom WHERE x12de355 = 'KGM' AND isactive = 'Y')
       END                                                             AS netweight_uom_id,
       CASE
           WHEN T_Item."Gross Weight" <> 0
               THEN (SELECT c_uom_id FROM c_uom WHERE x12de355 = 'KGM' AND isactive = 'Y')
       END                                                             AS weight_uom_id,
       NULL                                                            AS weightuom,
       NULL                                                            AS netweightuom,
       NULL                                                            AS dosageuom,
       NULL                                                            AS m_hu_pi_value,
       NULL::numeric                                                   AS qtycu_uom_id,
       'N'                                                             AS isdefaultpacking,
       NULL                                                            AS invoicableqtybasedon,
       T_Item."Price Unit Conversion"                                  AS uom_multiplierrate,
       NULL::numeric                                                   AS qtycu,
       NULL                                                            AS qtycu_uom_code,
       'Y'                                                             AS isupdatename,
       CASE
           WHEN NULLIF(TRIM(T_Item."Expiration Calculation"), '') IS NULL THEN 0
                                                                          ELSE REGEXP_REPLACE(TRIM(T_Item."Expiration Calculation"), '\D', '', 'g')::numeric
       END                                                             AS GuaranteeDaysMin
FROM "migration_data"."Navision$Item" AS T_Item
         LEFT JOIN C_UOM uom ON T_Item."Base Unit of Measure" = UOM.name
;


-- Single INSERT into i_product (no batching needed since there's no price duplication issue)
INSERT INTO i_product (i_product_id,
                       ad_client_id,
                       ad_org_id,
                       isactive,
                       created,
                       createdby,
                       updated,
                       updatedby,
                       i_isimported,
                       i_errormsg,
                       m_product_id,
                       value,
                       name,
                       description,
                       documentnote,
                       help,
                       upc,
                       sku,
                       x12de355,
                       c_uom_id,
                       productcategory_value,
                       m_product_category_id,
                       producttype,
                       classification,
                       volume,
                       weight,
                       shelfwidth,
                       shelfheight,
                       shelfdepth,
                       unitsperpallet,
                       discontinued,
                       discontinuedby,
                       imageurl,
                       descriptionurl,
                       bpartner_value,
                       c_bpartner_id,
                       iso_code,
                       pricelist,
                       pricepo,
                       royaltyamt,
                       priceeffective,
                       vendorproductno,
                       vendorcategory,
                       order_min,
                       order_pack,
                       costperorder,
                       deliverytime_promised,
                       processing,
                       processed,
                       pricestd,
                       pricelimit,
                       c_taxcategory_id,
                       c_taxcategory_name,
                       m_pricelist_version_name,
                       package_uom_id,
                       packagesize,
                       productmanufacturer,
                       issold,
                       isstocked,
                       a00pgeinh,
                       isprescription,
                       isnarcotic,
                       istfg,
                       iscoldchain,
                       fam_zub,
                       m_indication_id,
                       m_indication_name,
                       m_dosageform_id,
                       a00darfo,
                       m_productplanningschema_selector,
                       c_dataimport_id,
                       pharmaproductcategory_name,
                       m_pharmaproductcategory_id,
                       a01aep,
                       a01apu,
                       apu_price_list_id,
                       aep_price_list_id,
                       manufacturer_id,
                       ad_issue_id,
                       i_lineno,
                       i_linecontent,
                       c_dataimport_run_id,
                       externalid,
                       netweight,
                       rawmaterialorigincountrycode,
                       customstariff,
                       m_customstariff_id,
                       rawmaterialorigin_id,
                       isscaleprice,
                       qty,
                       trademark,
                       pzn,
                       manufacturingmethod,
                       iscommissioned,
                       ispurchased,
                       diettype,
                       dosageqty,
                       dosageuom_id,
                       netweight_uom_id,
                       weight_uom_id,
                       weightuom,
                       netweightuom,
                       dosageuom,
                       m_hu_pi_value,
                       qtycu_uom_id,
                       isdefaultpacking,
                       invoicableqtybasedon,
                       uom_multiplierrate,
                       qtycu,
                       qtycu_uom_code,
                       isupdatename,
                       GuaranteeDaysMin)
SELECT NEXTVAL('i_product_seq'),
       ad_client_id,
       ad_org_id,
       isactive,
       created,
       createdby,
       updated,
       updatedby,
       i_isimported,
       i_errormsg,
       m_product_id,
       value,
       name,
       description,
       documentnote,
       help,
       upc,
       sku,
       x12de355,
       c_uom_id,
       productcategory_value,
       m_product_category_id,
       producttype,
       classification,
       volume,
       weight,
       shelfwidth,
       shelfheight,
       shelfdepth,
       unitsperpallet,
       discontinued,
       discontinuedby,
       imageurl,
       descriptionurl,
       bpartner_value,
       c_bpartner_id,
       iso_code,
       pricelist,
       pricepo,
       royaltyamt,
       priceeffective,
       vendorproductno,
       vendorcategory,
       order_min,
       order_pack,
       costperorder,
       deliverytime_promised,
       processing,
       processed,
       pricestd,
       pricelimit,
       c_taxcategory_id,
       c_taxcategory_name,
       m_pricelist_version_name,
       package_uom_id,
       packagesize,
       productmanufacturer,
       issold,
       isstocked,
       a00pgeinh,
       isprescription,
       isnarcotic,
       istfg,
       iscoldchain,
       fam_zub,
       m_indication_id,
       m_indication_name,
       m_dosageform_id,
       a00darfo,
       m_productplanningschema_selector,
       c_dataimport_id,
       pharmaproductcategory_name,
       m_pharmaproductcategory_id,
       a01aep,
       a01apu,
       apu_price_list_id,
       aep_price_list_id,
       manufacturer_id,
       ad_issue_id,
       i_lineno,
       i_linecontent,
       c_dataimport_run_id,
       externalid,
       netweight,
       rawmaterialorigincountrycode,
       customstariff,
       m_customstariff_id,
       rawmaterialorigin_id,
       isscaleprice,
       qty,
       trademark,
       pzn,
       manufacturingmethod,
       iscommissioned,
       ispurchased,
       diettype,
       dosageqty,
       dosageuom_id,
       netweight_uom_id,
       weight_uom_id,
       weightuom,
       netweightuom,
       dosageuom,
       m_hu_pi_value,
       qtycu_uom_id,
       isdefaultpacking,
       invoicableqtybasedon,
       uom_multiplierrate,
       qtycu,
       qtycu_uom_code,
       isupdatename,
       GuaranteeDaysMin
FROM migration_data.i_product_inserts_products_only
;

-- SELECT 'Total products inserted into i_product: ' || COUNT(1)
-- FROM i_product
-- WHERE created >= NOW() - INTERVAL '1 minute'
-- ;
