
update ad_tab_trl set name = 'Accounting' ,istranslated = 'Y' where ad_tab_id = 210 and ad_language = 'en_US';
update ad_tab_trl set name = 'Allocated Product' ,istranslated = 'Y' where ad_tab_id = 540722 and ad_language = 'en_US';
update ad_tab_trl set name = 'Attribute' ,istranslated = 'Y' where ad_tab_id = 540509 and ad_language = 'en_US';
update ad_tab_trl set name = 'Bank Account' ,istranslated = 'Y' where ad_tab_id = 226 and ad_language = 'en_US';
update ad_tab_trl set name = 'Boxing Type' ,istranslated = 'Y' where ad_tab_id = 540521 and ad_language = 'en_US';
update ad_tab_trl set name = 'Business Partner Group' ,istranslated = 'Y' where ad_tab_id = 322 and ad_language = 'en_US';
update ad_tab_trl set name = 'Business Partner' ,istranslated = 'Y' where ad_tab_id = 220 and ad_language = 'en_US';
update ad_tab_trl set name = 'Business Partner' ,istranslated = 'Y' where ad_tab_id = 562 and ad_language = 'en_US';
update ad_tab_trl set name = 'CU-TU Allocation' ,istranslated = 'Y' where ad_tab_id = 540517 and ad_language = 'en_US';
update ad_tab_trl set name = 'Contact (User)' ,istranslated = 'Y' where ad_tab_id = 496 and ad_language = 'en_US';
update ad_tab_trl set name = 'Customer' ,istranslated = 'Y' where ad_tab_id = 223 and ad_language = 'en_US';
update ad_tab_trl set name = 'Handling Unit Assignment' ,istranslated = 'Y' where ad_tab_id = 540625 and ad_language = 'en_US';
update ad_tab_trl set name = 'Invoice Line' ,istranslated = 'Y' where ad_tab_id = 270 and ad_language = 'en_US';
update ad_tab_trl set name = 'Invoice Tax' ,istranslated = 'Y' where ad_tab_id = 271 and ad_language = 'en_US';
update ad_tab_trl set name = 'Invoice' ,istranslated = 'Y' where ad_tab_id = 263 and ad_language = 'en_US';
update ad_tab_trl set name = 'Location' ,istranslated = 'Y' where ad_tab_id = 222 and ad_language = 'en_US';
update ad_tab_trl set name = 'Matched Inouts' ,istranslated = 'Y' where ad_tab_id = 540671 and ad_language = 'en_US';
update ad_tab_trl set name = 'Order Line' ,istranslated = 'Y' where ad_tab_id = 187 and ad_language = 'en_US';
update ad_tab_trl set name = 'Order Tax' ,istranslated = 'Y' where ad_tab_id = 236 and ad_language = 'en_US';
update ad_tab_trl set name = 'Order' ,istranslated = 'Y' where ad_tab_id = 186 and ad_language = 'en_US';
update ad_tab_trl set name = 'Packing Instruction' ,istranslated = 'Y' where ad_tab_id = 540504 and ad_language = 'en_US';
update ad_tab_trl set name = 'Parcel' ,istranslated = 'Y' where ad_tab_id = 540572 and ad_language = 'en_US';
update ad_tab_trl set name = 'Payment Term' ,istranslated = 'Y' where ad_tab_id = 184 and ad_language = 'en_US';
update ad_tab_trl set name = 'Position' ,istranslated = 'Y' where ad_tab_id = 540506 and ad_language = 'en_US';
update ad_tab_trl set name = 'Price' ,istranslated = 'Y' where ad_tab_id = 183 and ad_language = 'en_US';
update ad_tab_trl set name = 'Print Format' ,istranslated = 'Y' where ad_tab_id = 540653 and ad_language = 'en_US';
update ad_tab_trl set name = 'Product Category' ,istranslated = 'Y' where ad_tab_id = 189 and ad_language = 'en_US';
update ad_tab_trl set name = 'Product' ,istranslated = 'Y' where ad_tab_id = 180 and ad_language = 'en_US';
update ad_tab_trl set name = 'Replenish' ,istranslated = 'Y' where ad_tab_id = 182 and ad_language = 'en_US';
update ad_tab_trl set name = 'Sales Representative' ,istranslated = 'Y' where ad_tab_id = 504622 and ad_language = 'en_US';
update ad_tab_trl set name = 'Shipment Line' ,istranslated = 'Y' where ad_tab_id = 258 and ad_language = 'en_US';
update ad_tab_trl set name = 'Shipment' ,istranslated = 'Y' where ad_tab_id = 257 and ad_language = 'en_US';
update ad_tab_trl set name = 'TU-CU Allocation' ,istranslated = 'Y' where ad_tab_id = 540507 and ad_language = 'en_US';
update ad_tab_trl set name = 'Translation' ,istranslated = 'Y' where ad_tab_id = 233 and ad_language = 'en_US';
update ad_tab_trl set name = 'Vendor' ,istranslated = 'Y' where ad_tab_id = 224 and ad_language = 'en_US';
update ad_tab_trl set name = 'Version' ,istranslated = 'Y' where ad_tab_id = 540505 and ad_language = 'en_US';
