
# List of branches that are not "sandbox"
# See https://help.testspace.com/dashboard/project#configuration
# Please keep in sync with the branch list in .mergify.yml
release:
  - keen_hawk_uat
  - task_force_uat
  - electric_light_uat
  - feisty_sloth_uat
  - arctic_north_uat
  - blue_horizon_uat
  - big_coconut_uat
  - clone_wars_uat
  - epic_party_uat
  - gray_knight_uat
  - hard_encoded_uat
  - hard_encoded_hotfix
  - inner_silence_uat
  - inner_silence_hotfix
  - intensive_care_uat
  - intensive_care_hotfix
  - intensive_care_release
  - iron_plant_uat
  - koala_yawn_uat
  - massive_entropy_uat
  - massive_entropy_hotfix
  - mad_orange_uat
  - mad_orange_hotfix
  - majestic_kangaroo_uat
  - middle_ages_uat
  - modified_carbon_uat
  - modus_operandi_uat
  - neon_underwear_uat
  - new_dawn_uat
  - oasis_sun_uat
  - pink_rooster_uat
  - pink_rooster_hotfix
  - release
  - soft_panda_uat
  - soft_panda_hotfix
  - soft_panda_release
  - science_vessel_uat
  - secondary_opinion_uat
  - secondary_opinion_hotfix
  - tasty_ham_uat
  - tasty_ham_hotfix
  - tenacious_d_uat
  - vampire_textbook_uat
  - vampire_textbook_hotfix
  - vampire_textbook_release
  - yoyo_uat
  - yoyo_hotfix
