[
  {
    "field": "ID",
    "value": "T1002",
    "value-reason": "new document"
  },
  {
    "field": "QtyOrdered",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AD_Language",
    "value": "en_US",
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsCommissionLock",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Ref_RMA_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DescriptionBottom",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "QtyInvoiced",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsEdiRecipient",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "QtyMoved",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Incoterm",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "GrandTotal",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsInvoiced",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsPrinted",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsSelected",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsSelfService",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsSOTrx",
    "value": true,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsTaxIncluded",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsTransferred",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsUseBillToAddress",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsUseBPartnerAddress",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsUseDeliveryToAddress",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "lines",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "M_FreightCategory_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@DeliveryViaRule@='S'&@OrderType@='SO'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "M_PriceList_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DatePrinted",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "DateAcct",
    "value": "2016-08-18T00:00Z",
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "net_in_base_currency",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "netsum",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "CurSymbol",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "CreateCopy",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AD_Client_ID",
    "value": {
      "1000000": "metas fresh"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "OrderType",
    "value": "SO",
    "value-reason": "direct set from document wrapper",
    "readonly": false,
    "readonly-reason": "direct set from document wrapper",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Pay_BPartner_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Pay_Location_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Weight",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsCreditApproved",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@='SO'"
  },
  {
    "field": "IsDelivered",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsActive",
    "value": true,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IncotermLocation",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@Incoterm@!''"
  },
  {
    "field": "CompleteOrderDiscount",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "C_DocType_ID",
    "value": {
      "0": "** New **"
    },
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_CashLine_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_BP_BankAccount_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "BaseCurSymbol",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "SendEMail",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Sum_Tax",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "TotalLines",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Volume",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsApproved",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@='SO'"
  },
  {
    "field": "C_PaymentTerm_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@PaymentRule@='P'|@PaymentRule@='D'|@PaymentRule@='K'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Posted",
    "value": "N",
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@Processed@=Y&@#ShowAcct@=Y"
  },
  {
    "field": "C_Payment_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_Order_ID",
    "value": -1002,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Processed",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Processing",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "PromotionCode",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "CopyFrom",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AmountRefunded",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AmountTendered",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "C_POS_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "M_Warehouse_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "InvoiceStatus",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DeliveryStatus",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_DocTypeTarget_ID",
    "value": {
      "1000030": "Standardauftrag"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DocStatus",
    "value": {
      "DR": "Drafted"
    },
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "AD_Org_ID",
    "value": {
      "1000000": "metas fresh AG"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DocumentNo",
    "value": "<2>",
    "value-reason": "direct set from document wrapper",
    "readonly": false,
    "readonly-reason": "direct set from document wrapper",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "DateOrdered",
    "value": "2016-08-18T00:00Z",
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "receivedvia",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Ref_Proposal_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@Ref_Proposal_ID@!0",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Ref_Order_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@Ref_Order_ID@!0",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Ref_DateOrder",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@Ref_Proposal_ID@!0&@C_DocTypeTarget_ID@=1000027"
  },
  {
    "field": "OfferValidDays",
    "value": 0,
    "value-reason": "direct set from document wrapper",
    "readonly": false,
    "readonly-reason": "direct set from document wrapper",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@=ON|@OrderType@=OB"
  },
  {
    "field": "OfferValidDate",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@=ON|@OrderType@=OB"
  },
  {
    "field": "C_BPartner_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Bill_BPartner_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "POReference",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AD_User_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Bill_User_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_BPartner_Location_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Bill_Location_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "BPartnerAddress",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "BillToAddress",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "AD_InputDataSource_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "IsEdiEnabled",
    "value": false,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "EDI_Desadv_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@EDI_Desadv_ID@!0",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "InvoiceRule",
    "value": {
      "D": "After Delivery"
    },
    "value-reason": "direct set from document wrapper",
    "readonly": false,
    "readonly-reason": "direct set from document wrapper",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@='SO'|@OrderType@='WP'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "SalesRep_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DeliveryViaRule",
    "value": {
      "P": "Pickup"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DeliveryRule",
    "value": {
      "F": "Force"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@='SO'|@OrderType@='WP'|@OrderType@='PM'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "M_Shipper_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "IsDropShip",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "DropShip_BPartner_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=@IsDropShip/'N'@='Y'",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsDropShip@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DropShip_User_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsDropShip@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DropShip_Location_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=@IsDropShip/'N'@='Y'",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsDropShip@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "DeliveryToAddress",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsDropShip@='Y'"
  },
  {
    "field": "FreightCostRule",
    "value": {
      "I": "Freight included"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsSOTrx@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "FreightAmt",
    "value": 0,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsSOTrx@='Y'"
  },
  {
    "field": "DatePromised",
    "value": "2016-08-18T00:00Z",
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "PreparationDate",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "M_PricingSystem_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "PaymentRule",
    "value": "P",
    "value-reason": "direct set from document wrapper",
    "readonly": false,
    "readonly-reason": "direct set from document wrapper",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "M_Product_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "M_HU_PI_Item_Product_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Qty_FastInput_TU",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Qty_FastInput",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "DocAction",
    "value": "CO",
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "HandOver_Partner_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "HandOver_Location_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@IsUseHandOver_Location@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "IsUseHandOver_Location",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "CreateNewFromProposal",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@C_DocTypeTarget_ID@=1000027&@Ref_Proposal_ID@=0&@DocStatus@='CO'"
  },
  {
    "field": "C_Currency_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_ConversionType_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@C_Currency_ID@!@$C_Currency_ID@",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_Charge_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@HasCharges@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "ChargeAmt",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@HasCharges@='Y'"
  },
  {
    "field": "PriorityRule",
    "value": {
      "5": "Medium"
    },
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@OrderType@='SO'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "UpdatedBy",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Updated",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "CreatedBy",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Created",
    "value": null,
    "value-reason": "new document",
    "readonly": true,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "IsDiscountPrinted",
    "value": false,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": true,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=true",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Description",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "Orderline_includedTab",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true"
  },
  {
    "field": "C_Project_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_PJ@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_Activity_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_AY@='Y'",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "C_Campaign_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_MC@=Y",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "AD_OrgTrx_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_OT@=Y",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "User1_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_U1@=Y",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "User2_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": false,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=@$Element_U2@=Y",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  },
  {
    "field": "Link_Order_ID",
    "value": null,
    "value-reason": "new document",
    "readonly": false,
    "readonly-reason": "new document",
    "mandatory": false,
    "mandatory-reason": "TriggeringField=null, DependencyType=MandatoryLogic, MandatoryLogic=false",
    "displayed": true,
    "displayed-reason": "TriggeringField=null, DependencyType=DisplayLogic, DisplayLogic=true",
    "lookupValuesStale": true,
    "lookupValuesStale-reason": "TriggeringField=null, DependencyType=LookupValues"
  }
]
