#
# unsuccessfull first try for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1013
# I managed to build and run the docker container, but could not connect to it with firefox  (both running on localhost).
#
# At the same time, the following *did* work
#  * install npm and node locally and run the metasfresh-webui-frontent (output looked the same as in the docker container!)
#  * run the standard nxginx container with "sudo docker run --name my-nginx-test -p 8080:80 nginx" (welcome page was shown)
#
# How i build and ran the container:
# sudo docker build --file Dockerfile.build-dev --tag my-webui-frontent .
# sudo docker run --name my-webui-frontend4 -p 8080:3000 -d my-webui-frontent
#
# resources i tried to follow:
# * the README.md of this repository
# * https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

FROM node:latest

RUN npm install webpack -g

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . /usr/src/app/
COPY config.js.dist /usr/src/app/config.js
RUN npm install

EXPOSE 3000

CMD [ "npm", "start" ]


