FROM node:6-onbuild

ENV DOCKER true

RUN npm install webpack -g

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy app source to Docker
COPY . /usr/src/app/

# Install node_packages
RUN npm install

# Use default config
RUN cp ./config.js.dist ./config.js

EXPOSE 3000
