FROM postgres:9

RUN apt -y update \
    && apt -y upgrade \
    && apt -y install openjdk-8-jre-headless \
    && apt -y autoremove \
    && apt -y clean
	
WORKDIR /tmp/init

COPY --chmod=700 docker/db/apply-migrations.sh .
COPY docker/db/migrate.properties .

COPY --from=mvn-backend:latest /backend/metasfresh-dist/dist/target/dist/sql ./sql
COPY --from=mvn-backend:latest /backend/metasfresh-dist/dist/target/dist/install/lib .

ENTRYPOINT ["/bin/bash"]
CMD ["/tmp/init/apply-migrations.sh"]