FROM node:17

RUN npm install -g webpack webpack-cli

WORKDIR /app 
COPY frontend/package.json .
# COPY yarn.lock .

RUN yarn install

COPY frontend/ .

RUN yarn lint
# RUN yarn test --ci
RUN webpack --config webpack.prod.js
