FROM maven:3.8.4-jdk-8

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* && localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8
ENV TZ=Europe/Berlin

COPY --from=metas-mvn-common:latest /root/.m2 /root/.m2/

WORKDIR /backend
COPY backend .
RUN mvn clean install -Dmaven.gitcommitid.skip=true -DskipTests

RUN mvn test