FROM openjdk:8-jdk-oraclelinux7 as build

RUN yum -y install yum-utils && yum-config-manager --add-repo http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo && yum-config-manager --enable epel-apache-maven && yum install -y apache-maven && yum -y clean all  && rm -rf /var/cache


COPY docker-builds/mvn/settings.xml /root/.m2/

WORKDIR /parent
COPY misc/parent-pom .
RUN mvn clean install

WORKDIR /commons
COPY misc/de-metas-common .
RUN mvn clean install
