FROM openjdk:8-jdk-oraclelinux7 as build

RUN yum -y install yum-utils && yum-config-manager --add-repo http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo && yum-config-manager --enable epel-apache-maven && yum install -y apache-maven && yum -y clean all  && rm -rf /var/cache

COPY --from=metas-mvn-common:latest /root/.m2 /root/.m2/

WORKDIR /backend
COPY backend .
RUN mvn clean install -DskipTests