update ad_field_trl set name = 'Delivery method' ,istranslated = 'Y' where ad_field_id = 2877 and ad_language = 'en_US';
update ad_field_trl set name = 'Payment method' ,istranslated = 'Y' where ad_field_id = 3113 and ad_language = 'en_US';
update ad_field_trl set name = 'Inbound by' ,istranslated = 'Y' where ad_field_id = 543186 and ad_language = 'en_US';
update ad_field_trl set name = 'Net Price' ,istranslated = 'Y' where ad_field_id = 1138 and ad_language = 'en_US';
update ad_field_trl set name = 'Terms & Conditions' ,istranslated = 'Y' where ad_field_id = 540003 and ad_language = 'en_US';
update ad_field_trl set name = 'Global Gap' ,istranslated = 'Y' where ad_field_id = 9706 and ad_language = 'en_US';
update ad_field_trl set name = 'Produce Planning' ,istranslated = 'Y' where ad_field_id = 553152 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner' ,istranslated = 'Y' where ad_field_id = 556914 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery from' ,istranslated = 'Y' where ad_field_id = 3419 and ad_language = 'en_US';
update ad_field_trl set name = 'Address' ,istranslated = 'Y' where ad_field_id = 547266 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging prescription/ product intruction' ,istranslated = 'Y' where ad_field_id = 553933 and ad_language = 'en_US';
update ad_field_trl set name = 'Availability Date' ,istranslated = 'Y' where ad_field_id = 553947 and ad_language = 'en_US';
update ad_field_trl set name = 'Attributes' ,istranslated = 'Y' where ad_field_id = 6535 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging description' ,istranslated = 'Y' where ad_field_id = 553020 and ad_language = 'en_US';
update ad_field_trl set name = 'CU-TU Assignment' ,istranslated = 'Y' where ad_field_id = 553021 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging capacity ' ,istranslated = 'Y' where ad_field_id = 553022 and ad_language = 'en_US';
update ad_field_trl set name = 'Target warehouse' ,istranslated = 'Y' where ad_field_id = 553023 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity TU' ,istranslated = 'Y' where ad_field_id = 554024 and ad_language = 'en_US';
update ad_field_trl set name = 'Price unit ' ,istranslated = 'Y' where ad_field_id = 554373 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity in price unit' ,istranslated = 'Y' where ad_field_id = 554674 and ad_language = 'en_US';
update ad_field_trl set name = 'Cost Center' ,istranslated = 'Y' where ad_field_id = 73442 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Warehouse' ,istranslated = 'Y' where ad_field_id = 66950 and ad_language = 'en_US';
update ad_field_trl set name = 'Stock' ,istranslated = 'Y' where ad_field_id = 500234 and ad_language = 'en_US';
update ad_field_trl set name = 'Priority' ,istranslated = 'Y' where ad_field_id = 500235 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Priority' ,istranslated = 'Y' where ad_field_id = 500236 and ad_language = 'en_US';
update ad_field_trl set name = 'Open' ,istranslated = 'Y' where ad_field_id = 500237 and ad_language = 'en_US';
update ad_field_trl set name = 'Nett (open)' ,istranslated = 'Y' where ad_field_id = 500240 and ad_language = 'en_US';
update ad_field_trl set name = 'Warehouse' ,istranslated = 'Y' where ad_field_id = 541240 and ad_language = 'en_US';
update ad_field_trl set name = 'Deliverymethod' ,istranslated = 'Y' where ad_field_id = 542110 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Deliverymethod' ,istranslated = 'Y' where ad_field_id = 542111 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery ' ,istranslated = 'Y' where ad_field_id = 542496 and ad_language = 'en_US';
update ad_field_trl set name = 'Deliveryaddress' ,istranslated = 'Y' where ad_field_id = 542497 and ad_language = 'en_US';
update ad_field_trl set name = 'Productdescription ' ,istranslated = 'Y' where ad_field_id = 546420 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery asignment ended' ,istranslated = 'Y' where ad_field_id = 546689 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery ID' ,istranslated = 'Y' where ad_field_id = 546690 and ad_language = 'en_US';
update ad_field_trl set name = 'Orderpicker' ,istranslated = 'Y' where ad_field_id = 546695 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt deliveryquantity ready' ,istranslated = 'Y' where ad_field_id = 546826 and ad_language = 'en_US';
update ad_field_trl set name = 'Pcs/diff.Price' ,istranslated = 'Y' where ad_field_id = 547264 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery Date' ,istranslated = 'Y' where ad_field_id = 547689 and ad_language = 'en_US';
update ad_field_trl set name = 'Address note' ,istranslated = 'Y' where ad_field_id = 547778 and ad_language = 'en_US';
update ad_field_trl set name = 'User address note' ,istranslated = 'Y' where ad_field_id = 547779 and ad_language = 'en_US';
update ad_field_trl set name = 'Deliverycontact' ,istranslated = 'Y' where ad_field_id = 547780 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Contact ' ,istranslated = 'Y' where ad_field_id = 547781 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Business Partner' ,istranslated = 'Y' where ad_field_id = 547782 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Delivery Address' ,istranslated = 'Y' where ad_field_id = 547783 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery to Alt. Delivery Address' ,istranslated = 'Y' where ad_field_id = 547784 and ad_language = 'en_US';
update ad_field_trl set name = 'Document Type' ,istranslated = 'Y' where ad_field_id = 547785 and ad_language = 'en_US';
update ad_field_trl set name = 'Target Warehouse' ,istranslated = 'Y' where ad_field_id = 549449 and ad_language = 'en_US';
update ad_field_trl set name = 'Record-ID' ,istranslated = 'Y' where ad_field_id = 550476 and ad_language = 'en_US';
update ad_field_trl set name = 'DB-Table' ,istranslated = 'Y' where ad_field_id = 550477 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging intruction/product assignment' ,istranslated = 'Y' where ad_field_id = 553027 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging capacity' ,istranslated = 'Y' where ad_field_id = 553028 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging description ' ,istranslated = 'Y' where ad_field_id = 553029 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Deliverydate' ,istranslated = 'Y' where ad_field_id = 553948 and ad_language = 'en_US';
update ad_field_trl set name = 'Date ready' ,istranslated = 'Y' where ad_field_id = 553949 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt. Packaging intruction/product assignment' ,istranslated = 'Y' where ad_field_id = 554352 and ad_language = 'en_US';
update ad_field_trl set name = 'Header  merge characteristic' ,istranslated = 'Y' where ad_field_id = 554353 and ad_language = 'en_US';
update ad_field_trl set name = 'Ordered Quantity (TU)' ,istranslated = 'Y' where ad_field_id = 554650 and ad_language = 'en_US';
update ad_field_trl set name = 'Ordered Quantity (LU)' ,istranslated = 'Y' where ad_field_id = 554651 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery Quantity (TU)' ,istranslated = 'Y' where ad_field_id = 554652 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivered Quantity (TU)' ,istranslated = 'Y' where ad_field_id = 554653 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivered Quantity (LU)' ,istranslated = 'Y' where ad_field_id = 554654 and ad_language = 'en_US';
update ad_field_trl set name = 'Delivery Quantity (LU)' ,istranslated = 'Y' where ad_field_id = 554655 and ad_language = 'en_US';
update ad_field_trl set name = 'Unit ' ,istranslated = 'Y' where ad_field_id = 554688 and ad_language = 'en_US';
update ad_field_trl set name = 'Currency' ,istranslated = 'Y' where ad_field_id = 554689 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity TU (reported)' ,istranslated = 'Y' where ad_field_id = 555273 and ad_language = 'en_US';
update ad_field_trl set name = 'Ordered Alt.' ,istranslated = 'Y' where ad_field_id = 555277 and ad_language = 'en_US';
update ad_field_trl set name = 'Drop shipment' ,istranslated = 'Y' where ad_field_id = 555405 and ad_language = 'en_US';
update ad_field_trl set name = 'In Process' ,istranslated = 'Y' where ad_field_id = 555864 and ad_language = 'en_US';
update ad_field_trl set name = 'Alt Date ready' ,istranslated = 'Y' where ad_field_id = 556128 and ad_language = 'en_US';
update ad_field_trl set name = 'Ordered' ,istranslated = 'Y' where ad_field_id = 556206 and ad_language = 'en_US';
update ad_field_trl set name = 'Processed' ,istranslated = 'Y' where ad_field_id = 554657 and ad_language = 'en_US';
update ad_field_trl set name = 'Customer' ,istranslated = 'Y' where ad_field_id = 554879 and ad_language = 'en_US';
update ad_field_trl set name = 'Section' ,istranslated = 'Y' where ad_field_id = 554880 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity' ,istranslated = 'Y' where ad_field_id = 554886 and ad_language = 'en_US';
update ad_field_trl set name = 'Product' ,istranslated = 'Y' where ad_field_id = 555858 and ad_language = 'en_US';
update ad_field_trl set name = 'Description' ,istranslated = 'Y' where ad_field_id = 556130 and ad_language = 'en_US';
update ad_field_trl set name = 'End note' ,istranslated = 'Y' where ad_field_id = 501685 and ad_language = 'en_US';
update ad_field_trl set name = 'Approve in/out shipment' ,istranslated = 'Y' where ad_field_id = 555479 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity TU (reported)' ,istranslated = 'Y' where ad_field_id = 555259 and ad_language = 'en_US';