update ad_field_trl set name = 'Document Nr.' ,istranslated = 'Y' where ad_field_id = 1081 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document Status' ,istranslated = 'Y' where ad_field_id = 1082 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Opdracht Verwerken' ,istranslated = 'Y' where ad_field_id = 1083 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document type' ,istranslated = 'Y' where ad_field_id = 1085 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 1086 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Orderdatum' ,istranslated = 'Y' where ad_field_id = 1093 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afgesproken datum' ,istranslated = 'Y' where ad_field_id = 1094 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verkoopmedewerker' ,istranslated = 'Y' where ad_field_id = 1098 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Valuta' ,istranslated = 'Y' where ad_field_id = 1103 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Facturatie adres' ,istranslated = 'Y' where ad_field_id = 1104 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leveradres' ,istranslated = 'Y' where ad_field_id = 1108 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prioriteit' ,istranslated = 'Y' where ad_field_id = 1110 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Magazijn' ,istranslated = 'Y' where ad_field_id = 1114 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Campagne ' ,istranslated = 'Y' where ad_field_id = 1324 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Opdrachtgever' ,istranslated = 'Y' where ad_field_id = 1573 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2052 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijs' ,istranslated = 'Y' where ad_field_id = 2109 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Referentie' ,istranslated = 'Y' where ad_field_id = 2111 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Toeslag ' ,istranslated = 'Y' where ad_field_id = 2112 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kostenplaats' ,istranslated = 'Y' where ad_field_id = 2589 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Besteladres' ,istranslated = 'Y' where ad_field_id = 2590 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Project' ,istranslated = 'Y' where ad_field_id = 2593 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levermethode' ,istranslated = 'Y' where ad_field_id = 2877 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Betalingsmethode' ,istranslated = 'Y' where ad_field_id = 3113 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Korting afdrukken' ,istranslated = 'Y' where ad_field_id = 3272 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuur relatie' ,istranslated = 'Y' where ad_field_id = 6559 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuuradres' ,istranslated = 'Y' where ad_field_id = 6561 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Boekende organisatie' ,istranslated = 'Y' where ad_field_id = 7038 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gebruiker 2' ,istranslated = 'Y' where ad_field_id = 7825 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gebruiker 1' ,istranslated = 'Y' where ad_field_id = 7826 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Valuta soort' ,istranslated = 'Y' where ad_field_id = 8653 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Referentie order' ,istranslated = 'Y' where ad_field_id = 9429 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkende aflevering' ,istranslated = 'Y' where ad_field_id = 10124 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkende klant' ,istranslated = 'Y' where ad_field_id = 55410 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkend adres' ,istranslated = 'Y' where ad_field_id = 55411 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Produkt' ,istranslated = 'Y' where ad_field_id = 505000 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aantal zonder emballage' ,istranslated = 'Y' where ad_field_id = 505001 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adres' ,istranslated = 'Y' where ad_field_id = 505102 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkend factuuradres' ,istranslated = 'Y' where ad_field_id = 505103 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijsmethode' ,istranslated = 'Y' where ad_field_id = 505273 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aanmaken order' ,istranslated = 'Y' where ad_field_id = 531089 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Referentie offerte/order' ,istranslated = 'Y' where ad_field_id = 531090 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Opdrachtsdatum (Ref. opdracht)' ,istranslated = 'Y' where ad_field_id = 531091 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gemaakt door' ,istranslated = 'Y' where ad_field_id = 540048 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gewijzigd door' ,istranslated = 'Y' where ad_field_id = 540049 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gemaakt op' ,istranslated = 'Y' where ad_field_id = 540050 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gewijzigd op' ,istranslated = 'Y' where ad_field_id = 540051 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Binnen gekomen door' ,istranslated = 'Y' where ad_field_id = 543186 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Geldigheid (dagen)' ,istranslated = 'Y' where ad_field_id = 547120 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Geldig tot' ,istranslated = 'Y' where ad_field_id = 547121 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkend afleveradres' ,istranslated = 'Y' where ad_field_id = 548081 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Losadres' ,istranslated = 'Y' where ad_field_id = 553692 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Los partner' ,istranslated = 'Y' where ad_field_id = 553693 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkend losadres' ,istranslated = 'Y' where ad_field_id = 553694 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Emballage' ,istranslated = 'Y' where ad_field_id = 553931 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid emballage' ,istranslated = 'Y' where ad_field_id = 553932 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Beschikbaarheidsdatum' ,istranslated = 'Y' where ad_field_id = 553946 and ad_language = 'nl_NL';
update ad_field_trl set name = 'DESADV' ,istranslated = 'Y' where ad_field_id = 555777 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Oorsprong ingave' ,istranslated = 'Y' where ad_field_id = 556234 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document dient per EDI verzonden te worden' ,istranslated = 'Y' where ad_field_id = 556237 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Status facturatie' ,istranslated = 'Y' where ad_field_id = 556278 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Status levering' ,istranslated = 'Y' where ad_field_id = 556289 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Regelnr' ,istranslated = 'Y' where ad_field_id = 1120 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 1126 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Product' ,istranslated = 'Y' where ad_field_id = 1127 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Eenheid' ,istranslated = 'Y' where ad_field_id = 1128 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Lijst Prijs' ,istranslated = 'Y' where ad_field_id = 1137 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Netto' ,istranslated = 'Y' where ad_field_id = 1138 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW' ,istranslated = 'Y' where ad_field_id = 1141 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levering aan' ,istranslated = 'Y' where ad_field_id = 1574 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afleveradres' ,istranslated = 'Y' where ad_field_id = 2595 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Regeltotaal' ,istranslated = 'Y' where ad_field_id = 2880 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kortings %' ,istranslated = 'Y' where ad_field_id = 3124 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kenmerken' ,istranslated = 'Y' where ad_field_id = 6570 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid' ,istranslated = 'Y' where ad_field_id = 10828 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijs' ,istranslated = 'Y' where ad_field_id = 10829 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kostenplaats' ,istranslated = 'Y' where ad_field_id = 13644 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Algemene voorwaarden' ,istranslated = 'Y' where ad_field_id = 540003 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Handmatige prijs' ,istranslated = 'Y' where ad_field_id = 546412 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leveringscontract' ,istranslated = 'Y' where ad_field_id = 547138 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Emballage' ,istranslated = 'Y' where ad_field_id = 552881 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingscapaciteit' ,istranslated = 'Y' where ad_field_id = 552882 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingsbeschrijving' ,istranslated = 'Y' where ad_field_id = 552883 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Emballage hoeveelheid' ,istranslated = 'Y' where ad_field_id = 554023 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijs eenheid' ,istranslated = 'Y' where ad_field_id = 554366 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid per prijseenheid' ,istranslated = 'Y' where ad_field_id = 554673 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 2123 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Taal' ,istranslated = 'Y' where ad_field_id = 2124 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2125 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Beschrijving' ,istranslated = 'Y' where ad_field_id = 2133 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 2136 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zoeksleutel' ,istranslated = 'Y' where ad_field_id = 2156 and ad_language = 'nl_NL';
update ad_field_trl set name = 'URL' ,istranslated = 'Y' where ad_field_id = 2164 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam 2' ,istranslated = 'Y' where ad_field_id = 3228 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakelijke partner' ,istranslated = 'Y' where ad_field_id = 3955 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levermethode' ,istranslated = 'Y' where ad_field_id = 9612 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Logo' ,istranslated = 'Y' where ad_field_id = 57533 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW Nummer' ,istranslated = 'Y' where ad_field_id = 502491 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Bedrijf' ,istranslated = 'Y' where ad_field_id = 545310 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Overige' ,istranslated = 'Y' where ad_field_id = 545318 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Ontvangt EDI documenten' ,istranslated = 'Y' where ad_field_id = 553177 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Beplantingsplan' ,istranslated = 'Y' where ad_field_id = 553867 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Standaard kopieer waarde' ,istranslated = 'Y' where ad_field_id = 554020 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Uitsluiten voor MRP' ,istranslated = 'Y' where ad_field_id = 555412 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Emballage' ,istranslated = 'Y' where ad_field_id = 555866 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levering' ,istranslated = 'Y' where ad_field_id = 555867 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Facturatie' ,istranslated = 'Y' where ad_field_id = 555868 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Standaard referentie op order' ,istranslated = 'Y' where ad_field_id = 556620 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Facturatie per email toegestaan' ,istranslated = 'Y' where ad_field_id = 557309 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 556885 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gemaakt' ,istranslated = 'Y' where ad_field_id = 556889 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Type' ,istranslated = 'Y' where ad_field_id = 556890 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document nummer' ,istranslated = 'Y' where ad_field_id = 556891 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Bijgewerkt' ,istranslated = 'Y' where ad_field_id = 556892 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Bijgewerkt door' ,istranslated = 'Y' where ad_field_id = 556893 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aangemaakt door' ,istranslated = 'Y' where ad_field_id = 556894 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 556896 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 553883 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 553884 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 553885 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakelijke partner' ,istranslated = 'Y' where ad_field_id = 553887 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Pakket' ,istranslated = 'Y' where ad_field_id = 553888 and ad_language = 'nl_NL';
update ad_field_trl set name = 'geldig vanaf' ,istranslated = 'Y' where ad_field_id = 553889 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Product' ,istranslated = 'Y' where ad_field_id = 553890 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 553891 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 553892 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 2400 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2402 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 2422 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zoeksleutel' ,istranslated = 'Y' where ad_field_id = 2433 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 2568 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aflevering' ,istranslated = 'Y' where ad_field_id = 3526 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 7621 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Eerste verkoop' ,istranslated = 'Y' where ad_field_id = 9634 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW vrijstelling' ,istranslated = 'Y' where ad_field_id = 9657 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamel pakbon toegestaan' ,istranslated = 'Y' where ad_field_id = 502495 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ADR klant' ,istranslated = 'Y' where ad_field_id = 553959 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamelmagazijn' ,istranslated = 'Y' where ad_field_id = 554259 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamelregel voor klantfacturen' ,istranslated = 'Y' where ad_field_id = 555566 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Emballage op pakbon niet tonen' ,istranslated = 'Y' where ad_field_id = 555853 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamelregel klantfacturen(facturatieschema)' ,istranslated = 'Y' where ad_field_id = 556192 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Statistiek Groep' ,istranslated = 'Y' where ad_field_id = 556535 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Rekeningschema' ,istranslated = 'Y' where ad_field_id = 1477 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 1478 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 1479 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 1595 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2073 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant vooruitbetaling' ,istranslated = 'Y' where ad_field_id = 2609 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant vorderingen' ,istranslated = 'Y' where ad_field_id = 2610 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Diensten vorderingen' ,istranslated = 'Y' where ad_field_id = 12354 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2444 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 2464 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zoeksleutel' ,istranslated = 'Y' where ad_field_id = 2475 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leverancier' ,istranslated = 'Y' where ad_field_id = 2567 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 7622 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Global GAP' ,istranslated = 'Y' where ad_field_id = 9706 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Inkoopprijs systeem' ,istranslated = 'Y' where ad_field_id = 505277 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Teeltplanning' ,istranslated = 'Y' where ad_field_id = 553152 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Oerproducent' ,istranslated = 'Y' where ad_field_id = 553175 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Producenten facturatie' ,istranslated = 'Y' where ad_field_id = 553176 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Inkoop BTW vrijstelling' ,istranslated = 'Y' where ad_field_id = 553806 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ADR Leverancier' ,istranslated = 'Y' where ad_field_id = 554030 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levering' ,istranslated = 'Y' where ad_field_id = 554264 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamelregel voor leveranciers facturen' ,istranslated = 'Y' where ad_field_id = 555567 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verzamelregel voor Leveranciersfacturen (Grootboekschema)' ,istranslated = 'Y' where ad_field_id = 556193 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Rekeningschema' ,istranslated = 'Y' where ad_field_id = 1484 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 1485 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 1486 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenpartner' ,istranslated = 'Y' where ad_field_id = 1596 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2065 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leveranciersbetrouwbaarheid' ,istranslated = 'Y' where ad_field_id = 2601 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Diensten leveranciersbetrouwbaarheid' ,istranslated = 'Y' where ad_field_id = 2602 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Vooruitbetaling leveranciers' ,istranslated = 'Y' where ad_field_id = 2603 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 504646 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 504650 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Geldig vanaf' ,istranslated = 'Y' where ad_field_id = 504653 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Geldig tot' ,istranslated = 'Y' where ad_field_id = 504654 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 504655 and ad_language = 'nl_NL';
update ad_field_trl set name = 'organisatie' ,istranslated = 'Y' where ad_field_id = 504657 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Sponsor' ,istranslated = 'Y' where ad_field_id = 504658 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Vertegenwoordiger' ,istranslated = 'Y' where ad_field_id = 504660 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Grootboekschema' ,istranslated = 'Y' where ad_field_id = 1492 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 1494 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 1495 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 1597 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2074 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Werknemer kosten' ,istranslated = 'Y' where ad_field_id = 2611 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Werknemer vooruitbetalingen' ,istranslated = 'Y' where ad_field_id = 2612 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 2181 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 2182 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 2183 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adres' ,istranslated = 'Y' where ad_field_id = 2185 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 2189 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 2190 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuuradres' ,istranslated = 'Y' where ad_field_id = 2193 and ad_language = 'nl_NL';
update ad_field_trl set name = 'EDI leveranciersadres' ,istranslated = 'Y' where ad_field_id = 2195 and ad_language = 'nl_NL';
update ad_field_trl set name = 'leveradres' ,istranslated = 'Y' where ad_field_id = 2196 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adres' ,istranslated = 'Y' where ad_field_id = 505104 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leveringsstandaard' ,istranslated = 'Y' where ad_field_id = 548907 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuurstandaard' ,istranslated = 'Y' where ad_field_id = 548910 and ad_language = 'nl_NL';
update ad_field_trl set name = 'GLN' ,istranslated = 'Y' where ad_field_id = 553179 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Losadres' ,istranslated = 'Y' where ad_field_id = 553808 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Vervangingswaarde' ,istranslated = 'Y' where ad_field_id = 554021 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 7005 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 7010 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 7011 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 7012 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Wachtwoord' ,istranslated = 'Y' where ad_field_id = 7013 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 7014 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 7016 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Email' ,istranslated = 'Y' where ad_field_id = 7017 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Begroeting' ,istranslated = 'Y' where ad_field_id = 7020 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Telefoon (alternatief)' ,istranslated = 'Y' where ad_field_id = 7021 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verjaardag' ,istranslated = 'Y' where ad_field_id = 7022 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Vestigingsplaats' ,istranslated = 'Y' where ad_field_id = 7023 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Telefoon' ,istranslated = 'Y' where ad_field_id = 7024 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Fax' ,istranslated = 'Y' where ad_field_id = 7025 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Titel' ,istranslated = 'Y' where ad_field_id = 7028 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Opmerkingen' ,istranslated = 'Y' where ad_field_id = 7029 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Positie' ,istranslated = 'Y' where ad_field_id = 12321 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoofdcontact' ,istranslated = 'Y' where ad_field_id = 500037 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verkoopcontact' ,istranslated = 'Y' where ad_field_id = 544640 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Achternaam' ,istranslated = 'Y' where ad_field_id = 544647 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Voornaam' ,istranslated = 'Y' where ad_field_id = 544655 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Inkoopcontact' ,istranslated = 'Y' where ad_field_id = 554202 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kerstgeschenk' ,istranslated = 'Y' where ad_field_id = 554753 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheidsmelding WebUI' ,istranslated = 'Y' where ad_field_id = 556856 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuur Email toegestaan' ,istranslated = 'Y' where ad_field_id = 557308 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Rekening-Nr' ,istranslated = 'Y' where ad_field_id = 2197 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Bank' ,istranslated = 'Y' where ad_field_id = 2200 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 2202 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 2203 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Plaats' ,istranslated = 'Y' where ad_field_id = 4096 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Email' ,istranslated = 'Y' where ad_field_id = 4097 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Rijbewijs-Nr' ,istranslated = 'Y' where ad_field_id = 4098 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ID-Nr' ,istranslated = 'Y' where ad_field_id = 4099 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam eigenaar' ,istranslated = 'Y' where ad_field_id = 4100 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Provincie' ,istranslated = 'Y' where ad_field_id = 4101 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Straat' ,istranslated = 'Y' where ad_field_id = 4102 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Postcode' ,istranslated = 'Y' where ad_field_id = 4103 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Contact' ,istranslated = 'Y' where ad_field_id = 4105 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ACH' ,istranslated = 'Y' where ad_field_id = 4111 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adres gecontroleerd' ,istranslated = 'Y' where ad_field_id = 4112 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Postcode gecontroleerd' ,istranslated = 'Y' where ad_field_id = 4113 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Land' ,istranslated = 'Y' where ad_field_id = 6298 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant gebruik' ,istranslated = 'Y' where ad_field_id = 13699 and ad_language = 'nl_NL';
update ad_field_trl set name = 'IBAN' ,istranslated = 'Y' where ad_field_id = 542821 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ESR deelnemernummer' ,istranslated = 'Y' where ad_field_id = 551427 and ad_language = 'nl_NL';
update ad_field_trl set name = 'ESR rekening' ,istranslated = 'Y' where ad_field_id = 551429 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Standaard' ,istranslated = 'Y' where ad_field_id = 551430 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Valuta' ,istranslated = 'Y' where ad_field_id = 551666 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Naam' ,istranslated = 'Y' where ad_field_id = 556433 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 555265 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 555267 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afdrukformaat' ,istranslated = 'Y' where ad_field_id = 555268 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document type' ,istranslated = 'Y' where ad_field_id = 555269 and ad_language = 'nl_NL';
update ad_field_trl set name = 'DB tabel' ,istranslated = 'Y' where ad_field_id = 556773 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 556906 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 556907 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Aktief' ,istranslated = 'Y' where ad_field_id = 556908 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Krediet gebruikt' ,istranslated = 'Y' where ad_field_id = 556910 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Openstaand saldo' ,istranslated = 'Y' where ad_field_id = 556911 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Huidig totaalsaldo' ,istranslated = 'Y' where ad_field_id = 556912 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kredietstatus' ,istranslated = 'Y' where ad_field_id = 556913 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Zakenrelatie' ,istranslated = 'Y' where ad_field_id = 556914 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levering van ' ,istranslated = 'Y' where ad_field_id = 3419 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document nr.' ,istranslated = 'Y' where ad_field_id = 3424 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Document status' ,istranslated = 'Y' where ad_field_id = 3425 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Opdracht verwerken' ,istranslated = 'Y' where ad_field_id = 3426 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Documenttype' ,istranslated = 'Y' where ad_field_id = 3427 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Doeldocumenttype' ,istranslated = 'Y' where ad_field_id = 3428 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Besteldatum' ,istranslated = 'Y' where ad_field_id = 3435 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Toegezegde datum' ,istranslated = 'Y' where ad_field_id = 3436 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Inkoper' ,istranslated = 'Y' where ad_field_id = 3438 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Valuta' ,istranslated = 'Y' where ad_field_id = 3441 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Facturatie' ,istranslated = 'Y' where ad_field_id = 3442 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Levering door' ,istranslated = 'Y' where ad_field_id = 3444 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prioriteit' ,istranslated = 'Y' where ad_field_id = 3448 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Totaal regels' ,istranslated = 'Y' where ad_field_id = 3449 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Totaal bedrag' ,istranslated = 'Y' where ad_field_id = 3450 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Magazijn' ,istranslated = 'Y' where ad_field_id = 3451 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Leveringscontact' ,istranslated = 'Y' where ad_field_id = 3452 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 3453 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Referentie' ,istranslated = 'Y' where ad_field_id = 3455 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adres' ,istranslated = 'Y' where ad_field_id = 3458 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Betaalmethode' ,istranslated = 'Y' where ad_field_id = 3466 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Korting afdrukken' ,istranslated = 'Y' where ad_field_id = 3467 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuurcontact' ,istranslated = 'Y' where ad_field_id = 6504 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuur van' ,istranslated = 'Y' where ad_field_id = 6505 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Regels kopieren' ,istranslated = 'Y' where ad_field_id = 6506 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuuradres' ,istranslated = 'Y' where ad_field_id = 6507 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Drop aflevering' ,istranslated = 'Y' where ad_field_id = 10123 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Orderregel_includedTab' ,istranslated = 'Y' where ad_field_id = 540012 and ad_language = 'nl_NL';
update ad_field_trl set name = 'prijssysteem' ,istranslated = 'Y' where ad_field_id = 543372 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Adrestekst' ,istranslated = 'Y' where ad_field_id = 547266 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afwijkend factuuradres' ,istranslated = 'Y' where ad_field_id = 547267 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afleveradres' ,istranslated = 'Y' where ad_field_id = 547270 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Product' ,istranslated = 'Y' where ad_field_id = 552658 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid CE' ,istranslated = 'Y' where ad_field_id = 552659 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingsvoorschrift/verpakkingsinstructie' ,istranslated = 'Y' where ad_field_id = 553933 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid TU' ,istranslated = 'Y' where ad_field_id = 553934 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Beschikbaarheidsdatum' ,istranslated = 'Y' where ad_field_id = 553947 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Factuur status' ,istranslated = 'Y' where ad_field_id = 556290 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afleverings status' ,istranslated = 'Y' where ad_field_id = 556291 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Batchdatum' ,istranslated = 'Y' where ad_field_id = 557472 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kortings%' ,istranslated = 'Y' where ad_field_id = 3383 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Produkt' ,istranslated = 'Y' where ad_field_id = 3386 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Eenheid' ,istranslated = 'Y' where ad_field_id = 3387 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijslijst Prijs' ,istranslated = 'Y' where ad_field_id = 3395 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Stuksprijs' ,istranslated = 'Y' where ad_field_id = 3396 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Omschrijving' ,istranslated = 'Y' where ad_field_id = 3398 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Lijnnr.' ,istranslated = 'Y' where ad_field_id = 3403 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afleverdatum' ,istranslated = 'Y' where ad_field_id = 3406 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Regelhoeveelheid' ,istranslated = 'Y' where ad_field_id = 3416 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Kenmerken' ,istranslated = 'Y' where ad_field_id = 6535 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid' ,istranslated = 'Y' where ad_field_id = 10826 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijs' ,istranslated = 'Y' where ad_field_id = 10827 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Afroepdatum' ,istranslated = 'Y' where ad_field_id = 542101 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingsbeschrijving' ,istranslated = 'Y' where ad_field_id = 553020 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingsvoorschrift/verpakkingsinstructie' ,istranslated = 'Y' where ad_field_id = 553021 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingscapaciteit' ,istranslated = 'Y' where ad_field_id = 553022 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Doelmagazijn' ,istranslated = 'Y' where ad_field_id = 553023 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid TU' ,istranslated = 'Y' where ad_field_id = 554024 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijseenheid' ,istranslated = 'Y' where ad_field_id = 554373 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Hoeveelheid in prijsunit' ,istranslated = 'Y' where ad_field_id = 554674 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Klant' ,istranslated = 'Y' where ad_field_id = 3468 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Organisatie' ,istranslated = 'Y' where ad_field_id = 3469 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW' ,istranslated = 'Y' where ad_field_id = 3470 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Inkooporder' ,istranslated = 'Y' where ad_field_id = 3472 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW bedrag' ,istranslated = 'Y' where ad_field_id = 3473 and ad_language = 'nl_NL';
update ad_field_trl set name = 'BTW basis' ,istranslated = 'Y' where ad_field_id = 3474 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Prijs inclusief BTW' ,istranslated = 'Y' where ad_field_id = 11010 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Gehele BTW' ,istranslated = 'Y' where ad_field_id = 74294 and ad_language = 'nl_NL';
update ad_field_trl set name = 'Verpakkingsbelasting' ,istranslated = 'Y' where ad_field_id = 556922 and ad_language = 'nl_NL';