export const CLEAR_LOADED_DATA = 'huManager/CLEAR_LOADED_DATA';
export const HANDLING_UNIT_LOADED = 'huManager/HANDLING_UNIT_LOADED';
export const CHANGE_CLEARANCE_STATUS = 'huManager/CHANGE_CLEARANCE_STATUS';
