
update ad_field_trl set name = 'VAT ID', istranslated = 'Y' where ad_field_id = 502491 and ad_language = 'en_US';
update ad_field_trl set name = 'Company', istranslated = 'Y' where ad_field_id = 545310 and ad_language = 'en_US';
update ad_field_trl set name = 'misc', istranslated = 'Y' where ad_field_id = 545318 and ad_language = 'en_US';
update ad_field_trl set name = 'Company Name', istranslated = 'Y' where ad_field_id = 545303 and ad_language = 'en_US';
update ad_field_trl set name = 'receives EDI documents', istranslated = 'Y' where ad_field_id = 553177 and ad_language = 'en_US';
update ad_field_trl set name = 'EDI-ID of the recipient', istranslated = 'Y' where ad_field_id = 553178 and ad_language = 'en_US';
update ad_field_trl set name = 'Anbauplanung', istranslated = 'Y' where ad_field_id = 553867 and ad_language = 'en_US';
update ad_field_trl set name = 'Default-Replication-Value', istranslated = 'Y' where ad_field_id = 554020 and ad_language = 'en_US';
update ad_field_trl set name = 'Exclude from MRP', istranslated = 'Y' where ad_field_id = 555412 and ad_language = 'en_US';
update ad_field_trl set name = 'Memo Trading Unit', istranslated = 'Y' where ad_field_id = 555866 and ad_language = 'en_US';
update ad_field_trl set name = 'Memo Shipment', istranslated = 'Y' where ad_field_id = 555867 and ad_language = 'en_US';
update ad_field_trl set name = 'Memo Invoicing', istranslated = 'Y' where ad_field_id = 555868 and ad_language = 'en_US';
update ad_field_trl set name = 'Default Order Reference Value', istranslated = 'Y' where ad_field_id = 556620 and ad_language = 'en_US';
update ad_field_trl set name = 'Default Order Reference Template', istranslated = 'Y' where ad_field_id = 556621 and ad_language = 'en_US';
update ad_field_trl set name = 'CU per TU on infinite capacity', istranslated = 'Y' where ad_field_id = 556622 and ad_language = 'en_US';
update ad_field_trl set name = 'BillTo Default', istranslated = 'Y' where ad_field_id = 548910 and ad_language = 'en_US';
update ad_field_trl set name = 'ShipTo Default', istranslated = 'Y' where ad_field_id = 548907 and ad_language = 'en_US';
update ad_field_trl set name = 'Address', istranslated = 'Y' where ad_field_id = 505104 and ad_language = 'en_US';
update ad_field_trl set name = 'Default-Replication-Value', istranslated = 'Y' where ad_field_id = 554021 and ad_language = 'en_US';
update ad_field_trl set name = 'Unloading Location', istranslated = 'Y' where ad_field_id = 553808 and ad_language = 'en_US';
update ad_field_trl set name = 'GLN', istranslated = 'Y' where ad_field_id = 553179 and ad_language = 'en_US';
update ad_field_trl set name = 'ADR-Region', istranslated = 'Y' where ad_field_id = 553807 and ad_language = 'en_US';
update ad_field_trl set name = 'ADR-Customer', istranslated = 'Y' where ad_field_id = 553959 and ad_language = 'en_US';
update ad_field_trl set name = 'Picking Warehouse', istranslated = 'Y' where ad_field_id = 554259 and ad_language = 'en_US';
update ad_field_trl set name = 'Aggregationrule Customer Invoices', istranslated = 'Y' where ad_field_id = 555566 and ad_language = 'en_US';
update ad_field_trl set name = 'Do not show trade unit on shipment note', istranslated = 'Y' where ad_field_id = 555853 and ad_language = 'en_US';
update ad_field_trl set name = 'Aggregationrule Customer Invoices (Invoice Schedule))', istranslated = 'Y' where ad_field_id = 556192 and ad_language = 'en_US';
update ad_field_trl set name = 'Kundengruppe', istranslated = 'Y' where ad_field_id = 556295 and ad_language = 'en_US';
update ad_field_trl set name = 'disable Order Checkup', istranslated = 'Y' where ad_field_id = 556360 and ad_language = 'en_US';
update ad_field_trl set name = 'Statistic Group', istranslated = 'Y' where ad_field_id = 556535 and ad_language = 'en_US';
update ad_field_trl set name = 'consolidation for shipments allowed', istranslated = 'Y' where ad_field_id = 502495 and ad_language = 'en_US';
update ad_field_trl set name = 'Price System', istranslated = 'Y' where ad_field_id = 505287 and ad_language = 'en_US';
update ad_field_trl set name = 'Anbauplanung', istranslated = 'Y' where ad_field_id = 553152 and ad_language = 'en_US';
update ad_field_trl set name = 'Original Producer', istranslated = 'Y' where ad_field_id = 553175 and ad_language = 'en_US';
update ad_field_trl set name = 'Producer Billing', istranslated = 'Y' where ad_field_id = 553176 and ad_language = 'en_US';
update ad_field_trl set name = 'ADR Vendor', istranslated = 'Y' where ad_field_id = 554030 and ad_language = 'en_US';
update ad_field_trl set name = 'ADR-Certification', istranslated = 'Y' where ad_field_id = 553206 and ad_language = 'en_US';
update ad_field_trl set name = 'Shipment', istranslated = 'Y' where ad_field_id = 554264 and ad_language = 'en_US';
update ad_field_trl set name = 'Aggregationrule Vendor Invoices', istranslated = 'Y' where ad_field_id = 555567 and ad_language = 'en_US';
update ad_field_trl set name = 'Aggregationrule Vendor Invoices (Invoice Schedule)', istranslated = 'Y' where ad_field_id = 556193 and ad_language = 'en_US';
update ad_field_trl set name = 'Purchasing - Tax Excempt', istranslated = 'Y' where ad_field_id = 553806 and ad_language = 'en_US';
update ad_field_trl set name = 'Purchasing Price System', istranslated = 'Y' where ad_field_id = 505277 and ad_language = 'en_US';
update ad_field_trl set name = 'IBAN', istranslated = 'Y' where ad_field_id = 542821 and ad_language = 'en_US';
update ad_field_trl set name = 'Standard', istranslated = 'Y' where ad_field_id = 551430 and ad_language = 'en_US';
update ad_field_trl set name = 'ESR Member Number', istranslated = 'Y' where ad_field_id = 551427 and ad_language = 'en_US';
update ad_field_trl set name = 'ESR Account Number', istranslated = 'Y' where ad_field_id = 551429 and ad_language = 'en_US';
update ad_field_trl set name = 'Currency', istranslated = 'Y' where ad_field_id = 551666 and ad_language = 'en_US';
update ad_field_trl set name = 'Default ESR Account', istranslated = 'Y' where ad_field_id = 551911 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 556433 and ad_language = 'en_US';
update ad_field_trl set name = 'Default Contact', istranslated = 'Y' where ad_field_id = 500037 and ad_language = 'en_US';
update ad_field_trl set name = 'Lastname', istranslated = 'Y' where ad_field_id = 544647 and ad_language = 'en_US';
update ad_field_trl set name = 'Firstname', istranslated = 'Y' where ad_field_id = 544655 and ad_language = 'en_US';
update ad_field_trl set name = 'Christmas Gift', istranslated = 'Y' where ad_field_id = 554753 and ad_language = 'en_US';
update ad_field_trl set name = 'Purchase Contact', istranslated = 'Y' where ad_field_id = 554202 and ad_language = 'en_US';
update ad_field_trl set name = 'Sales Contact', istranslated = 'Y' where ad_field_id = 544640 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 504657 and ad_language = 'en_US';
update ad_field_trl set name = 'Client', istranslated = 'Y' where ad_field_id = 504655 and ad_language = 'en_US';
update ad_field_trl set name = 'Sponsor', istranslated = 'Y' where ad_field_id = 504658 and ad_language = 'en_US';
update ad_field_trl set name = 'valid to', istranslated = 'Y' where ad_field_id = 504654 and ad_language = 'en_US';
update ad_field_trl set name = 'valid from', istranslated = 'Y' where ad_field_id = 504653 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 504646 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 504650 and ad_language = 'en_US';
update ad_field_trl set name = 'Sales Representative', istranslated = 'Y' where ad_field_id = 504660 and ad_language = 'en_US';
update ad_field_trl set name = 'Client', istranslated = 'Y' where ad_field_id = 553883 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner', istranslated = 'Y' where ad_field_id = 553887 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 553885 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 553884 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 553892 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 553891 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 553890 and ad_language = 'en_US';
update ad_field_trl set name = 'valid from', istranslated = 'Y' where ad_field_id = 553889 and ad_language = 'en_US';
update ad_field_trl set name = 'Parcel', istranslated = 'Y' where ad_field_id = 553888 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 555265 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner', istranslated = 'Y' where ad_field_id = 555267 and ad_language = 'en_US';
update ad_field_trl set name = 'Print Format', istranslated = 'Y' where ad_field_id = 555268 and ad_language = 'en_US';
update ad_field_trl set name = 'Doc Type', istranslated = 'Y' where ad_field_id = 555269 and ad_language = 'en_US';
update ad_field_trl set name = 'Misc Item', istranslated = 'Y' where ad_field_id = 541239 and ad_language = 'en_US';
update ad_field_trl set name = 'is produced', istranslated = 'Y' where ad_field_id = 556296 and ad_language = 'en_US';
update ad_field_trl set name = 'Salesgroup_UOM_ID', istranslated = 'Y' where ad_field_id = 556610 and ad_language = 'en_US';
update ad_field_trl set name = 'Statistics Group', istranslated = 'Y' where ad_field_id = 556536 and ad_language = 'en_US';
update ad_field_trl set name = 'Exclude from MRP', istranslated = 'Y' where ad_field_id = 555413 and ad_language = 'en_US';
update ad_field_trl set name = 'Calendar (Arrival Time)', istranslated = 'Y' where ad_field_id = 502046 and ad_language = 'en_US';
update ad_field_trl set name = 'Period Arrival Time)', istranslated = 'Y' where ad_field_id = 502047 and ad_language = 'en_US';
update ad_field_trl set name = 'Time to market (weeks)', istranslated = 'Y' where ad_field_id = 502045 and ad_language = 'en_US';
update ad_field_trl set name = 'Tax Category', istranslated = 'Y' where ad_field_id = 542573 and ad_language = 'en_US';
update ad_field_trl set name = 'UOM', istranslated = 'Y' where ad_field_id = 554663 and ad_language = 'en_US';
update ad_field_trl set name = 'Cost Unit', istranslated = 'Y' where ad_field_id = 73442 and ad_language = 'en_US';
update ad_field_trl set name = 'Dropshipment', istranslated = 'Y' where ad_field_id = 555404 and ad_language = 'en_US';
update ad_field_trl set name = 'C_BPartner_Vendor_ID', istranslated = 'Y' where ad_field_id = 555195 and ad_language = 'en_US';
update ad_field_trl set name = 'Default Vendor', istranslated = 'Y' where ad_field_id = 553879 and ad_language = 'en_US';
update ad_field_trl set name = 'for vendor', istranslated = 'Y' where ad_field_id = 552671 and ad_language = 'en_US';
update ad_field_trl set name = 'for customer', istranslated = 'Y' where ad_field_id = 552670 and ad_language = 'en_US';
update ad_field_trl set name = 'Product Category', istranslated = 'Y' where ad_field_id = 552665 and ad_language = 'en_US';
update ad_field_trl set name = 'CU-EAN', istranslated = 'Y' where ad_field_id = 552669 and ad_language = 'en_US';
update ad_field_trl set name = 'Product Description', istranslated = 'Y' where ad_field_id = 552667 and ad_language = 'en_US';
update ad_field_trl set name = 'Product name', istranslated = 'Y' where ad_field_id = 552668 and ad_language = 'en_US';
update ad_field_trl set name = 'Product number', istranslated = 'Y' where ad_field_id = 552666 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 552272 and ad_language = 'en_US';
update ad_field_trl set name = 'Packing Instruction', istranslated = 'Y' where ad_field_id = 552270 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 552274 and ad_language = 'en_US';
update ad_field_trl set name = 'UOM', istranslated = 'Y' where ad_field_id = 552268 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552262 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552273 and ad_language = 'en_US';
update ad_field_trl set name = 'valid to', istranslated = 'Y' where ad_field_id = 553010 and ad_language = 'en_US';
update ad_field_trl set name = 'valid from', istranslated = 'Y' where ad_field_id = 553009 and ad_language = 'en_US';
update ad_field_trl set name = 'TU-EAN', istranslated = 'Y' where ad_field_id = 553744 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner', istranslated = 'Y' where ad_field_id = 552884 and ad_language = 'en_US';
update ad_field_trl set name = 'infinite capacity', istranslated = 'Y' where ad_field_id = 70139 and ad_language = 'en_US';
update ad_field_trl set name = 'Client', istranslated = 'Y' where ad_field_id = 552267 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 553956 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity', istranslated = 'Y' where ad_field_id = 552269 and ad_language = 'en_US';
update ad_field_trl set name = 'Product-Allocation', istranslated = 'Y' where ad_field_id = 556617 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 556614 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 556616 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 556613 and ad_language = 'en_US';
update ad_field_trl set name = 'Name on Invoice', istranslated = 'Y' where ad_field_id = 543389 and ad_language = 'en_US';
update ad_field_trl set name = 'Name on Invoice', istranslated = 'Y' where ad_field_id = 543390 and ad_language = 'en_US';
update ad_field_trl set name = 'Updated on', istranslated = 'Y' where ad_field_id = 540051 and ad_language = 'en_US';
update ad_field_trl set name = 'Created on', istranslated = 'Y' where ad_field_id = 540050 and ad_language = 'en_US';
update ad_field_trl set name = 'Created by', istranslated = 'Y' where ad_field_id = 540048 and ad_language = 'en_US';
update ad_field_trl set name = 'updated by', istranslated = 'Y' where ad_field_id = 540049 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 505000 and ad_language = 'en_US';
update ad_field_trl set name = 'Qty without Trading Unit', istranslated = 'Y' where ad_field_id = 505001 and ad_language = 'en_US';
update ad_field_trl set name = 'Diff. Invoice Address', istranslated = 'Y' where ad_field_id = 505103 and ad_language = 'en_US';
update ad_field_trl set name = 'Full Address', istranslated = 'Y' where ad_field_id = 505102 and ad_language = 'en_US';
update ad_field_trl set name = 'Price System', istranslated = 'Y' where ad_field_id = 505273 and ad_language = 'en_US';
update ad_field_trl set name = 'Create Order', istranslated = 'Y' where ad_field_id = 531089 and ad_language = 'en_US';
update ad_field_trl set name = 'Order Date (Ref. Order)', istranslated = 'Y' where ad_field_id = 531091 and ad_language = 'en_US';
update ad_field_trl set name = 'Reference Quote / Order', istranslated = 'Y' where ad_field_id = 531090 and ad_language = 'en_US';
update ad_field_trl set name = 'inbound via', istranslated = 'Y' where ad_field_id = 543186 and ad_language = 'en_US';
update ad_field_trl set name = 'Days valid', istranslated = 'Y' where ad_field_id = 547120 and ad_language = 'en_US';
update ad_field_trl set name = 'valid to', istranslated = 'Y' where ad_field_id = 547121 and ad_language = 'en_US';
update ad_field_trl set name = 'Diff. Shipment Address', istranslated = 'Y' where ad_field_id = 548081 and ad_language = 'en_US';
update ad_field_trl set name = 'diff. unloading point', istranslated = 'Y' where ad_field_id = 553694 and ad_language = 'en_US';
update ad_field_trl set name = 'unloading partner', istranslated = 'Y' where ad_field_id = 553693 and ad_language = 'en_US';
update ad_field_trl set name = 'unloading address', istranslated = 'Y' where ad_field_id = 553692 and ad_language = 'en_US';
update ad_field_trl set name = 'Trade unit', istranslated = 'Y' where ad_field_id = 553931 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity Trade Unit', istranslated = 'Y' where ad_field_id = 553932 and ad_language = 'en_US';
update ad_field_trl set name = 'Date of Provisioning', istranslated = 'Y' where ad_field_id = 553946 and ad_language = 'en_US';
update ad_field_trl set name = 'DESADV', istranslated = 'Y' where ad_field_id = 555777 and ad_language = 'en_US';
update ad_field_trl set name = 'Inputsource', istranslated = 'Y' where ad_field_id = 556234 and ad_language = 'en_US';
update ad_field_trl set name = 'Document to be sent via EDI', istranslated = 'Y' where ad_field_id = 556237 and ad_language = 'en_US';
update ad_field_trl set name = 'Status Billing', istranslated = 'Y' where ad_field_id = 556278 and ad_language = 'en_US';
update ad_field_trl set name = 'Status Shipment', istranslated = 'Y' where ad_field_id = 556289 and ad_language = 'en_US';
update ad_field_trl set name = 'Orderline_includedTab', istranslated = 'Y' where ad_field_id = 1000000 and ad_language = 'en_US';
update ad_field_trl set name = 'Shipment Contact', istranslated = 'Y' where ad_field_id = 547138 and ad_language = 'en_US';
update ad_field_trl set name = 'manual price', istranslated = 'Y' where ad_field_id = 546412 and ad_language = 'en_US';
update ad_field_trl set name = 'Trading Unit', istranslated = 'Y' where ad_field_id = 552881 and ad_language = 'en_US';
update ad_field_trl set name = 'Loading Capacity', istranslated = 'Y' where ad_field_id = 552882 and ad_language = 'en_US';
update ad_field_trl set name = 'Packing Description', istranslated = 'Y' where ad_field_id = 552883 and ad_language = 'en_US';
update ad_field_trl set name = 'Trading Unit Quantity', istranslated = 'Y' where ad_field_id = 554023 and ad_language = 'en_US';
update ad_field_trl set name = 'Price Unit', istranslated = 'Y' where ad_field_id = 554366 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity in Price Unit', istranslated = 'Y' where ad_field_id = 554673 and ad_language = 'en_US';
update ad_field_trl set name = 'Whole Tax', istranslated = 'Y' where ad_field_id = 74293 and ad_language = 'en_US';
update ad_field_trl set name = 'Trading Unit', istranslated = 'Y' where ad_field_id = 556619 and ad_language = 'en_US';
update ad_field_trl set name = 'Packaging Material ', istranslated = 'Y' where ad_field_id = 556611 and ad_language = 'en_US';
update ad_field_trl set name = 'Exclude from MRP', istranslated = 'Y' where ad_field_id = 555418 and ad_language = 'en_US';
update ad_field_trl set name = 'Attribute Set', istranslated = 'Y' where ad_field_id = 553957 and ad_language = 'en_US';
update ad_field_trl set name = 'Export EDI Status', istranslated = 'Y' where ad_field_id = 551554 and ad_language = 'en_US';
update ad_field_trl set name = 'Adjustment Charge', istranslated = 'Y' where ad_field_id = 553945 and ad_language = 'en_US';
update ad_field_trl set name = 'Document to be sent via EDI', istranslated = 'Y' where ad_field_id = 551567 and ad_language = 'en_US';
update ad_field_trl set name = 'EDI Error Message', istranslated = 'Y' where ad_field_id = 551574 and ad_language = 'en_US';
update ad_field_trl set name = 'Credit Amount invoiceable again', istranslated = 'Y' where ad_field_id = 556177 and ad_language = 'en_US';
update ad_field_trl set name = 'Reference to Credit Memo', istranslated = 'Y' where ad_field_id = 504607 and ad_language = 'en_US';
update ad_field_trl set name = 'Addresds', istranslated = 'Y' where ad_field_id = 505106 and ad_language = 'en_US';
update ad_field_trl set name = 'Reversal ID', istranslated = 'Y' where ad_field_id = 551570 and ad_language = 'en_US';
update ad_field_trl set name = 'Document Foot Note', istranslated = 'Y' where ad_field_id = 501684 and ad_language = 'en_US';
update ad_field_trl set name = 'Create Credit Memo', istranslated = 'Y' where ad_field_id = 504605 and ad_language = 'en_US';
update ad_field_trl set name = 'Invoice_includedTab', istranslated = 'Y' where ad_field_id = 540009 and ad_language = 'en_US';
update ad_field_trl set name = 'Credit Reason', istranslated = 'Y' where ad_field_id = 542147 and ad_language = 'en_US';
update ad_field_trl set name = 'Diff. Prod. Desc.', istranslated = 'Y' where ad_field_id = 504493 and ad_language = 'en_US';
update ad_field_trl set name = 'Credit Reason', istranslated = 'Y' where ad_field_id = 542148 and ad_language = 'en_US';
update ad_field_trl set name = 'PS', istranslated = 'Y' where ad_field_id = 547263 and ad_language = 'en_US';
update ad_field_trl set name = 'Discount %', istranslated = 'Y' where ad_field_id = 548656 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantitiy TU', istranslated = 'Y' where ad_field_id = 554025 and ad_language = 'en_US';
update ad_field_trl set name = 'Price Unit', istranslated = 'Y' where ad_field_id = 554362 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity in Price Unit', istranslated = 'Y' where ad_field_id = 554676 and ad_language = 'en_US';
update ad_field_trl set name = 'Packing Instruction - Product - Allocation', istranslated = 'Y' where ad_field_id = 556180 and ad_language = 'en_US';
update ad_field_trl set name = 'Order', istranslated = 'Y' where ad_field_id = 556241 and ad_language = 'en_US';
update ad_field_trl set name = 'Whole Tax', istranslated = 'Y' where ad_field_id = 74292 and ad_language = 'en_US';
update ad_field_trl set name = 'Doc No.', istranslated = 'Y' where ad_field_id = 555649 and ad_language = 'en_US';
update ad_field_trl set name = 'Client', istranslated = 'Y' where ad_field_id = 555638 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 555639 and ad_language = 'en_US';
update ad_field_trl set name = 'Shipping Line', istranslated = 'Y' where ad_field_id = 555641 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 555643 and ad_language = 'en_US';
update ad_field_trl set name = 'Invoice Line', istranslated = 'Y' where ad_field_id = 555642 and ad_language = 'en_US';
update ad_field_trl set name = 'Date', istranslated = 'Y' where ad_field_id = 555644 and ad_language = 'en_US';
update ad_field_trl set name = 'Attribute Set Instance', istranslated = 'Y' where ad_field_id = 555651 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity', istranslated = 'Y' where ad_field_id = 555648 and ad_language = 'en_US';
update ad_field_trl set name = 'Box Label', istranslated = 'Y' where ad_field_id = 542971 and ad_language = 'en_US';
update ad_field_trl set name = 'Address', istranslated = 'Y' where ad_field_id = 505108 and ad_language = 'en_US';
update ad_field_trl set name = 'IncotermLocation', istranslated = 'Y' where ad_field_id = 501623 and ad_language = 'en_US';
update ad_field_trl set name = 'Incoterm', istranslated = 'Y' where ad_field_id = 501622 and ad_language = 'en_US';
update ad_field_trl set name = 'InOutLine_includedTab', istranslated = 'Y' where ad_field_id = 1000005 and ad_language = 'en_US';
update ad_field_trl set name = 'Approve Inout / Receipt', istranslated = 'Y' where ad_field_id = 555479 and ad_language = 'en_US';
update ad_field_trl set name = 'DESADV', istranslated = 'Y' where ad_field_id = 555713 and ad_language = 'en_US';
update ad_field_trl set name = 'EDI Error Message', istranslated = 'Y' where ad_field_id = 553215 and ad_language = 'en_US';
update ad_field_trl set name = 'Send Doc via EDI', istranslated = 'Y' where ad_field_id = 553213 and ad_language = 'en_US';
update ad_field_trl set name = 'Target Warehouse', istranslated = 'Y' where ad_field_id = 549453 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity TU', istranslated = 'Y' where ad_field_id = 554027 and ad_language = 'en_US';
update ad_field_trl set name = 'Packing Instruction - Product - Allocation', istranslated = 'Y' where ad_field_id = 555194 and ad_language = 'en_US';
update ad_field_trl set name = 'Preis', istranslated = 'Y' where ad_field_id = 555190 and ad_language = 'en_US';
update ad_field_trl set name = 'Manual Packing Material', istranslated = 'Y' where ad_field_id = 555193 and ad_language = 'en_US';
update ad_field_trl set name = 'Menge TU (ausgewiesen)', istranslated = 'Y' where ad_field_id = 555259 and ad_language = 'en_US';
update ad_field_trl set name = 'Productnummer', istranslated = 'Y' where ad_field_id = 556211 and ad_language = 'en_US';
update ad_field_trl set name = 'diff. Packing Instruction - Product - Allocation', istranslated = 'Y' where ad_field_id = 555262 and ad_language = 'en_US';
update ad_field_trl set name = 'Diff. Prod. Desc.', istranslated = 'Y' where ad_field_id = 504492 and ad_language = 'en_US';
update ad_field_trl set name = 'Products', istranslated = 'Y' where ad_field_id = 555856 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 554897 and ad_language = 'en_US';
update ad_field_trl set name = 'Handling Units', istranslated = 'Y' where ad_field_id = 554899 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity', istranslated = 'Y' where ad_field_id = 554902 and ad_language = 'en_US';
update ad_field_trl set name = 'Transfer Packing Materials', istranslated = 'Y' where ad_field_id = 555180 and ad_language = 'en_US';
update ad_field_trl set name = 'Handling Unit (LU)', istranslated = 'Y' where ad_field_id = 555181 and ad_language = 'en_US';
update ad_field_trl set name = 'Handling Unit (TU)', istranslated = 'Y' where ad_field_id = 555182 and ad_language = 'en_US';
update ad_field_trl set name = 'Virtual Handling Unit (VHU)', istranslated = 'Y' where ad_field_id = 555403 and ad_language = 'en_US';
update ad_field_trl set name = 'Customer', istranslated = 'Y' where ad_field_id = 556294 and ad_language = 'en_US';
update ad_field_trl set name = 'Price System', istranslated = 'Y' where ad_field_id = 505274 and ad_language = 'en_US';
update ad_field_trl set name = 'Purchase Price System', istranslated = 'Y' where ad_field_id = 505275 and ad_language = 'en_US';
update ad_field_trl set name = 'Freight Cost Fixed', istranslated = 'Y' where ad_field_id = 540044 and ad_language = 'en_US';
update ad_field_trl set name = 'Payment Type', istranslated = 'Y' where ad_field_id = 554377 and ad_language = 'en_US';
update ad_field_trl set name = 'Exclude from MRP', istranslated = 'Y' where ad_field_id = 555417 and ad_language = 'en_US';
update ad_field_trl set name = 'IsPrintTaxSales', istranslated = 'Y' where ad_field_id = 556271 and ad_language = 'en_US';
update ad_field_trl set name = 'Show VAT', istranslated = 'Y' where ad_field_id = 1000006 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552074 and ad_language = 'en_US';
update ad_field_trl set name = 'Standard-LU', istranslated = 'Y' where ad_field_id = 555207 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 552277 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 552073 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552066 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 552275 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 552085 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552084 and ad_language = 'en_US';
update ad_field_trl set name = 'Current valid version', istranslated = 'Y' where ad_field_id = 552082 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552075 and ad_language = 'en_US';
update ad_field_trl set name = 'Handling Unit Typ', istranslated = 'Y' where ad_field_id = 553856 and ad_language = 'en_US';
update ad_field_trl set name = 'Line type', istranslated = 'Y' where ad_field_id = 552094 and ad_language = 'en_US';
update ad_field_trl set name = 'Sub Packing Instruction', istranslated = 'Y' where ad_field_id = 552093 and ad_language = 'en_US';
update ad_field_trl set name = 'Boxing Type', istranslated = 'Y' where ad_field_id = 552097 and ad_language = 'en_US';
update ad_field_trl set name = 'Quantity', istranslated = 'Y' where ad_field_id = 552096 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner', istranslated = 'Y' where ad_field_id = 553219 and ad_language = 'en_US';
update ad_field_trl set name = 'AllowDirectlyOnPM', istranslated = 'Y' where ad_field_id = 554365 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552098 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552086 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 553955 and ad_language = 'en_US';
update ad_field_trl set name = 'TU-EAN', istranslated = 'Y' where ad_field_id = 553771 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552110 and ad_language = 'en_US';
update ad_field_trl set name = 'Business Partner', istranslated = 'Y' where ad_field_id = 553012 and ad_language = 'en_US';
update ad_field_trl set name = 'infinite capacity', istranslated = 'Y' where ad_field_id = 70140 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 552276 and ad_language = 'en_US';
update ad_field_trl set name = 'UOM', istranslated = 'Y' where ad_field_id = 552107 and ad_language = 'en_US';
update ad_field_trl set name = 'Menge', istranslated = 'Y' where ad_field_id = 552108 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 552109 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552099 and ad_language = 'en_US';
update ad_field_trl set name = 'allow any product', istranslated = 'Y' where ad_field_id = 553162 and ad_language = 'en_US';
update ad_field_trl set name = 'valid to', istranslated = 'Y' where ad_field_id = 553014 and ad_language = 'en_US';
update ad_field_trl set name = 'valid from', istranslated = 'Y' where ad_field_id = 553013 and ad_language = 'en_US';
update ad_field_trl set name = 'Splitter Strategy', istranslated = 'Y' where ad_field_id = 552507 and ad_language = 'en_US';
update ad_field_trl set name = 'Aggregation Strategy', istranslated = 'Y' where ad_field_id = 552508 and ad_language = 'en_US';
update ad_field_trl set name = 'Propagation Type', istranslated = 'Y' where ad_field_id = 552509 and ad_language = 'en_US';
update ad_field_trl set name = 'Attribute', istranslated = 'Y' where ad_field_id = 552155 and ad_language = 'en_US';
update ad_field_trl set name = 'mandatory', istranslated = 'Y' where ad_field_id = 552154 and ad_language = 'en_US';
update ad_field_trl set name = 'Instance Attribute', istranslated = 'Y' where ad_field_id = 552152 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552145 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552158 and ad_language = 'en_US';
update ad_field_trl set name = 'Use in ASI', istranslated = 'Y' where ad_field_id = 554871 and ad_language = 'en_US';
update ad_field_trl set name = 'Displayed', istranslated = 'Y' where ad_field_id = 556608 and ad_language = 'en_US';
update ad_field_trl set name = 'HU Transfer Attribute Strategy', istranslated = 'Y' where ad_field_id = 554355 and ad_language = 'en_US';
update ad_field_trl set name = 'Sequence', istranslated = 'Y' where ad_field_id = 554090 and ad_language = 'en_US';
update ad_field_trl set name = 'readonly', istranslated = 'Y' where ad_field_id = 554089 and ad_language = 'en_US';
update ad_field_trl set name = 'UOM', istranslated = 'Y' where ad_field_id = 554051 and ad_language = 'en_US';
update ad_field_trl set name = 'Filling degree', istranslated = 'Y' where ad_field_id = 552430 and ad_language = 'en_US';
update ad_field_trl set name = 'overweight tolerance', istranslated = 'Y' where ad_field_id = 552439 and ad_language = 'en_US';
update ad_field_trl set name = 'overvolume tolerance', istranslated = 'Y' where ad_field_id = 552440 and ad_language = 'en_US';
update ad_field_trl set name = 'closed', istranslated = 'Y' where ad_field_id = 552431 and ad_language = 'en_US';
update ad_field_trl set name = 'unit measurements', istranslated = 'Y' where ad_field_id = 552426 and ad_language = 'en_US';
update ad_field_trl set name = 'width', istranslated = 'Y' where ad_field_id = 552425 and ad_language = 'en_US';
update ad_field_trl set name = 'length', istranslated = 'Y' where ad_field_id = 552433 and ad_language = 'en_US';
update ad_field_trl set name = 'height', istranslated = 'Y' where ad_field_id = 552432 and ad_language = 'en_US';
update ad_field_trl set name = 'Client', istranslated = 'Y' where ad_field_id = 552434 and ad_language = 'en_US';
update ad_field_trl set name = 'Product', istranslated = 'Y' where ad_field_id = 552436 and ad_language = 'en_US';
update ad_field_trl set name = 'Description', istranslated = 'Y' where ad_field_id = 552424 and ad_language = 'en_US';
update ad_field_trl set name = 'Name', istranslated = 'Y' where ad_field_id = 552435 and ad_language = 'en_US';
update ad_field_trl set name = 'Boxing Type', istranslated = 'Y' where ad_field_id = 552420 and ad_language = 'en_US';
update ad_field_trl set name = 'Active', istranslated = 'Y' where ad_field_id = 552421 and ad_language = 'en_US';
update ad_field_trl set name = 'Organisation', istranslated = 'Y' where ad_field_id = 552437 and ad_language = 'en_US';
update ad_field_trl set name = 'UOM for weight', istranslated = 'Y' where ad_field_id = 552427 and ad_language = 'en_US';
update ad_field_trl set name = 'permitted boxing weight ', istranslated = 'Y' where ad_field_id = 552441 and ad_language = 'en_US';
update ad_field_trl set name = 'permitted boxing volume', istranslated = 'Y' where ad_field_id = 552442 and ad_language = 'en_US';
update ad_field_trl set name = 'stackability Factor', istranslated = 'Y' where ad_field_id = 552438 and ad_language = 'en_US';
