UPDATE c_uom_trl SET description='(plus petite unité d''allocation des ressources)', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_FR';
UPDATE c_uom_trl SET description='(La plus petite unité pour l''attribution des ressources)', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='1000 LFM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540028 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='1000 LFM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540028 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='1000 Stk', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000003 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='1000 pcs', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000003 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Fédéral', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540031 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Fédération', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540031 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='Fédéral', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540031 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='Fédération', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540031 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Centimètre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540047 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Centimètre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540047 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='CM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540047 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='CM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540047 AND ad_language='fr_CH';
UPDATE c_uom_trl SET description='La précision de la localisation détermine le nombre de décimales sur le relevé de commission.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_FR';
UPDATE c_uom_trl SET description='La précision de la localisation détermine le nombre de décimales sur le relevé de commission.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Récipient', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Récipient', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='grammes', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540019 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='grammes', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540019 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='GRM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540019 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='GRM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540019 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='H', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=101 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='H', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=101 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Carton', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000004 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Carton', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000004 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='kg', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540017 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='kg', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540017 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Kilogramme', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540017 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='kilogramme', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540017 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Collo', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Collo', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='Collo', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='Collo', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='KRT', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000004 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='KRT', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000004 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Litre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540015 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Litre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540015 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='LTR', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540015 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='LTR', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540015 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='m', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='m', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_CH';
UPDATE c_uom_trl SET description='Unité de mesure pour le conteneurs. Peut etre utilisée comme unité de prix pour les conteneurs, ainsi que pour les commandes et les factures, à condition que la capacité du conteneur correspondant soit enregistrée dans metasfresh.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_FR';
UPDATE c_uom_trl SET description='Unité de mesure pour les conteneurs. Peut être utilisé comme unité de prix pour les conteneurs et pour les commandes et les factures si la capacité de conteneur respectif est stockée dans Metasfresh.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_CH';
UPDATE c_uom_trl SET description='Unité de mesure pour le conteneurs. Peut etre utilisée comme unité de prix pour les conteneurs, ainsi que pour les commandes et les factures, à condition que la capacité du conteneur correspondant soit enregistrée dans metasfresh.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_FR';
UPDATE c_uom_trl SET description='Unité de mesure pour le conteneurs. Peut etre utilisée comme unité de prix pour les conteneurs, ainsi que pour les commandes et les factures, à condition que la capacité du conteneur correspondant soit enregistrée dans metasfresh.', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540048 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='millimétre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000001 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='millimètre', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000001 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='minute', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='minute', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=103 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='mm', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000001 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='mm', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000001 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='Pkt', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='Pkt', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Point de commission', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Point de commission', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540049 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='qm2', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000002 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='qm2', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000002 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Métres carrés', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000002 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Métres carrés', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000002 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Rouleau', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540009 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Rouleau', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540009 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='rlx', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540009 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='rlx', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540009 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='Pce', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=100 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='Pce', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=100 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Pièce', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=100 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Pièce', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=100 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Heure', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=101 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Heure', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=101 AND ad_language='fr_CH';
UPDATE c_uom_trl SET name='Jour', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=102 AND ad_language='fr_FR';
UPDATE c_uom_trl SET name='Jour', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=102 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='TLFM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540028 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='TLFM', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540028 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='TSTK', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000003 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='TSTK', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=1000003 AND ad_language='fr_CH';
UPDATE c_uom_trl SET uomsymbol='TU', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_FR';
UPDATE c_uom_trl SET uomsymbol='TU', updated=now(), updatedby=100, istranslated='Y' WHERE c_uom_id=540030 AND ad_language='fr_CH';
