#!/bin/bash

# This script executes a modified java service wrapper to run the jboss-server

AS_SCRIPT_FILE="adempiere_wrapper"              # Name of main script file
AS_SCRIPT_DIR=$(dirname $0)                     # Get current dir
CURRENT_USER=$(whoami)
SCRIPT_USER=adempiere

#Sets AS_SCRIPT as relative folder+file path, depending wether this script is started in /etc/init.d or it's basedir ".../Adempiere/utils"
resolve_bin(){
 if [[ "$AS_SCRIPT_DIR" =~ "utils" ]]; then                                                                                                             #Started in /etc/init.d
   AS_SCRIPT_DIR=${AS_SCRIPT_DIR//utils/"jboss/bin/"}
 else                                                                           #Started in basedir
   AS_SCRIPT_DIR=$(readlink -f "/etc/init.d/adempiere_server")
   AS_SCRIPT_DIR=${AS_SCRIPT_DIR//"utils/adempiere_server"/"jboss/bin/"}
 fi

 AS_SCRIPT="$AS_SCRIPT_DIR/$AS_SCRIPT_FILE"                                    # Script location "../jboss/bin/jboss"
}

# Only root and adempiere can execute this script properly
 sanity_check(){
 if [[ $EUID -ne 0 && $CURRENT_USER -ne "$SCRIPT_USER" ]]; then
   echo 'This script need to be run as "root" or '"$SCRIPT_USER"' !' 2>&1
   echo $CURRENT_USER
   exit 1
 fi

 if [[ ! -f $AS_SCRIPT ]]; then
  echo "Java Service Wrapper is not installed properly!"
  exit 1
 fi
}

# User "adempiere" is able to run the script as is. User "root" runs the script as user "adempiere"
run_script(){
  if [[ $CURRENT_USER == "$SCRIPT_USER" ]]; then
   $AS_SCRIPT $1
   if [[ $? -gt 0 ]]; then
    exit 1
   fi
  fi

  if [[ $EUID -eq 0 ]]; then
   su -l $SCRIPT_USER -c "$AS_SCRIPT $1"
   if [[ $? -gt 0 ]]; then
     exit 1
   fi
  fi
}

main(){
resolve_bin
sanity_check
run_script $1
}

main $1
exit 0

