
-- 2017-11-15T11:52:41.725
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
/* DDL */ CREATE TABLE public.ESR_PostFinanceUserNumber (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BP_BankAccount_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, ESR_PostFinanceUserNumber_ID NUMERIC(10) NOT NULL, ESR_RenderedAccountNo VARCHAR(25) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT CBPBankAccount_ESRPostFinanceU FOREIGN KEY (C_BP_BankAccount_ID) REFERENCES public.C_BP_BankAccount DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ESR_PostFinanceUserNumber_Key PRIMARY KEY (ESR_PostFinanceUserNumber_ID))
;

