page=Seite
of=von
all=Alle

parm1=Geschäftspartner:
parm2=Geschäftspartnergruppe:
parm3=Artikel:
timeframe=Zeitraum:
headline=Einkauf nach Produkt und Lieferant

sum=Summe
totalsum=Gesamtsumme:
subtotal=Zwischensumme:
product=ArtNr
ProductName=Bezeichnung
PackingInstruction=Packvorschrift
Vendor=Lieferant
QtyTU=Menge
Weight=Gewicht
NetPurchaseValue=WWert
Discount=Rabatte
PurchaseValue=Einkaufswert
