
INSERT INTO public.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, widgetsize, commitwarning, webui_namebrowse, webui_namenewbreadcrumb, webui_namenew) VALUES (583581, 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:31:00.304000 +02:00', 100, 'TaxAmt_Sum_PrevYear', 'U', 'Saldo Vorjahr', 'Saldo Vorjahr', null, 'It''s used like a balance for taxes', null, null, null, null, null, null, null, null, null);
INSERT INTO public.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, widgetsize, commitwarning, webui_namebrowse, webui_namenewbreadcrumb, webui_namenew) VALUES (583580, 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:29:41.013000 +02:00', 100, 'TaxAmt_Sum', 'U', 'Aktueller Saldo', 'Aktueller Saldo', null, 'It''s used for describing tax amount like a balance', null, null, null, null, null, null, null, null, null);
INSERT INTO public.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, widgetsize, commitwarning, webui_namebrowse, webui_namenewbreadcrumb, webui_namenew) VALUES (583579, 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:27:05.098000 +02:00', 100, 'NeAmt', 'U', 'Nettobetrag', 'Nettobetrag', null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO public.ad_element (ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help, widgetsize, commitwarning, webui_namebrowse, webui_namenewbreadcrumb, webui_namenew) VALUES (583578, 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:23:41.735000 +02:00', 100, 'NetAmt_Sum', 'U', 'Summe ohne MwSt.', 'Summe ohne MwSt.', null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583578, 'de_CH', 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:26:33.094000 +02:00', 100, 'Summe ohne MwSt.', 'Summe ohne MwSt.', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583578, 'de_DE', 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:23:41.735000 +02:00', 100, 'Summe ohne MwSt.', 'Summe ohne MwSt.', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583578, 'en_US', 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:23:59.792000 +02:00', 100, 'Total Net Amount', 'Total Net Amount', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583578, 'fr_CH', 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:23:31.273000 +02:00', 100, 'Nettobetrag', 'Nettobetrag', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583578, 'it_CH', 0, 0, 'Y', '2025-04-11 16:23:31.273000 +02:00', 100, '2025-04-11 16:23:31.273000 +02:00', 100, 'Nettobetrag', 'Nettobetrag', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583579, 'de_CH', 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:27:01.595000 +02:00', 100, 'Nettobetrag', 'Nettobetrag', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583579, 'de_DE', 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:27:05.098000 +02:00', 100, 'Nettobetrag', 'Nettobetrag', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583579, 'en_US', 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:27:15.933000 +02:00', 100, 'Net Amount', 'Net Amount', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583579, 'fr_CH', 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:26:49.749000 +02:00', 100, 'NetAmt', 'Nettobetrag', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583579, 'it_CH', 0, 0, 'Y', '2025-04-11 16:26:49.749000 +02:00', 100, '2025-04-11 16:26:49.749000 +02:00', 100, 'NetAmt', 'Nettobetrag', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583580, 'de_CH', 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:29:45.402000 +02:00', 100, 'Aktueller Saldo', 'Aktueller Saldo', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583580, 'de_DE', 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:29:41.013000 +02:00', 100, 'Aktueller Saldo', 'Aktueller Saldo', null, 'It''s used for describing tax amount like a balance', null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583580, 'en_US', 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:30:07.059000 +02:00', 100, 'Tax Amount Sum', 'Tax Amount Sum', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583580, 'fr_CH', 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:29:01.817000 +02:00', 100, 'taxamt_sum', 'Aktueller Saldo', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583580, 'it_CH', 0, 0, 'Y', '2025-04-11 16:29:01.817000 +02:00', 100, '2025-04-11 16:29:01.817000 +02:00', 100, 'taxamt_sum', 'Aktueller Saldo', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583581, 'de_CH', 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:30:57.644000 +02:00', 100, 'Saldo Vorjahr', 'Saldo Vorjahr', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583581, 'de_DE', 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:31:00.304000 +02:00', 100, 'Saldo Vorjahr', 'Saldo Vorjahr', null, 'It''s used like a balance for taxes', null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583581, 'en_US', 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:31:18.721000 +02:00', 100, 'Tax Amt Sum Prev. Year', 'Tax Amt Sum Prev. Year', null, null, null, null, null, null, 'Y', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583581, 'fr_CH', 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:30:42.791000 +02:00', 100, 'Saldo Vorjahr', 'Saldo Vorjahr', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);
INSERT INTO public.ad_element_trl (ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated, commitwarning, webui_namebrowse, webui_namenew, webui_namenewbreadcrumb, isusecustomization, name_customized, description_customized, help_customized) VALUES (583581, 'it_CH', 0, 0, 'Y', '2025-04-11 16:30:42.791000 +02:00', 100, '2025-04-11 16:30:42.791000 +02:00', 100, 'Saldo Vorjahr', 'Saldo Vorjahr', null, null, null, null, null, null, 'N', null, null, null, null, 'N', null, null, null);

UPDATE public.ad_element_trl SET  name = 'Belegwährung', printname = 'Belegwährung', istranslated = 'Y' WHERE ad_element_id = 578756 AND ad_language = 'de_CH';
UPDATE public.ad_element_trl SET name = 'Belegwährung', printname = 'Belegwährung',  istranslated = 'Y' WHERE ad_element_id = 578756 AND ad_language = 'de_DE';

UPDATE ad_process SET sqlstatement = e'SELECT *
FROM de_metas_acct.report_taxaccounts(@AD_Org_ID@, @Account_ID/NULL@, @C_VAT_Code_ID/NULL@, \'@DateFrom@\'::date, \'@DateTo@\'::date,\'@showdetails/N@\')
;' WHERE ad_process_id = 585325;