CREATE TABLE migration_data.default_account_mapping
(
    accountvalue                  varchar(10),
    accountname                   varchar(100),
    c_validcombination_columnname varchar(100),
    tablename                     varchar(100),
    ad_window_id                  numeric,
    windowname                    varchar(60),
    description                   varchar(2000),
    elementvaluedescription       varchar(2000)
)
;

ALTER TABLE migration_data.default_account_mapping
    OWNER TO metasfresh
;








INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90051', 'SUSPENSEBALANCING_ACCT', 'SuspenseBalancing_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Suspense Balancing Account', 'Default Suspense Balancing Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90026', 'C_PREPAYMENT_ACCT', 'C_Prepayment_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Customer Prepayment Account', 'Default Customer Prepayment Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90008', 'V_PREPAYMENT_ACCT', 'V_Prepayment_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Vendor Prepayment Account', 'Default Vendor Prepayment Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90004', 'W_INVACTUALADJUST_ACCT', 'W_InvActualAdjust_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Warehouse Inventory Actual Adjustment Account', 'Default Warehouse Inventory Actual Adjustment Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90013', 'SUSPENSEERROR_ACCT', 'SuspenseError_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Suspense Error Account', 'Default Suspense Error Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90002', 'PJ_WIP_ACCT', 'PJ_WIP_Acct', 'C_Project_Acct', 286, 'Projekt (Verkauf)', 'Default Project Work in Progress Account', 'Default Project Work in Progress Account (1. Fenster "Projekt (Verkauf) (286)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90009', 'C_RECEIVABLE_ACCT', 'C_Receivable_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Customer Receivables Account', 'Default Customer Receivables Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90010', 'C_RECEIVABLE_SERVICES_ACCT', 'C_Receivable_Services_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Customer Receivables (Services) Account', 'Default Customer Receivables (Services) Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90011', 'PJ_ASSET_ACCT', 'PJ_Asset_Acct', 'C_Project_Acct', 286, 'Projekt (Verkauf)', 'Default Project Asset Account', 'Default Project Asset Account (1. Fenster "Projekt (Verkauf) (286)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90027', 'V_LIABILITY_ACCT', 'V_Liability_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Vendor Liability Account', 'Default Vendor Liability Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90028', 'V_LIABILITY_SERVICES_ACCT', 'V_Liability_Services_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Vendor Liability (Services) Account', 'Default Vendor Liability (Services) Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90031', 'E_PREPAYMENT_ACCT', 'E_Prepayment_Acct', 'C_BP_Employee_Acct', 53033, 'Lohnbuchhaltung Mitarbeiter', 'Default Employee Prepayment Account', 'Default Employee Prepayment Account (1. Fenster "Lohnbuchhaltung Mitarbeiter (53033)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90035', 'CH_REVENUE_ACCT', 'Ch_Revenue_Acct', 'C_Charge_Acct', 161, 'Kosten', 'Default Charge Revenue Account', 'Default Charge Revenue Account (1. Fenster "Kosten (161)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90053', 'NOTINVOICEDRECEIPTS_ACCT', 'NotInvoicedReceipts_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Not Invoiced Receipts Account', 'Default Not Invoiced Receipts Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90052', 'CB_DIFFERENCES_ACCT', 'CB_Differences_Acct', 'C_CashBook_Acct', 197, 'Kassenbuch', 'Default Cashbook Difference Account', 'Default Cashbook Difference Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90010', 'C_RECEIVABLE_SERVICES_ACCT', 'C_Receivable_Services_Acct', 'C_BP_Customer_Acct', 540390, 'Debitoren Konten', 'Default Customer Receivables (Services) Account', 'Default Customer Receivables (Services) Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90027', 'V_LIABILITY_ACCT', 'V_Liability_Acct', 'C_BP_Vendor_Acct', 540391, 'Kreditoren Konten', 'Default Vendor Liability Account', 'Default Vendor Liability Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90034', 'UNEARNEDREVENUE_ACCT', 'UnEarnedRevenue_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Unearned Revenue Account', 'Default Unearned Revenue Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90002', 'PJ_WIP_ACCT', 'PJ_WIP_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Project Work in Progress Account', 'Default Project Work in Progress Account (1. Fenster "Projekt (Verkauf) (286)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90008', 'V_PREPAYMENT_ACCT', 'V_Prepayment_Acct', 'C_BP_Vendor_Acct', 540391, 'Kreditoren Konten', 'Default Vendor Prepayment Account', 'Default Vendor Prepayment Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90009', 'C_RECEIVABLE_ACCT', 'C_Receivable_Acct', 'C_BP_Customer_Acct', 540390, 'Debitoren Konten', 'Default Customer Receivables Account', 'Default Customer Receivables Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90004', 'W_INVACTUALADJUST_ACCT', 'W_InvActualAdjust_Acct', 'M_Warehouse_Acct', 139, 'Lager und Lagerort', 'Default Warehouse Inventory Actual Adjustment Account', 'Default Warehouse Inventory Actual Adjustment Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90007', 'P_INVENTORYCLEARING_ACCT', 'P_InventoryClearing_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Inventory Clearing Account', 'Default Product Inventory Clearing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Kostenart (343)", 4. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90003', 'W_INVENTORY_ACCT', 'W_Inventory_Acct', 'M_Warehouse_Acct', 139, 'Lager und Lagerort', 'Default Warehouse Inventory Account', 'Default Warehouse Inventory Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90063', 'B_EXPENSE_ACCT', 'B_Expense_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Expense Account', 'Default Bank Expense Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90003', 'W_INVENTORY_ACCT', 'W_Inventory_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Warehouse Inventory Account', 'Default Warehouse Inventory Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90046', 'P_PURCHASEPRICEVARIANCE_ACCT', 'P_PurchasePriceVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Purchase Price Variance Account', 'Default Purchase Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90056', 'P_COGS_ACCT', 'P_COGS_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product COGS Account', 'Default Product COGS Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90072', 'P_COSTOFPRODUCTION_ACCT', 'P_CostOfProduction_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Cost of Production Account', 'Default Cost of Production Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90073', 'P_FLOORSTOCK_ACCT', 'P_FloorStock_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Floor Stock Account', 'Default Floor Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90074', 'P_LABOR_ACCT', 'P_Labor_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Labor Account', 'Default Labor Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90075', 'P_METHODCHANGEVARIANCE_ACCT', 'P_MethodChangeVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Method Change Variance Account', 'Default Method Change Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90076', 'P_MIXVARIANCE_ACCT', 'P_MixVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Mix Variance Account', 'Default Mix Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90077', 'P_OUTSIDEPROCESSING_ACCT', 'P_OutsideProcessing_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Outside Processing Account', 'Default Outside Processing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90078', 'P_OVERHEAD_ACCT', 'P_Overhead_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Overhead Account', 'Default Overhead Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90079', 'P_RATEVARIANCE_ACCT', 'P_RateVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Rate Variance Account', 'Default Rate Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90080', 'P_SCRAP_ACCT', 'P_Scrap_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Scrap Account', 'Default Scrap Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90060', 'P_COSTADJUSTMENT_ACCT', 'P_CostAdjustment_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Cost Adjustment Account', 'Default Product Cost Adjustment Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90060', 'P_COSTADJUSTMENT_ACCT', 'P_CostAdjustment_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Cost Adjustment Account', 'Default Product Cost Adjustment Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90005', 'W_DIFFERENCES_ACCT', 'W_Differences_Acct', 'M_Warehouse_Acct', 139, 'Lager und Lagerort', 'Default Warehouse Differences Account', 'Default Warehouse Differences Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90000', 'P_ASSET_ACCT', 'P_Asset_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Asset Account', 'Default Product Asset Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90000', 'P_ASSET_ACCT', 'P_Asset_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Asset Account', 'Default Product Asset Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90001', 'NOTINVOICEDRECEIVABLES_ACCT', 'NotInvoicedReceivables_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Not Invoiced Receivables Account', 'Default Not Invoiced Receivables Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90001', 'NOTINVOICEDRECEIVABLES_ACCT', 'NotInvoicedReceivables_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Not Invoiced Receivables Account', 'Default Not Invoiced Receivables Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90018', 'B_INTRANSIT_ACCT', 'B_InTransit_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank In Transit Account', 'Default Bank In Transit Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90044', 'P_INVOICEPRICEVARIANCE_ACCT', 'P_InvoicePriceVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Invoice Price Variance Account', 'Default Product Invoice Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90019', 'B_UNIDENTIFIED_ACCT', 'B_Unidentified_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Unidentified Account', 'Default Bank Unidentified Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90020', 'B_UNALLOCATEDCASH_ACCT', 'B_UnallocatedCash_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Unallocated Cash Account', 'Default Bank Unallocated Cash Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90021', 'B_PAYMENTSELECT_ACCT', 'B_PaymentSelect_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Payment Selection Account', 'Default Bank Payment Selection Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90022', 'CB_CASHTRANSFER_ACCT', 'CB_CashTransfer_Acct', 'C_CashBook_Acct', 197, 'Kassenbuch', 'Default Cashbook Cash Transfer Account', 'Default Cashbook Cash Transfer Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90047', 'B_SETTLEMENTLOSS_ACCT', 'B_SettlementLoss_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Settlement Loss Account', 'Default Bank Settlement Loss Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90016', 'CB_ASSET_ACCT', 'CB_Asset_Acct', 'C_CashBook_Acct', 197, 'Kassenbuch', 'Default Cashbook Asset Account', 'Default Cashbook Asset Account (1. Fenster "Kassenbuch (197)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90066', 'B_SETTLEMENTGAIN_ACCT', 'B_SettlementGain_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Settlement Gain Account', 'Default Bank Settlement Gain Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90056', 'P_COGS_ACCT', 'P_COGS_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product COGS Account', 'Default Product COGS Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90066', 'B_SETTLEMENTGAIN_ACCT', 'B_SettlementGain_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Settlement Gain Account', 'Default Bank Settlement Gain Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90017', 'B_ASSET_ACCT', 'B_Asset_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Asset Account', 'Default Bank Asset Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90037', 'NOTINVOICEDREVENUE_ACCT', 'NotInvoicedRevenue_Acct', 'C_BP_Group_Acct', 192, 'Geschäftspartnergruppe', 'Default Not Invoiced Revenue Account', 'Default Not Invoiced Revenue Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90056', 'P_COGS_ACCT', 'P_COGS_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product COGS Account', 'Default Product COGS Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90062', 'CH_EXPENSE_ACCT', 'Ch_Expense_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Charge Expense Account', 'Default Charge Expense Account (1. Fenster "Kosten (161)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90057', 'CB_EXPENSE_ACCT', 'CB_Expense_Acct', 'C_CashBook_Acct', 197, 'Kassenbuch', 'Default Cashbook Expense Account', 'Default Cashbook Expense Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90071', 'P_Burden_Acct', 'P_Burden_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Burden Account', 'Default Burden Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90062', 'CH_EXPENSE_ACCT', 'Ch_Expense_Acct', 'C_Charge_Acct', 161, 'Kosten', 'Default Charge Expense Account', 'Default Charge Expense Account (1. Fenster "Kosten (161)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90073', 'P_FLOORSTOCK_ACCT', 'P_FloorStock_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Floor Stock Account', 'Default Floor Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90074', 'P_LABOR_ACCT', 'P_Labor_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Labor Account', 'Default Labor Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90075', 'P_METHODCHANGEVARIANCE_ACCT', 'P_MethodChangeVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Method Change Variance Account', 'Default Method Change Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90065', 'B_INTERESTREV_ACCT', 'B_InterestRev_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Interest Revenue Account', 'Default Bank Interest Revenue Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90067', 'B_INTERESTEXP_ACCT', 'B_InterestExp_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Interest Expense Account', 'Default Bank Interest Expense Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90059', 'P_TRADEDISCOUNTREC_ACCT', 'P_TradeDiscountRec_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Trade Discount Received Account', 'Default Trade Discount Received Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90069', 'RETAINEDEARNING_ACCT', 'RetainedEarning_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Retained Earnings Account', 'Default Retained Earnings Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90072', 'P_COSTOFPRODUCTION_ACCT', 'P_CostOfProduction_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Cost of Production Account', 'Default Cost of Production Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90045', 'REALIZEDLOSS_ACCT', 'RealizedLoss_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Realized Loss Account', 'Default Realized Loss Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90007', 'P_INVENTORYCLEARING_ACCT', 'P_CostClearing_Acct', 'M_CostElement_Acct', 343, 'Kostenart', 'Default Product Cost Clearing Account', 'Default Product Cost Clearing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Kostenart (343)", 4. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_ExternallyOwnedStock_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Externally Owned Stock Account', 'Default Product Externally Owned Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_ExternallyOwnedStock_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Externally Owned Stock Account', 'Default Product Externally Owned Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90007', 'P_INVENTORYCLEARING_ACCT', 'P_CostClearing_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Cost Clearing Account', 'Default Product Cost Clearing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Kostenart (343)", 4. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_ExternallyOwnedStock_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Externally Owned Stock Account', 'Default Product Externally Owned Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90041', 'PPVOFFSET_ACCT', 'PPVOffset_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Purchase Price Variance Offset Account', 'Default Purchase Price Variance Offset Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90006', 'W_REVALUATION_ACCT', 'W_Revaluation_Acct', 'M_Warehouse_Acct', 139, 'Lager und Lagerort', 'Default Warehouse Revaluation Account', 'Default Warehouse Revaluation Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90043', 'REALIZEDGAIN_ACCT', 'RealizedGain_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Realized Gain Account', 'Default Realized Gain Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90036', 'CB_RECEIPT_ACCT', 'CB_Receipt_Acct', 'C_CashBook_Acct', 197, 'Kassenbuch', 'Default Cashbook Receipt Account', 'Default Cashbook Receipt Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90060', 'P_COSTADJUSTMENT_ACCT', 'P_CostAdjustment_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Cost Adjustment Account', 'Default Product Cost Adjustment Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90075', 'P_METHODCHANGEVARIANCE_ACCT', 'P_MethodChangeVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Method Change Variance Account', 'Default Method Change Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90046', 'P_PURCHASEPRICEVARIANCE_ACCT', 'P_PurchasePriceVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Purchase Price Variance Account', 'Default Purchase Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90040', 'B_REVALUATIONLOSS_ACCT', 'B_RevaluationLoss_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Revaluation Loss Account', 'Default Bank Revaluation Loss Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90071', 'P_Burden_Acct', 'P_Burden_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Burden Account', 'Default Burden Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90057', 'CB_EXPENSE_ACCT', 'CB_Expense_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Cashbook Expense Account', 'Default Cashbook Expense Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90024', 'COMMITMENTOFFSET_ACCT', 'CommitmentOffset_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Commitment Offset Account', 'Default Commitment Offset Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90028', 'V_LIABILITY_SERVICES_ACCT', 'V_Liability_Services_Acct', 'C_BP_Vendor_Acct', 540391, 'Kreditoren Konten', 'Default Vendor Liability (Services) Account', 'Default Vendor Liability (Services) Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90034', 'UNEARNEDREVENUE_ACCT', 'UnEarnedRevenue_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Unearned Revenue Account', 'Default Unearned Revenue Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90076', 'P_MIXVARIANCE_ACCT', 'P_MixVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Mix Variance Account', 'Default Mix Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90005', 'W_DIFFERENCES_ACCT', 'W_Differences_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Warehouse Differences Account', 'Default Warehouse Differences Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90021', 'B_PAYMENTSELECT_ACCT', 'B_PaymentSelect_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Payment Selection Account', 'Default Bank Payment Selection Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90022', 'CB_CASHTRANSFER_ACCT', 'CB_CashTransfer_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Cashbook Cash Transfer Account', 'Default Cashbook Cash Transfer Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90026', 'C_PREPAYMENT_ACCT', 'C_Prepayment_Acct', 'C_BP_Customer_Acct', 540390, 'Debitoren Konten', 'Default Customer Prepayment Account', 'Default Customer Prepayment Account (1. Fenster "Debitoren Konten (540390)", 2. Fenster "Geschäftspartnergruppe (192)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90077', 'P_OUTSIDEPROCESSING_ACCT', 'P_OutsideProcessing_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Outside Processing Account', 'Default Outside Processing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90078', 'P_OVERHEAD_ACCT', 'P_Overhead_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Overhead Account', 'Default Overhead Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90079', 'P_RATEVARIANCE_ACCT', 'P_RateVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Rate Variance Account', 'Default Rate Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90079', 'P_RATEVARIANCE_ACCT', 'P_RateVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Rate Variance Account', 'Default Rate Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90073', 'P_FLOORSTOCK_ACCT', 'P_FloorStock_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Floor Stock Account', 'Default Floor Stock Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90076', 'P_MIXVARIANCE_ACCT', 'P_MixVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Mix Variance Account', 'Default Mix Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90078', 'P_OVERHEAD_ACCT', 'P_Overhead_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Overhead Account', 'Default Overhead Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90000', 'P_ASSET_ACCT', 'P_Asset_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Asset Account', 'Default Product Asset Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90007', 'P_INVENTORYCLEARING_ACCT', 'P_InventoryClearing_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Inventory Clearing Account', 'Default Product Inventory Clearing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Kostenart (343)", 4. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90033', 'P_REVENUE_ACCT', 'P_Revenue_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Revenue Account', 'Default Product Revenue Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90080', 'P_SCRAP_ACCT', 'P_Scrap_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Scrap Account', 'Default Scrap Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90080', 'P_SCRAP_ACCT', 'P_Scrap_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Scrap Account', 'Default Scrap Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90081', 'P_USAGEVARIANCE_ACCT', 'P_UsageVariance_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Usage Variance Account', 'Default Usage Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90081', 'P_USAGEVARIANCE_ACCT', 'P_UsageVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Usage Variance Account', 'Default Usage Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90082', 'P_WIP_ACCT', 'P_WIP_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Work In Process Account', 'Default Work In Process Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90082', 'P_WIP_ACCT', 'P_WIP_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Work In Process Account', 'Default Work In Process Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90036', 'CB_RECEIPT_ACCT', 'CB_Receipt_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Cashbook Receipt Account', 'Default Cashbook Receipt Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90033', 'P_REVENUE_ACCT', 'P_Revenue_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Revenue Account', 'Default Product Revenue Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90039', 'P_TRADEDISCOUNTGRANT_ACCT', 'P_TradeDiscountGrant_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Trade Discount Granted Account', 'Default Trade Discount Granted Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90037', 'NOTINVOICEDREVENUE_ACCT', 'NotInvoicedRevenue_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Not Invoiced Revenue Account', 'Default Not Invoiced Revenue Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_Expense_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Expense Account', 'Default Product Expense Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90044', 'P_INVOICEPRICEVARIANCE_ACCT', 'P_InvoicePriceVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Invoice Price Variance Account', 'Default Product Invoice Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90044', 'P_INVOICEPRICEVARIANCE_ACCT', 'P_InvoicePriceVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Invoice Price Variance Account', 'Default Product Invoice Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90053', 'NOTINVOICEDRECEIPTS_ACCT', 'NotInvoicedReceipts_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Not Invoiced Receipts Account', 'Default Not Invoiced Receipts Account (1. Fenster "Geschäftspartnergruppe (192)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90052', 'CB_DIFFERENCES_ACCT', 'CB_Differences_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Cashbook Difference Account', 'Default Cashbook Difference Account (1. Fenster "Kassenbuch (197)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90046', 'P_PURCHASEPRICEVARIANCE_ACCT', 'P_PurchasePriceVariance_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Purchase Price Variance Account', 'Default Purchase Price Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90059', 'P_TRADEDISCOUNTREC_ACCT', 'P_TradeDiscountRec_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Trade Discount Received Account', 'Default Trade Discount Received Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90074', 'P_LABOR_ACCT', 'P_Labor_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Labor Account', 'Default Labor Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90006', 'W_REVALUATION_ACCT', 'W_Revaluation_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Warehouse Revaluation Account', 'Default Warehouse Revaluation Account (1. Fenster "Lager und Lagerort (139)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90007', 'P_INVENTORYCLEARING_ACCT', 'P_InventoryClearing_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Product Inventory Clearing Account', 'Default Product Inventory Clearing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Kostenart (343)", 4. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90071', 'P_Burden_Acct', 'P_Burden_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Burden Account', 'Default Burden Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90020', 'B_UNALLOCATEDCASH_ACCT', 'B_UnallocatedCash_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Unallocated Cash Account', 'Default Bank Unallocated Cash Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90025', 'WITHHOLDING_ACCT', 'Withholding_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Withholding Account', 'Default Withholding Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90061', 'E_EXPENSE_ACCT', 'E_Expense_Acct', 'C_BP_Employee_Acct', 53033, 'Lohnbuchhaltung Mitarbeiter', 'Default Expense Account', 'Default Expense Account (1. Fenster "Lohnbuchhaltung Mitarbeiter (53033)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_Expense_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Product Expense Account', 'Default Product Expense Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90070', 'COMMITMENTOFFSETSALES_ACCT', 'CommitmentOffsetSales_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Sales Commitment Offset Account', 'Default Sales Commitment Offset Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90055', 'P_EXPENSE_ACCT', 'P_Expense_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Product Expense Account', 'Default Product Expense Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90047', 'B_SETTLEMENTLOSS_ACCT', 'B_SettlementLoss_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Settlement Loss Account', 'Default Bank Settlement Loss Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90050', 'B_REVALUATIONGAIN_ACCT', 'B_RevaluationGain_Acct', 'C_BP_BankAccount_Acct', 540337, 'Bankkonto', 'Default Bank Revaluation Gain Account', 'Default Bank Revaluation Gain Account (1. Fenster "Bankkonto (540337)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90072', 'P_COSTOFPRODUCTION_ACCT', 'P_CostOfProduction_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Cost of Production Account', 'Default Cost of Production Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90084', 'CashRounding_ACCT', 'CashRounding_Acct', 'C_AcctSchema_GL', 125, 'Buchführungs-Schema', 'Default Cash Rounding Account', 'Default Cash Rounding Account (1. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90008', 'V_PREPAYMENT_ACCT', 'V_Prepayment_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Vendor Prepayment Account', 'Default Vendor Prepayment Account (1. Fenster "Kreditoren Konten (540391)", 2. Fenster "Geschäftspartnergruppe (192)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90011', 'PJ_ASSET_ACCT', 'PJ_Asset_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Project Asset Account', 'Default Project Asset Account (1. Fenster "Projekt (Verkauf) (286)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90017', 'B_ASSET_ACCT', 'B_Asset_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Asset Account', 'Default Bank Asset Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90018', 'B_INTRANSIT_ACCT', 'B_InTransit_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank In Transit Account', 'Default Bank In Transit Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90019', 'B_UNIDENTIFIED_ACCT', 'B_Unidentified_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Bank Unidentified Account', 'Default Bank Unidentified Account (1. Fenster "Bankkonto (540337)", 2. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90082', 'P_WIP_ACCT', 'P_WIP_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Work In Process Account', 'Default Work In Process Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90083', 'P_ExternallyOwnedStock_Acct', 'P_ExternallyOwnedStock_Acct', 'M_Product_Acct', 140, 'Produkt', 'Default Externally Owned Stock Account', 'Default Externally Owned Stock Account (1. Fenster "Produkt (140)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90039', 'P_TRADEDISCOUNTGRANT_ACCT', 'P_TradeDiscountGrant_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Trade Discount Granted Account', 'Default Trade Discount Granted Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90039', 'P_TRADEDISCOUNTGRANT_ACCT', 'P_TradeDiscountGrant_Acct', 'C_AcctSchema_Default', 125, 'Buchführungs-Schema', 'Default Trade Discount Granted Account', 'Default Trade Discount Granted Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90059', 'P_TRADEDISCOUNTREC_ACCT', 'P_TradeDiscountRec_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Trade Discount Received Account', 'Default Trade Discount Received Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90077', 'P_OUTSIDEPROCESSING_ACCT', 'P_OutsideProcessing_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Outside Processing Account', 'Default Outside Processing Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
INSERT INTO migration_data.default_account_mapping (accountvalue, accountname, c_validcombination_columnname, tablename, ad_window_id, windowname, description, elementvaluedescription) VALUES ('90081', 'P_USAGEVARIANCE_ACCT', 'P_UsageVariance_Acct', 'M_Product_Category_Acct', 144, 'Produkt Kategorie', 'Default Usage Variance Account', 'Default Usage Variance Account (1. Fenster "Produkt (140)", 2. Fenster "Produkt Kategorie (144)", 3. Fenster "Buchführungs-Schema (125)")');
