//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 12:03:26 PM CET 
//


package at.erpel.schemas._1p0.documents.extensions.edifact;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ListLineItemExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListLineItemExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentLineItemNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Unit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PriceReferenceUnit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}NumberOfPromotion" minOccurs="0"/&gt;
 *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}FTX" minOccurs="0"/&gt;
 *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}FreeText" minOccurs="0"/&gt;
 *         &lt;element name="ChargeBestBeforeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}OrderedQuantity" minOccurs="0"/&gt;
 *         &lt;element name="QuantitySchedules" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Schedule" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Conditions" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}StatusIndicator" minOccurs="0"/&gt;
 *                                       &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}DeliveryRequirementsCoded" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}FreeText" minOccurs="0"/&gt;
 *                             &lt;element name="ScheduledQuantities" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Qualifier" minOccurs="0"/&gt;
 *                                       &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Quantity"/&gt;
 *                                       &lt;element name="Date" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;simpleContent&gt;
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
 *                                               &lt;attribute name="DateFunctionCodeQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                               &lt;attribute name="DateFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                             &lt;/extension&gt;
 *                                           &lt;/simpleContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PositionAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}AdditionalBusinessPartner" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DESADVListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}DESADVListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="INVOICListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}INVOICListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="ManuallyAddedListLineItem" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ORDERSListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}ORDERSListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="RECADVListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}RECADVListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="ORDRSPListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}ORDRSPListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="INVRPTListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}INVRPTListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="SLSRPTListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}SLSRPTListLineExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="PRICATListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}PRICATListLineItemExtensionType" minOccurs="0"/&gt;
 *         &lt;element name="REMADVListLineItemExtension" type="{http://erpel.at/schemas/1p0/documents/extensions/edifact}REMADVListLineItemExtensionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListLineItemExtensionType", propOrder = {
    "parentLineItemNumber",
    "unit",
    "priceReferenceUnit",
    "numberOfPromotion",
    "ftx",
    "freeText",
    "chargeBestBeforeDate",
    "orderedQuantity",
    "quantitySchedules",
    "positionAction",
    "additionalBusinessPartner",
    "desadvListLineItemExtension",
    "invoicListLineItemExtension",
    "manuallyAddedListLineItem",
    "ordersListLineItemExtension",
    "recadvListLineItemExtension",
    "ordrspListLineItemExtension",
    "invrptListLineItemExtension",
    "slsrptListLineItemExtension",
    "pricatListLineItemExtension",
    "remadvListLineItemExtension"
})
public class ListLineItemExtensionType {

    @XmlElement(name = "ParentLineItemNumber")
    protected String parentLineItemNumber;
    @XmlElement(name = "Unit")
    protected String unit;
    @XmlElement(name = "PriceReferenceUnit")
    protected BigDecimal priceReferenceUnit;
    @XmlElement(name = "NumberOfPromotion")
    protected String numberOfPromotion;
    @XmlElement(name = "FTX")
    protected String ftx;
    @XmlElement(name = "FreeText")
    protected FreeTextType freeText;
    @XmlElement(name = "ChargeBestBeforeDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar chargeBestBeforeDate;
    @XmlElement(name = "OrderedQuantity")
    protected UnitType orderedQuantity;
    @XmlElement(name = "QuantitySchedules")
    protected ListLineItemExtensionType.QuantitySchedules quantitySchedules;
    @XmlElement(name = "PositionAction")
    protected String positionAction;
    @XmlElement(name = "AdditionalBusinessPartner")
    protected List<BusinessEntityType> additionalBusinessPartner;
    @XmlElement(name = "DESADVListLineItemExtension")
    protected DESADVListLineItemExtensionType desadvListLineItemExtension;
    @XmlElement(name = "INVOICListLineItemExtension")
    protected INVOICListLineItemExtensionType invoicListLineItemExtension;
    @XmlElement(name = "ManuallyAddedListLineItem")
    protected Boolean manuallyAddedListLineItem;
    @XmlElement(name = "ORDERSListLineItemExtension")
    protected ORDERSListLineItemExtensionType ordersListLineItemExtension;
    @XmlElement(name = "RECADVListLineItemExtension")
    protected RECADVListLineItemExtensionType recadvListLineItemExtension;
    @XmlElement(name = "ORDRSPListLineItemExtension")
    protected ORDRSPListLineItemExtensionType ordrspListLineItemExtension;
    @XmlElement(name = "INVRPTListLineItemExtension")
    protected INVRPTListLineItemExtensionType invrptListLineItemExtension;
    @XmlElement(name = "SLSRPTListLineItemExtension")
    protected SLSRPTListLineExtensionType slsrptListLineItemExtension;
    @XmlElement(name = "PRICATListLineItemExtension")
    protected PRICATListLineItemExtensionType pricatListLineItemExtension;
    @XmlElement(name = "REMADVListLineItemExtension")
    protected REMADVListLineItemExtensionType remadvListLineItemExtension;

    /**
     * Gets the value of the parentLineItemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentLineItemNumber() {
        return parentLineItemNumber;
    }

    /**
     * Sets the value of the parentLineItemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentLineItemNumber(String value) {
        this.parentLineItemNumber = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the priceReferenceUnit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceReferenceUnit() {
        return priceReferenceUnit;
    }

    /**
     * Sets the value of the priceReferenceUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceReferenceUnit(BigDecimal value) {
        this.priceReferenceUnit = value;
    }

    /**
     * Relevant number of promotion.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfPromotion() {
        return numberOfPromotion;
    }

    /**
     * Sets the value of the numberOfPromotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPromotion(String value) {
        this.numberOfPromotion = value;
    }

    /**
     * Free text field.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTX() {
        return ftx;
    }

    /**
     * Sets the value of the ftx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTX(String value) {
        this.ftx = value;
    }

    /**
     * Free text information.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextType }
     *     
     */
    public FreeTextType getFreeText() {
        return freeText;
    }

    /**
     * Sets the value of the freeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextType }
     *     
     */
    public void setFreeText(FreeTextType value) {
        this.freeText = value;
    }

    /**
     * Gets the value of the chargeBestBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getChargeBestBeforeDate() {
        return chargeBestBeforeDate;
    }

    /**
     * Sets the value of the chargeBestBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setChargeBestBeforeDate(XMLGregorianCalendar value) {
        this.chargeBestBeforeDate = value;
    }

    /**
     * Originally ordered quantity in the referenced order/schedule.
     * 
     * @return
     *     possible object is
     *     {@link UnitType }
     *     
     */
    public UnitType getOrderedQuantity() {
        return orderedQuantity;
    }

    /**
     * Sets the value of the orderedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType }
     *     
     */
    public void setOrderedQuantity(UnitType value) {
        this.orderedQuantity = value;
    }

    /**
     * Gets the value of the quantitySchedules property.
     * 
     * @return
     *     possible object is
     *     {@link ListLineItemExtensionType.QuantitySchedules }
     *     
     */
    public ListLineItemExtensionType.QuantitySchedules getQuantitySchedules() {
        return quantitySchedules;
    }

    /**
     * Sets the value of the quantitySchedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListLineItemExtensionType.QuantitySchedules }
     *     
     */
    public void setQuantitySchedules(ListLineItemExtensionType.QuantitySchedules value) {
        this.quantitySchedules = value;
    }

    /**
     * Gets the value of the positionAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionAction() {
        return positionAction;
    }

    /**
     * Sets the value of the positionAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionAction(String value) {
        this.positionAction = value;
    }

    /**
     * Used to provide details about additional business partners, which are not contained in the core schema, such as ultimate consignee, etc.Gets the value of the additionalBusinessPartner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalBusinessPartner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalBusinessPartner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessEntityType }
     * 
     * 
     */
    public List<BusinessEntityType> getAdditionalBusinessPartner() {
        if (additionalBusinessPartner == null) {
            additionalBusinessPartner = new ArrayList<BusinessEntityType>();
        }
        return this.additionalBusinessPartner;
    }

    /**
     * Gets the value of the desadvListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link DESADVListLineItemExtensionType }
     *     
     */
    public DESADVListLineItemExtensionType getDESADVListLineItemExtension() {
        return desadvListLineItemExtension;
    }

    /**
     * Sets the value of the desadvListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link DESADVListLineItemExtensionType }
     *     
     */
    public void setDESADVListLineItemExtension(DESADVListLineItemExtensionType value) {
        this.desadvListLineItemExtension = value;
    }

    /**
     * Gets the value of the invoicListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link INVOICListLineItemExtensionType }
     *     
     */
    public INVOICListLineItemExtensionType getINVOICListLineItemExtension() {
        return invoicListLineItemExtension;
    }

    /**
     * Sets the value of the invoicListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVOICListLineItemExtensionType }
     *     
     */
    public void setINVOICListLineItemExtension(INVOICListLineItemExtensionType value) {
        this.invoicListLineItemExtension = value;
    }

    /**
     * Gets the value of the manuallyAddedListLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isManuallyAddedListLineItem() {
        return manuallyAddedListLineItem;
    }

    /**
     * Sets the value of the manuallyAddedListLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setManuallyAddedListLineItem(Boolean value) {
        this.manuallyAddedListLineItem = value;
    }

    /**
     * Gets the value of the ordersListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERSListLineItemExtensionType }
     *     
     */
    public ORDERSListLineItemExtensionType getORDERSListLineItemExtension() {
        return ordersListLineItemExtension;
    }

    /**
     * Sets the value of the ordersListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERSListLineItemExtensionType }
     *     
     */
    public void setORDERSListLineItemExtension(ORDERSListLineItemExtensionType value) {
        this.ordersListLineItemExtension = value;
    }

    /**
     * Gets the value of the recadvListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link RECADVListLineItemExtensionType }
     *     
     */
    public RECADVListLineItemExtensionType getRECADVListLineItemExtension() {
        return recadvListLineItemExtension;
    }

    /**
     * Sets the value of the recadvListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link RECADVListLineItemExtensionType }
     *     
     */
    public void setRECADVListLineItemExtension(RECADVListLineItemExtensionType value) {
        this.recadvListLineItemExtension = value;
    }

    /**
     * Gets the value of the ordrspListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ORDRSPListLineItemExtensionType }
     *     
     */
    public ORDRSPListLineItemExtensionType getORDRSPListLineItemExtension() {
        return ordrspListLineItemExtension;
    }

    /**
     * Sets the value of the ordrspListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDRSPListLineItemExtensionType }
     *     
     */
    public void setORDRSPListLineItemExtension(ORDRSPListLineItemExtensionType value) {
        this.ordrspListLineItemExtension = value;
    }

    /**
     * Gets the value of the invrptListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link INVRPTListLineItemExtensionType }
     *     
     */
    public INVRPTListLineItemExtensionType getINVRPTListLineItemExtension() {
        return invrptListLineItemExtension;
    }

    /**
     * Sets the value of the invrptListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVRPTListLineItemExtensionType }
     *     
     */
    public void setINVRPTListLineItemExtension(INVRPTListLineItemExtensionType value) {
        this.invrptListLineItemExtension = value;
    }

    /**
     * Gets the value of the slsrptListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link SLSRPTListLineExtensionType }
     *     
     */
    public SLSRPTListLineExtensionType getSLSRPTListLineItemExtension() {
        return slsrptListLineItemExtension;
    }

    /**
     * Sets the value of the slsrptListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLSRPTListLineExtensionType }
     *     
     */
    public void setSLSRPTListLineItemExtension(SLSRPTListLineExtensionType value) {
        this.slsrptListLineItemExtension = value;
    }

    /**
     * Gets the value of the pricatListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link PRICATListLineItemExtensionType }
     *     
     */
    public PRICATListLineItemExtensionType getPRICATListLineItemExtension() {
        return pricatListLineItemExtension;
    }

    /**
     * Sets the value of the pricatListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICATListLineItemExtensionType }
     *     
     */
    public void setPRICATListLineItemExtension(PRICATListLineItemExtensionType value) {
        this.pricatListLineItemExtension = value;
    }

    /**
     * Gets the value of the remadvListLineItemExtension property.
     * 
     * @return
     *     possible object is
     *     {@link REMADVListLineItemExtensionType }
     *     
     */
    public REMADVListLineItemExtensionType getREMADVListLineItemExtension() {
        return remadvListLineItemExtension;
    }

    /**
     * Sets the value of the remadvListLineItemExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMADVListLineItemExtensionType }
     *     
     */
    public void setREMADVListLineItemExtension(REMADVListLineItemExtensionType value) {
        this.remadvListLineItemExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Schedule" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Conditions" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}StatusIndicator" minOccurs="0"/&gt;
     *                             &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}DeliveryRequirementsCoded" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}FreeText" minOccurs="0"/&gt;
     *                   &lt;element name="ScheduledQuantities" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Qualifier" minOccurs="0"/&gt;
     *                             &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Quantity"/&gt;
     *                             &lt;element name="Date" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;simpleContent&gt;
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
     *                                     &lt;attribute name="DateFunctionCodeQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                     &lt;attribute name="DateFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                   &lt;/extension&gt;
     *                                 &lt;/simpleContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schedule"
    })
    public static class QuantitySchedules {

        @XmlElement(name = "Schedule")
        protected List<ListLineItemExtensionType.QuantitySchedules.Schedule> schedule;

        /**
         * Gets the value of the schedule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the schedule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSchedule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListLineItemExtensionType.QuantitySchedules.Schedule }
         * 
         * 
         */
        public List<ListLineItemExtensionType.QuantitySchedules.Schedule> getSchedule() {
            if (schedule == null) {
                schedule = new ArrayList<ListLineItemExtensionType.QuantitySchedules.Schedule>();
            }
            return this.schedule;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Conditions" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}StatusIndicator" minOccurs="0"/&gt;
         *                   &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}DeliveryRequirementsCoded" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}FreeText" minOccurs="0"/&gt;
         *         &lt;element name="ScheduledQuantities" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Qualifier" minOccurs="0"/&gt;
         *                   &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Quantity"/&gt;
         *                   &lt;element name="Date" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;simpleContent&gt;
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
         *                           &lt;attribute name="DateFunctionCodeQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                           &lt;attribute name="DateFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                         &lt;/extension&gt;
         *                       &lt;/simpleContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "conditions",
            "freeText",
            "scheduledQuantities"
        })
        public static class Schedule {

            @XmlElement(name = "Conditions")
            protected ListLineItemExtensionType.QuantitySchedules.Schedule.Conditions conditions;
            @XmlElement(name = "FreeText")
            protected FreeTextType freeText;
            @XmlElement(name = "ScheduledQuantities")
            protected List<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities> scheduledQuantities;

            /**
             * Gets the value of the conditions property.
             * 
             * @return
             *     possible object is
             *     {@link ListLineItemExtensionType.QuantitySchedules.Schedule.Conditions }
             *     
             */
            public ListLineItemExtensionType.QuantitySchedules.Schedule.Conditions getConditions() {
                return conditions;
            }

            /**
             * Sets the value of the conditions property.
             * 
             * @param value
             *     allowed object is
             *     {@link ListLineItemExtensionType.QuantitySchedules.Schedule.Conditions }
             *     
             */
            public void setConditions(ListLineItemExtensionType.QuantitySchedules.Schedule.Conditions value) {
                this.conditions = value;
            }

            /**
             * Freetext belonging to the schedule conditions.
             * 
             * @return
             *     possible object is
             *     {@link FreeTextType }
             *     
             */
            public FreeTextType getFreeText() {
                return freeText;
            }

            /**
             * Sets the value of the freeText property.
             * 
             * @param value
             *     allowed object is
             *     {@link FreeTextType }
             *     
             */
            public void setFreeText(FreeTextType value) {
                this.freeText = value;
            }

            /**
             * Gets the value of the scheduledQuantities property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the scheduledQuantities property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getScheduledQuantities().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities }
             * 
             * 
             */
            public List<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities> getScheduledQuantities() {
                if (scheduledQuantities == null) {
                    scheduledQuantities = new ArrayList<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities>();
                }
                return this.scheduledQuantities;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}StatusIndicator" minOccurs="0"/&gt;
             *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}DeliveryRequirementsCoded" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "statusIndicator",
                "deliveryRequirementsCoded"
            })
            public static class Conditions {

                @XmlElement(name = "StatusIndicator")
                protected String statusIndicator;
                @XmlElement(name = "DeliveryRequirementsCoded")
                protected String deliveryRequirementsCoded;

                /**
                 * Code specifing the commitment to a delivery plan. 1..Firm, 10..Immediate, etc.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatusIndicator() {
                    return statusIndicator;
                }

                /**
                 * Sets the value of the statusIndicator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatusIndicator(String value) {
                    this.statusIndicator = value;
                }

                /**
                 * Code describing the delivery instruction. AA..Ship on authorization, BK..Ship partial - balance back order, etc.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeliveryRequirementsCoded() {
                    return deliveryRequirementsCoded;
                }

                /**
                 * Sets the value of the deliveryRequirementsCoded property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeliveryRequirementsCoded(String value) {
                    this.deliveryRequirementsCoded = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Qualifier" minOccurs="0"/&gt;
             *         &lt;element ref="{http://erpel.at/schemas/1p0/documents/extensions/edifact}Quantity"/&gt;
             *         &lt;element name="Date" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;simpleContent&gt;
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
             *                 &lt;attribute name="DateFunctionCodeQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                 &lt;attribute name="DateFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *               &lt;/extension&gt;
             *             &lt;/simpleContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "qualifier",
                "quantity",
                "date"
            })
            public static class ScheduledQuantities {

                @XmlElement(name = "Qualifier")
                protected String qualifier;
                @XmlElement(name = "Quantity", required = true)
                protected UnitType quantity;
                @XmlElement(name = "Date")
                protected List<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities.Date> date;

                /**
                 * Code describing the kind of quantity. 113..Quantity to be delivered, 21..Ordered quantity
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQualifier() {
                    return qualifier;
                }

                /**
                 * Sets the value of the qualifier property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQualifier(String value) {
                    this.qualifier = value;
                }

                /**
                 * Quantity according to the qualifier.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UnitType }
                 *     
                 */
                public UnitType getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UnitType }
                 *     
                 */
                public void setQuantity(UnitType value) {
                    this.quantity = value;
                }

                /**
                 * Gets the value of the date property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the date property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDate().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities.Date }
                 * 
                 * 
                 */
                public List<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities.Date> getDate() {
                    if (date == null) {
                        date = new ArrayList<ListLineItemExtensionType.QuantitySchedules.Schedule.ScheduledQuantities.Date>();
                    }
                    return this.date;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;simpleContent&gt;
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
                 *       &lt;attribute name="DateFunctionCodeQualifier" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *       &lt;attribute name="DateFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *     &lt;/extension&gt;
                 *   &lt;/simpleContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Date {

                    @XmlValue
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar value;
                    @XmlAttribute(name = "DateFunctionCodeQualifier", namespace = "http://erpel.at/schemas/1p0/documents/extensions/edifact")
                    protected String dateFunctionCodeQualifier;
                    @XmlAttribute(name = "DateFormatCode", namespace = "http://erpel.at/schemas/1p0/documents/extensions/edifact")
                    protected String dateFormatCode;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setValue(XMLGregorianCalendar value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the dateFunctionCodeQualifier property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDateFunctionCodeQualifier() {
                        return dateFunctionCodeQualifier;
                    }

                    /**
                     * Sets the value of the dateFunctionCodeQualifier property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDateFunctionCodeQualifier(String value) {
                        this.dateFunctionCodeQualifier = value;
                    }

                    /**
                     * Gets the value of the dateFormatCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDateFormatCode() {
                        return dateFormatCode;
                    }

                    /**
                     * Sets the value of the dateFormatCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDateFormatCode(String value) {
                        this.dateFormatCode = value;
                    }

                }

            }

        }

    }

}
