//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package at.erpel.schemas._1p0.documents.extensions.edifact;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReductionExtensionType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ReductionExtensionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TypeOfReduction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReductionExtensionType", propOrder = {
    "typeOfReduction"
})
public class ReductionExtensionType {

    /**
     * Type of reduction.
     * 
     */
    @XmlElement(name = "TypeOfReduction", required = true)
    protected String typeOfReduction;

    /**
     * Type of reduction.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfReduction() {
        return typeOfReduction;
    }

    /**
     * Sets the value of the typeOfReduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTypeOfReduction()
     */
    public void setTypeOfReduction(String value) {
        this.typeOfReduction = value;
    }

}
