
POST {{baseURL}}/api/v2/processes/Historical_Sales_Orders_By_Ids_JSON/invoke
Authorization: {{authToken}}
Content-Type: application/json;charset=UTF-8
accept: application/json;charset=UTF-8

{
  "processParameters": [
    {
      "name": "C_Order_ID",
      "value": 1000000
    },
    {
      "name": "ExternalId",
      "value": "externalHeaderId_10052022_1"
    },
    {
      "name": "AD_InputDataSource_ID",
      "value": 540217
    }
  ]
}