
POST http://localhost:8282/api/v2/processes/Historical_Sales_Orders_By_Ids_JSON/invoke
Authorization: 1f73d244775c4bccad53bbc7afc80976
Content-Type: application/json;charset=UTF-8
accept: application/json;charset=UTF-8

{
  "processParameters": [
    {
      "name": "ExternalId",
      "value": "test_1"
    },
    {
      "name": "DataSource",
      "value": "int-Shopware"
    }
  ]
}