POST {{baseURL}}/api/v2/processes/M_InOut_EDI_Export_JSON/invoke
Authorization: {{authToken}}
Content-Type: application/json;charset=UTF-8
accept: application/json;charset=UTF-8

{
  "processParameters": [
    {
      "name": "M_InOut_ID",
      "value": "1000000"
    }
  ]
}