//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.metas.vertical.healthcare_ch.forum_datenaustausch_ch.invoice_450.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for treatmentType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="treatmentType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="diagnosis" type="{http://www.forum-datenaustausch.ch/invoice}diagnosisType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="xtra_hospital" type="{http://www.forum-datenaustausch.ch/invoice}xtraHospitalType" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="date_begin" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       <attribute name="date_end" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       <attribute name="gestation_week13" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       <attribute name="canton" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             <enumeration value="AG"/>
 *             <enumeration value="AI"/>
 *             <enumeration value="AR"/>
 *             <enumeration value="BE"/>
 *             <enumeration value="BL"/>
 *             <enumeration value="BS"/>
 *             <enumeration value="FR"/>
 *             <enumeration value="GE"/>
 *             <enumeration value="GL"/>
 *             <enumeration value="GR"/>
 *             <enumeration value="JU"/>
 *             <enumeration value="LU"/>
 *             <enumeration value="NE"/>
 *             <enumeration value="NW"/>
 *             <enumeration value="OW"/>
 *             <enumeration value="SG"/>
 *             <enumeration value="SH"/>
 *             <enumeration value="SO"/>
 *             <enumeration value="SZ"/>
 *             <enumeration value="TI"/>
 *             <enumeration value="TG"/>
 *             <enumeration value="UR"/>
 *             <enumeration value="VD"/>
 *             <enumeration value="VS"/>
 *             <enumeration value="ZG"/>
 *             <enumeration value="ZH"/>
 *             <enumeration value="LI"/>
 *             <enumeration value="A"/>
 *             <enumeration value="D"/>
 *             <enumeration value="F"/>
 *             <enumeration value="I"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="treatment" default="ambulatory">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             <enumeration value="ambulatory"/>
 *             <enumeration value="stationary"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="reason" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             <enumeration value="disease"/>
 *             <enumeration value="accident"/>
 *             <enumeration value="maternity"/>
 *             <enumeration value="prevention"/>
 *             <enumeration value="birthdefect"/>
 *             <enumeration value="unknown"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="apid" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_35" />
 *       <attribute name="acid" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_35" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "treatmentType", namespace = "http://www.forum-datenaustausch.ch/invoice", propOrder = {
    "diagnosis",
    "xtraHospital"
})
public class TreatmentType {

    @XmlElement(namespace = "http://www.forum-datenaustausch.ch/invoice")
    protected List<DiagnosisType> diagnosis;
    @XmlElement(name = "xtra_hospital", namespace = "http://www.forum-datenaustausch.ch/invoice")
    protected XtraHospitalType xtraHospital;
    @XmlAttribute(name = "date_begin", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateBegin;
    @XmlAttribute(name = "date_end", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateEnd;
    @XmlAttribute(name = "gestation_week13")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gestationWeek13;
    @XmlAttribute(name = "canton", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String canton;
    @XmlAttribute(name = "treatment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String treatment;
    @XmlAttribute(name = "reason", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reason;
    @XmlAttribute(name = "apid")
    protected String apid;
    @XmlAttribute(name = "acid")
    protected String acid;

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosisType }
     * </p>
     * 
     * 
     * @return
     *     The value of the diagnosis property.
     */
    public List<DiagnosisType> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the xtraHospital property.
     * 
     * @return
     *     possible object is
     *     {@link XtraHospitalType }
     *     
     */
    public XtraHospitalType getXtraHospital() {
        return xtraHospital;
    }

    /**
     * Sets the value of the xtraHospital property.
     * 
     * @param value
     *     allowed object is
     *     {@link XtraHospitalType }
     *     
     */
    public void setXtraHospital(XtraHospitalType value) {
        this.xtraHospital = value;
    }

    /**
     * Gets the value of the dateBegin property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateBegin() {
        return dateBegin;
    }

    /**
     * Sets the value of the dateBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateBegin(XMLGregorianCalendar value) {
        this.dateBegin = value;
    }

    /**
     * Gets the value of the dateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEnd() {
        return dateEnd;
    }

    /**
     * Sets the value of the dateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEnd(XMLGregorianCalendar value) {
        this.dateEnd = value;
    }

    /**
     * Gets the value of the gestationWeek13 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGestationWeek13() {
        return gestationWeek13;
    }

    /**
     * Sets the value of the gestationWeek13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGestationWeek13(XMLGregorianCalendar value) {
        this.gestationWeek13 = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanton(String value) {
        this.canton = value;
    }

    /**
     * Gets the value of the treatment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatment() {
        if (treatment == null) {
            return "ambulatory";
        } else {
            return treatment;
        }
    }

    /**
     * Sets the value of the treatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatment(String value) {
        this.treatment = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the apid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApid() {
        return apid;
    }

    /**
     * Sets the value of the apid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApid(String value) {
        this.apid = value;
    }

    /**
     * Gets the value of the acid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcid() {
        return acid;
    }

    /**
     * Sets the value of the acid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcid(String value) {
        this.acid = value;
    }

}
