//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.metas.edi.esb.jaxb.metasfresh;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for C_Order_DeliveryViaRuleEnum</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="C_Order_DeliveryViaRuleEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="P"/>
 *     <enumeration value="S"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "C_Order_DeliveryViaRuleEnum")
@XmlEnum
public enum COrderDeliveryViaRuleEnum {

    P,
    S;

    public String value() {
        return name();
    }

    public static COrderDeliveryViaRuleEnum fromValue(String v) {
        return valueOf(v);
    }

}
