export const NO_CONNECTION = 'NO_CONNECTION';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLOSE_PROCESS_MODAL = 'CLOSE_PROCESS_MODAL';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const USER_SESSION_INIT = 'USER_SESSION_INIT';
export const USER_SESSION_UPDATE = 'USER_SESSION_UPDATE';

export const SET_PROCESS_STATE_SAVED = 'SET_PROCESS_STATE_SAVED';
export const SET_PROCESS_STATE_PENDING = 'SET_PROCESS_STATE_PENDING';

// SCOPED ACTIONS
export const INIT_DATA_SUCCESS = 'INIT_DATA_SUCCESS';
export const INIT_LAYOUT_SUCCESS = 'INIT_LAYOUT_SUCCESS';
export const ADD_ROW_DATA = 'ADD_ROW_DATA';
export const SORT_TAB = 'SORT_TAB';
export const ACTIVATE_TAB = 'ACTIVATE_TAB';
export const UNSELECT_TAB = 'UNSELECT_TAB';
export const ADD_NEW_ROW = 'ADD_NEW_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const UPDATE_ROW_PROPERTY = 'UPDATE_ROW_PROPERTY';
export const UPDATE_DATA_PROPERTY = 'UPDATE_DATA_PROPERTY';
export const UPDATE_DATA_FIELD_PROPERTY = 'UPDATE_DATA_FIELD_PROPERTY';
export const UPDATE_ROW_FIELD_PROPERTY = 'UPDATE_ROW_FIELD_PROPERTY';
export const UPDATE_ROW_STATUS = 'UPDATE_ROW_STATUS';
export const CLEAR_MASTER_DATA = 'CLEAR_MASTER_DATA';

export const UPDATE_DATA_VALID_STATUS = 'UPDATE_DATA_VALID_STATUS';
export const UPDATE_DATA_SAVE_STATUS = 'UPDATE_DATA_SAVE_STATUS';
export const UPDATE_DATA_INCLUDED_TABS_INFO = 'UPDATE_DATA_INCLUDED_TABS_INFO';
// END OF SCOPED ACTIONS

// INDICATOR ACTIONS
export const CHANGE_INDICATOR_STATE = 'CHANGE_INDICATOR_STATE';
// END OF INDICATOR ACTIONS

// NOTIFICATION ACTIONS
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const SET_NOTIFICATION_PROGRESS = 'SET_NOTIFICATION_PROGRESS';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
// END OF NOTIFICATION ACTIONS

//AUTH ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ENABLE_TUTORIAL = 'ENABLE_TUTORIAL';
//END OF AUTH ACTIONS

export const INIT_FILTERS_PARAMETERS = 'INIT_FILTERS_PARAMETERS';
export const DELETE_FILTERS_PARAMETERS = 'DELETE_FILTERS_PARAMETERS';
export const UPDATE_FILTERS_PARAMETERS = 'UPDATE_FILTERS_PARAMETERS';

export const DRAGGABLE_CARD = 'DRAGGABLE_CARD';

export const NEW_PROCESS_SUCCESS = 'NEW_PROCESS_SUCCESS';

export const REMOVE_TABLE_ITEMS_SELECTION = 'REMOVE_TABLE_ITEMS_SELECTION';
export const SELECT_TABLE_ITEMS = 'SELECT_TABLE_ITEMS';

export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';

export const OPEN_RAW_MODAL = 'OPEN_RAW_MODAL';
export const CLOSE_RAW_MODAL = 'CLOSE_RAW_MODAL';

export const OPEN_FILTER_BOX = 'OPEN_FILTER_BOX';
export const CLOSE_FILTER_BOX = 'CLOSE_FILTER_BOX';

export const SET_LATEST_NEW_DOCUMENT = 'SET_LATEST_NEW_DOCUMENT';

export const ALLOW_SHORTCUT = 'ALLOW_SHORTCUT';
export const DISABLE_SHORTCUT = 'DISABLE_SHORTCUT';

export const PATCH_REQUEST = 'PATCH_REQUEST';
export const PATCH_SUCCESS = 'PATCH_SUCCESS';
export const PATCH_FAILURE = 'PATCH_FAILURE';
export const PATCH_RESET = 'PATCH_RESET';

export const ALLOW_OUTSIDE_CLICK = 'ALLOW_OUTSIDE_CLICK';
export const DISABLE_OUTSIDE_CLICK = 'DISABLE_OUTSIDE_CLICK';
