export const INIT_DATA_SUCCESS = 'INIT_DATA_SUCCESS';
export const ADD_ROW_DATA = 'ADD_ROW_DATA';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_PROPERTY = 'UPDATE_DATA_PROPERTY';
export const INIT_LAYOUT_SUCCESS = 'INIT_LAYOUT_SUCCESS';

export const NO_CONNECTION = 'NO_CONNECTION';

export const UNLOADING_CHANGED = 'UNLOADING_CHANGED';
export const INVOICE_CHANGED = 'INVOICE_CHANGED';
export const PURCHASER_CHANGED = 'PURCHASER_CHANGED';
export const PURCHASER_PROP_CHANGED = 'PURCHASER_PROP_CHANGED';

export const EDIT_PRODUCT_PROPERTY = 'EDIT_PRODUCT_PROPERTY';
export const CHANGE_PRODUCT_PROPERTY = 'CHANGE_PRODUCT_PROPERTY';
export const SAVE_PRODUCT_PROPERTY = 'SAVE_PRODUCT_PROPERTY';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_ONE_PRODUCT = 'SELECT_ONE_PRODUCT';
export const SELECT_RANGE_PRODUCT = 'SELECT_RANGE_PRODUCT';
export const DESELECT_PRODUCT = 'DESELECT_PRODUCT';
export const DESELECT_ALL_PRODUCTS = 'DESELECT_ALL_PRODUCTS';

export const SHOW_SUBHEADER = 'SHOW_SUBHEADER';
export const HIDE_SUBHEADER = 'HIDE_SUBHEADER';

export const DELETE_SELECTED_PRODUCTS = 'DELETE_SELECTED_PRODUCTS';

export const AUTOCOMPLETE = 'AUTOCOMPLETE';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const TOGGLE_ORDER_LIST = 'TOGGLE_ORDER_LIST';

export const NEW_SALES_ORDER_CREATED = 'NEW_SALES_ORDER_CREATED';

export const TOGGLE_PRODUCT_ORDER_SUMMARY = 'TOGGLE_PRODUCT_ORDER_SUMMARY';

export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
