export const INIT_DATA_SUCCESS = 'INIT_DATA_SUCCESS';
export const ADD_ROW_DATA = 'ADD_ROW_DATA';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_ROW_SUCCESS = 'UPDATE_ROW_SUCCESS';
export const UPDATE_DATA_PROPERTY = 'UPDATE_DATA_PROPERTY';
export const UPDATE_ROW_PROPERTY = 'UPDATE_ROW_PROPERTY';
export const INIT_LAYOUT_SUCCESS = 'INIT_LAYOUT_SUCCESS';

export const NO_CONNECTION = 'NO_CONNECTION';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_ONE_PRODUCT = 'SELECT_ONE_PRODUCT';
export const SELECT_RANGE_PRODUCT = 'SELECT_RANGE_PRODUCT';
export const DESELECT_PRODUCT = 'DESELECT_PRODUCT';
export const DESELECT_ALL_PRODUCTS = 'DESELECT_ALL_PRODUCTS';
