export const SET_LIST_ID = 'SET_LIST_ID';

export const SET_LIST_FILTERS = 'SET_LIST_FILTERS';

export const SET_LIST_SORTING = 'SET_LIST_SORTING';

export const SET_LIST_PAGINATION = 'SET_LIST_PAGINATION';

export const SET_LIST_INCLUDED_VIEW = 'SET_LIST_INCLUDED_VIEW';

export const CLOSE_LIST_INCLUDED_VIEW = 'CLOSE_LIST_INCLUDED_VIEW';
