// MENU ACTIONS
export const SET_BREADCRUMB = 'SET_BREADCRUMB';
export const SET_HOMEMENU = 'SET_HOMEMENU';
export const SET_REFERENCES = 'SET_REFERENCES';
export const SET_ACTIONS = 'SET_ACTIONS';
// END OF MENU ACTIONS
