storageClassName: do-block-storage #storage class for persistent volumes

pgadmin:
  image: dpage/pgadmin4
  port:
    pgadmin: 80
  dataStorageSize: 1Gi
  defaultEmail: example@mail.com #replace
  defaultPassword: password #replace

ingress:
  pgadmin: 
    url: pgadmin.demo-demouser.metasfresh.com #replace with your domain
    enabled: true
  tls:
    enabled: true