
ALTER TABLE M_Warehouse DROP CONSTRAINT IF EXISTS PPPlant_MWarehouse; 
ALTER TABLE M_Warehouse ADD CONSTRAINT PPPlant_MWarehouse FOREIGN KEY (PP_Plant_ID) REFERENCES S_Resource DEFERRABLE INITIALLY DEFERRED;
