
-- Clean up
DELETE FROM AD_User_SortPref_Hdr h WHERE h.AD_User_ID IS NOT NULL AND NOT EXISTS (select 1 FROM AD_User u WHERE u.AD_User_ID=h.AD_User_ID);
DELETE FROM AD_User_SortPref_Line l WHERE NOT EXISTS (select 1 from AD_User_SortPref_Hdr h where h.AD_User_SortPref_Hdr_ID=l.AD_User_SortPref_Hdr_ID);
DELETE FROM AD_User_SortPref_Line_Product lp WHERE NOT EXISTS (select 1 FROM M_Product p WHERE p.M_Product_ID=lp.M_Product_ID);
DELETE FROM AD_User_SortPref_Line_Product lp WHERE NOT EXISTS (select 1 FROM AD_User_SortPref_Line l WHERE l.AD_User_SortPref_Line_ID=lp.AD_User_SortPref_Line_ID);

COMMIT;

-- Now add FKs so this won't happen again
-- SELECT * FROM db_columns_fk WHERE TableName like 'AD_User_SortPref%' AND IsMissing='Y';
ALTER TABLE AD_User_SortPref_Hdr DROP CONSTRAINT IF EXISTS ADTab_ADUserSortPrefHdr;
ALTER TABLE AD_User_SortPref_Hdr DROP CONSTRAINT IF EXISTS ADWindow_ADUserSortPrefHdr;
ALTER TABLE AD_User_SortPref_Line_Product DROP CONSTRAINT IF EXISTS ADUserSortPrefLine_ADUserSortP;
ALTER TABLE AD_User_SortPref_Hdr DROP CONSTRAINT IF EXISTS ADInfoWindow_ADUserSortPrefHdr;
ALTER TABLE AD_User_SortPref_Line DROP CONSTRAINT IF EXISTS ADInfoColumn_ADUserSortPrefLin;
ALTER TABLE AD_User_SortPref_Hdr DROP CONSTRAINT IF EXISTS ADForm_ADUserSortPrefHdr;
ALTER TABLE AD_User_SortPref_Hdr DROP CONSTRAINT IF EXISTS ADUser_ADUserSortPrefHdr;
ALTER TABLE AD_User_SortPref_Line_Product DROP CONSTRAINT IF EXISTS MProduct_ADUserSortPrefLinePro;
ALTER TABLE AD_User_SortPref_Line DROP CONSTRAINT IF EXISTS ADField_ADUserSortPrefLine;
ALTER TABLE AD_User_SortPref_Line DROP CONSTRAINT IF EXISTS ADUserSortPrefHdr_ADUserSortPr;


ALTER TABLE AD_User_SortPref_Hdr ADD CONSTRAINT ADTab_ADUserSortPrefHdr FOREIGN KEY (AD_Tab_ID) REFERENCES AD_Tab DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Hdr ADD CONSTRAINT ADWindow_ADUserSortPrefHdr FOREIGN KEY (AD_Window_ID) REFERENCES AD_Window DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Line_Product ADD CONSTRAINT ADUserSortPrefLine_ADUserSortP FOREIGN KEY (AD_User_SortPref_Line_ID) REFERENCES AD_User_SortPref_Line DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Hdr ADD CONSTRAINT ADInfoWindow_ADUserSortPrefHdr FOREIGN KEY (AD_InfoWindow_ID) REFERENCES AD_InfoWindow DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Line ADD CONSTRAINT ADInfoColumn_ADUserSortPrefLin FOREIGN KEY (AD_InfoColumn_ID) REFERENCES AD_InfoColumn DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Hdr ADD CONSTRAINT ADForm_ADUserSortPrefHdr FOREIGN KEY (AD_Form_ID) REFERENCES AD_Form DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Hdr ADD CONSTRAINT ADUser_ADUserSortPrefHdr FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Line_Product ADD CONSTRAINT MProduct_ADUserSortPrefLinePro FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Line ADD CONSTRAINT ADField_ADUserSortPrefLine FOREIGN KEY (AD_Field_ID) REFERENCES AD_Field DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_User_SortPref_Line ADD CONSTRAINT ADUserSortPrefHdr_ADUserSortPr FOREIGN KEY (AD_User_SortPref_Hdr_ID) REFERENCES AD_User_SortPref_Hdr DEFERRABLE INITIALLY DEFERRED;

