-- 03.08.2016 10:11
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE AD_UI_Section (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Tab_ID NUMERIC(10) NOT NULL, AD_UI_Section_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(2000) DEFAULT NULL , Help TEXT DEFAULT NULL , IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, SeqNo NUMERIC(10) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_UI_Section_Key PRIMARY KEY (AD_UI_Section_ID))
;


-- 02.08.2016 18:13
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE AD_UI_Column (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_UI_Column_ID NUMERIC(10) NOT NULL, AD_UI_Section_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, UIStyle CHAR(1) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_UI_Column_Key PRIMARY KEY (AD_UI_Column_ID))
;


-- 03.08.2016 10:06
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE AD_UI_ElementGroup (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_UI_Column_ID NUMERIC(10) DEFAULT NULL , AD_UI_ElementGroup_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, SeqNo NUMERIC(10) NOT NULL, UIStyle VARCHAR(40) DEFAULT NULL , Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_UI_ElementGroup_Key PRIMARY KEY (AD_UI_ElementGroup_ID))
;

-- 03.08.2016 10:09
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE AD_UI_Element (AD_Client_ID NUMERIC(10) NOT NULL, AD_Field_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, AD_UI_Element_ID NUMERIC(10) NOT NULL, AD_UI_ElementGroup_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(2000) DEFAULT NULL , Help TEXT DEFAULT NULL , IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, IsAdvancedField CHAR(1) DEFAULT 'N' CHECK (IsAdvancedField IN ('Y','N')) NOT NULL, IsBasicField CHAR(1) DEFAULT 'Y' CHECK (IsBasicField IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, SeqNo NUMERIC(10) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_UI_Element_Key PRIMARY KEY (AD_UI_Element_ID))
;


-- 02.08.2016 16:03
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE AD_UI_ElementField (AD_Client_ID NUMERIC(10) NOT NULL, AD_Field_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_UI_Element_ID NUMERIC(10) DEFAULT NULL , AD_UI_ElementField_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_UI_ElementField_Key PRIMARY KEY (AD_UI_ElementField_ID))
;

