-- select * from db_columns_fk where IsMIssing='Y' and tableName like 'AD_UI%'

ALTER TABLE AD_UI_Element ADD CONSTRAINT ADField_ADUIElement FOREIGN KEY (AD_Field_ID) REFERENCES AD_Field DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_Element ADD CONSTRAINT ADUIElementGroup_ADUIElement FOREIGN KEY (AD_UI_ElementGroup_ID) REFERENCES AD_UI_ElementGroup DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_ElementField ADD CONSTRAINT ADUIElement_ADUIElementField FOREIGN KEY (AD_UI_Element_ID) REFERENCES AD_UI_Element DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_ElementField ADD CONSTRAINT ADField_ADUIElementField FOREIGN KEY (AD_Field_ID) REFERENCES AD_Field DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_ElementGroup ADD CONSTRAINT ADUIColumn_ADUIElementGroup FOREIGN KEY (AD_UI_Column_ID) REFERENCES AD_UI_Column DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_Section ADD CONSTRAINT ADTab_ADUISection FOREIGN KEY (AD_Tab_ID) REFERENCES AD_Tab DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_Column ADD CONSTRAINT ADUISection_ADUIColumn FOREIGN KEY (AD_UI_Section_ID) REFERENCES AD_UI_Section DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_UI_Element ADD CONSTRAINT ADTab_ADUIElement FOREIGN KEY (AD_Tab_ID) REFERENCES AD_Tab DEFERRABLE INITIALLY DEFERRED;

