-- Table creation
-- 2021-08-24T13:04:50.639Z
-- URL zum Konzept
/* DDL */ CREATE TABLE public.CRM_Occupation (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10), Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CRM_Occupation_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, JobType VARCHAR(40), Name VARCHAR(40) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(260) NOT NULL, CONSTRAINT CRM_Occupation_Key PRIMARY KEY (CRM_Occupation_ID))
;

-- 2021-08-24T14:18:29.963Z
-- URL zum Konzept
/* DDL */ CREATE TABLE public.AD_User_Occupation_Job (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_User_ID NUMERIC(10), AD_User_Occupation_Job_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CRM_Occupation_ID NUMERIC(10), IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT ADUser_ADUserOccupationJob FOREIGN KEY (AD_User_ID) REFERENCES public.AD_User DEFERRABLE INITIALLY DEFERRED, CONSTRAINT AD_User_Occupation_Job_Key PRIMARY KEY (AD_User_Occupation_Job_ID), CONSTRAINT CRMOccupation_ADUserOccupationJob FOREIGN KEY (CRM_Occupation_ID) REFERENCES public.CRM_Occupation DEFERRABLE INITIALLY DEFERRED)
;