-- Column: M_Shipment_Constraint.C_Invoice_ID
-- Column SQL (old): (  select i.c_invoice_ID   from c_invoice i  join c_dunning_candidate dc on  i.c_invoice_id = dc.record_id and dc.ad_table_id = get_table_ID('C_Invoice')  join c_dunningdoc_line_source dls on dc.c_dunning_candidate_id = dls.c_dunning_candidate_id  join c_dunningdoc_line ddl on dls.c_dunningdoc_line_id = ddl.c_dunningdoc_line_id  join c_dunningdoc dd on ddl.c_dunningdoc_id =  dd.c_dunningdoc_id  join m_shipment_constraint sc on dd.c_dunningdoc_id = sc.sourcedoc_record_id and sc.Sourcedoc_Table_ID = get_Table_ID ('C_DunningDoc')  where sc.m_shipment_constraint_ID = m_shipment_constraint.m_shipment_constraint_ID  )
-- 2022-06-06T13:53:56.378Z
UPDATE AD_Column SET ColumnSQL='( select i.c_invoice_ID from c_invoice i   join c_dunning_candidate dc on  i.c_invoice_id = dc.record_id and dc.ad_table_id = get_table_ID(''C_Invoice'')   join c_dunningdoc_line_source dls on dc.c_dunning_candidate_id = dls.c_dunning_candidate_id   join c_dunningdoc_line ddl on dls.c_dunningdoc_line_id = ddl.c_dunningdoc_line_id   join c_dunningdoc dd on ddl.c_dunningdoc_id =  dd.c_dunningdoc_id join m_shipment_constraint sc on dd.c_dunningdoc_id = sc.sourcedoc_record_id and sc.Sourcedoc_Table_ID = get_Table_ID (''C_DunningDoc'') where sc.m_shipment_constraint_ID = @JoinTableNameOrAliasIncludingDot@m_shipment_constraint_ID )', IsLazyLoading='Y',Updated=TO_TIMESTAMP('2022-06-06 16:53:56','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=559520
;

-- Column: M_Shipment_Constraint.IsPaid
-- Column SQL (old):  (  select i.IsPaid   from c_invoice i  join c_dunning_candidate dc on  i.c_invoice_id = dc.record_id and dc.ad_table_id = get_table_ID('C_Invoice')  join c_dunningdoc_line_source dls on dc.c_dunning_candidate_id = dls.c_dunning_candidate_id  join c_dunningdoc_line ddl on dls.c_dunningdoc_line_id = ddl.c_dunningdoc_line_id  join c_dunningdoc dd on ddl.c_dunningdoc_id =  dd.c_dunningdoc_id  join m_shipment_constraint sc on dd.c_dunningdoc_id = sc.sourcedoc_record_id and sc.Sourcedoc_Table_ID = get_Table_ID ('C_DunningDoc')  where sc.m_shipment_constraint_ID = m_shipment_constraint.m_shipment_constraint_ID    )
-- 2022-06-06T13:55:12.949Z
UPDATE AD_Column SET ColumnSQL='(  select i.IsPaid from c_invoice i  join c_dunning_candidate dc on  i.c_invoice_id = dc.record_id and dc.ad_table_id = get_table_ID(''C_Invoice'')  join c_dunningdoc_line_source dls on dc.c_dunning_candidate_id = dls.c_dunning_candidate_id  join c_dunningdoc_line ddl on dls.c_dunningdoc_line_id = ddl.c_dunningdoc_line_id  join c_dunningdoc dd on ddl.c_dunningdoc_id =  dd.c_dunningdoc_id  join m_shipment_constraint sc on dd.c_dunningdoc_id = sc.sourcedoc_record_id and sc.Sourcedoc_Table_ID = get_Table_ID (''C_DunningDoc'')  where sc.m_shipment_constraint_ID = @JoinTableNameOrAliasIncludingDot@m_shipment_constraint_ID  )', IsLazyLoading='Y',Updated=TO_TIMESTAMP('2022-06-06 16:55:12','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=559521
;

