-- me03 30520: clarify the PP_Activity_Type routing-activity ref-list (AD_Reference 541463).
-- Give each of the 11 list items a clear name + a description (what it does / when it runs),
-- and a real German translation instead of an English copy.
-- Convention (matches the rest of AD_Ref_List): German in the base Name/Description column;
-- English provided as the en_US translation override; de_DE/de_CH carry German (IsTranslated='Y').
-- Production-context terminology (per the authoritative HUTraceType ref-list): material *issue* to
-- the order = "Zuteilung"/zuteilen (PRODUCTION_ISSUE -> Produktionszuteilung); finished-goods
-- *receipt* from the order = "Entnahme" (PRODUCTION_RECEIPT -> Produktionsentnahme). "Wareneingang"
-- (warehouse goods-in) is deliberately NOT used for the production-receipt items.
-- The code-facing Value (MI, GenerateHUQRCodes, ...) and the fr_CH translation are left untouched.

-- MI (542919) Raw Materials Issue
UPDATE ad_ref_list SET name='Materialzuteilung (Rohstoffe)', description='Teilt die für den Produktionsauftrag benötigten Rohstoffe/Komponenten dem Auftrag zu und verbraucht sie aus dem Lager.', updated=TO_TIMESTAMP('2026-06-22 12:00:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542919;
UPDATE ad_ref_list_trl SET name='Raw Materials Issue', description='Issue (consume) the raw materials / components required by the production order from stock.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:00:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542919 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Materialzuteilung (Rohstoffe)', description='Teilt die für den Produktionsauftrag benötigten Rohstoffe/Komponenten dem Auftrag zu und verbraucht sie aus dem Lager.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:00:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542919 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Materialzuteilung (Rohstoffe)', description='Teilt die für den Produktionsauftrag benötigten Rohstoffe/Komponenten dem Auftrag zu und verbraucht sie aus dem Lager.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:00:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542919 AND ad_language='de_CH';

-- MIA (543135) Raw Materials Issue Adjustment
UPDATE ad_ref_list SET name='Korrektur Materialzuteilung', description='Korrigiert die dem Produktionsauftrag bereits zugeteilten Rohstoffmengen.', updated=TO_TIMESTAMP('2026-06-22 12:01:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543135;
UPDATE ad_ref_list_trl SET name='Raw Materials Issue Adjustment', description='Correct the quantities of raw materials already issued to the order.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:01:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543135 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Korrektur Materialzuteilung', description='Korrigiert die dem Produktionsauftrag bereits zugeteilten Rohstoffmengen.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:01:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543135 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Korrektur Materialzuteilung', description='Korrigiert die dem Produktionsauftrag bereits zugeteilten Rohstoffmengen.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:01:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543135 AND ad_language='de_CH';

-- IssueOnlyWhatWasReceived (543705) Issue Only What Was Received — backflush against the finished-goods production receipt
UPDATE ad_ref_list SET name='Nur Entnommenes zuteilen', description='Ein-Klick-Schritt, der Rohstoffe genau in der entnommenen (produzierten) Menge zuteilt (Backflush) – gemäss der konfigurierten Zuteilungsstrategie.', updated=TO_TIMESTAMP('2026-06-22 12:02:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543705;
UPDATE ad_ref_list_trl SET name='Issue Only What Was Received', description='One-tap step that issues raw materials in exactly the quantity that was received/produced (backflush), using the configured issue strategy.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:02:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543705 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Nur Entnommenes zuteilen', description='Ein-Klick-Schritt, der Rohstoffe genau in der entnommenen (produzierten) Menge zuteilt (Backflush) – gemäss der konfigurierten Zuteilungsstrategie.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:02:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543705 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Nur Entnommenes zuteilen', description='Ein-Klick-Schritt, der Rohstoffe genau in der entnommenen (produzierten) Menge zuteilt (Backflush) – gemäss der konfigurierten Zuteilungsstrategie.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:02:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543705 AND ad_language='de_CH';

-- MR (542920) Material Receipt — finished-goods production receipt
UPDATE ad_ref_list SET name='Produktionsentnahme (Fertigware)', description='Bucht die vom Produktionsauftrag produzierte Fertigware ins Lager ein und erzeugt dabei die Handling Units (HUs).', updated=TO_TIMESTAMP('2026-06-22 12:03:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542920;
UPDATE ad_ref_list_trl SET name='Material Receipt', description='Receive the finished goods produced by the order into stock, creating the handling units (HUs).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:03:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542920 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Produktionsentnahme (Fertigware)', description='Bucht die vom Produktionsauftrag produzierte Fertigware ins Lager ein und erzeugt dabei die Handling Units (HUs).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:03:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542920 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Produktionsentnahme (Fertigware)', description='Bucht die vom Produktionsauftrag produzierte Fertigware ins Lager ein und erzeugt dabei die Handling Units (HUs).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:03:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542920 AND ad_language='de_CH';

-- WR (542921) Work Report
UPDATE ad_ref_list SET name='Arbeitsrückmeldung', description='Meldet die für diesen Arbeitsgang geleistete Arbeit zurück (Schritt bestätigen / Fortschritt erfassen). Keine Materialbewegung.', updated=TO_TIMESTAMP('2026-06-22 12:04:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542921;
UPDATE ad_ref_list_trl SET name='Work Report', description='Report the work performed for this routing step (confirm the step / record progress). No material movement.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:04:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542921 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Arbeitsrückmeldung', description='Meldet die für diesen Arbeitsgang geleistete Arbeit zurück (Schritt bestätigen / Fortschritt erfassen). Keine Materialbewegung.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:04:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542921 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Arbeitsrückmeldung', description='Meldet die für diesen Arbeitsgang geleistete Arbeit zurück (Schritt bestätigen / Fortschritt erfassen). Keine Materialbewegung.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:04:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542921 AND ad_language='de_CH';

-- AC (542922) Activity Confirmation
UPDATE ad_ref_list SET name='Arbeitsgang-Bestätigung', description='Der Werker bestätigt, dass dieser Arbeitsgang abgeschlossen ist. Keine Materialbewegung.', updated=TO_TIMESTAMP('2026-06-22 12:05:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542922;
UPDATE ad_ref_list_trl SET name='Activity Confirmation', description='Operator confirms that this routing step is completed. No material movement.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:05:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542922 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Arbeitsgang-Bestätigung', description='Der Werker bestätigt, dass dieser Arbeitsgang abgeschlossen ist. Keine Materialbewegung.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:05:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542922 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Arbeitsgang-Bestätigung', description='Der Werker bestätigt, dass dieser Arbeitsgang abgeschlossen ist. Keine Materialbewegung.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:05:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=542922 AND ad_language='de_CH';

-- GenerateHUQRCodes (543114) Generate HU QR-Codes (before receipt)
UPDATE ad_ref_list SET name='HU-QR-Codes erzeugen (vor Entnahme)', description='Erzeugt und druckt QR-Code-Etiketten für die zu produzierende Fertigware – vor der Produktionsentnahme. Rendert die QR-Codes direkt (JSON) über einen fest hinterlegten QR-Code-Report und berücksichtigt M_HU_Label_Config nicht. Für konfigurierbare HU-Etiketten nach der Produktionsentnahme "HU-QR-Codes nach Entnahme drucken" verwenden.', updated=TO_TIMESTAMP('2026-06-22 12:06:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543114;
UPDATE ad_ref_list_trl SET name='Generate HU QR-Codes (before receipt)', description='Generates and prints QR-code labels for the finished goods to be produced, before they are received. Renders the QR codes directly (JSON) via a fixed QR-code report and does not read M_HU_Label_Config. For configurable HU labels printed after receipt, use "Print Received HU QR-Codes".', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:06:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543114 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='HU-QR-Codes erzeugen (vor Entnahme)', description='Erzeugt und druckt QR-Code-Etiketten für die zu produzierende Fertigware – vor der Produktionsentnahme. Rendert die QR-Codes direkt (JSON) über einen fest hinterlegten QR-Code-Report und berücksichtigt M_HU_Label_Config nicht. Für konfigurierbare HU-Etiketten nach der Produktionsentnahme "HU-QR-Codes nach Entnahme drucken" verwenden.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:06:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543114 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='HU-QR-Codes erzeugen (vor Entnahme)', description='Erzeugt und druckt QR-Code-Etiketten für die zu produzierende Fertigware – vor der Produktionsentnahme. Rendert die QR-Codes direkt (JSON) über einen fest hinterlegten QR-Code-Report und berücksichtigt M_HU_Label_Config nicht. Für konfigurierbare HU-Etiketten nach der Produktionsentnahme "HU-QR-Codes nach Entnahme drucken" verwenden.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:06:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543114 AND ad_language='de_CH';

-- PrintReceivedHUQRCodes (543361) Print Received HU QR-Codes (after receipt)
UPDATE ad_ref_list SET name='HU-QR-Codes nach Entnahme drucken', description='Druckt (erneut) die QR-Code-Etiketten für die bereits zu diesem Auftrag entnommenen Fertigware-HUs. Druckt die tatsächlichen HUs und berücksichtigt M_HU_Label_Config (das je Belegart konfigurierte Etikett).', updated=TO_TIMESTAMP('2026-06-22 12:07:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543361;
UPDATE ad_ref_list_trl SET name='Print Received HU QR-Codes (after receipt)', description='(Re)prints the QR-code labels for the finished-goods HUs already received on this order. Prints the real HUs and honours M_HU_Label_Config (the configured label per source document type).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:07:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543361 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='HU-QR-Codes nach Entnahme drucken', description='Druckt (erneut) die QR-Code-Etiketten für die bereits zu diesem Auftrag entnommenen Fertigware-HUs. Druckt die tatsächlichen HUs und berücksichtigt M_HU_Label_Config (das je Belegart konfigurierte Etikett).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:07:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543361 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='HU-QR-Codes nach Entnahme drucken', description='Druckt (erneut) die QR-Code-Etiketten für die bereits zu diesem Auftrag entnommenen Fertigware-HUs. Druckt die tatsächlichen HUs und berücksichtigt M_HU_Label_Config (das je Belegart konfigurierte Etikett).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:07:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543361 AND ad_language='de_CH';

-- ScanScaleDevice (543130) Scan Scale Device
UPDATE ad_ref_list SET name='Waage scannen', description='Scannt bzw. verbindet ein Waagengerät, um während des Auftrags ein gemessenes Gewicht zu erfassen.', updated=TO_TIMESTAMP('2026-06-22 12:08:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543130;
UPDATE ad_ref_list_trl SET name='Scan Scale Device', description='Scan/connect a weighing-scale device to capture a measured weight during the job.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:08:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543130 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Waage scannen', description='Scannt bzw. verbindet ein Waagengerät, um während des Auftrags ein gemessenes Gewicht zu erfassen.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:08:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543130 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Waage scannen', description='Scannt bzw. verbindet ein Waagengerät, um während des Auftrags ein gemessenes Gewicht zu erfassen.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:08:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543130 AND ad_language='de_CH';

-- ValidateLocator (543703) Validate Locator
UPDATE ad_ref_list SET name='Lagerort prüfen', description='Scannt und prüft den Barcode eines Lagerorts, z. B. zur Bestätigung, dass der Werker am richtigen Ort ist.', updated=TO_TIMESTAMP('2026-06-22 12:09:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543703;
UPDATE ad_ref_list_trl SET name='Validate Locator', description='Scan and validate a warehouse locator (bin) barcode, e.g. to confirm the operator is at the correct location.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:09:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543703 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Lagerort prüfen', description='Scannt und prüft den Barcode eines Lagerorts, z. B. zur Bestätigung, dass der Werker am richtigen Ort ist.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:09:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543703 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Lagerort prüfen', description='Scannt und prüft den Barcode eines Lagerorts, z. B. zur Bestätigung, dass der Werker am richtigen Ort ist.', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:09:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543703 AND ad_language='de_CH';

-- CallExternalSystem (543331) Call External System
UPDATE ad_ref_list SET name='Externes System aufrufen', description='Löst während des Auftrags einen Aufruf an ein konfiguriertes externes System aus (z. B. Datenübergabe an ein angebundenes System).', updated=TO_TIMESTAMP('2026-06-22 12:10:00','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543331;
UPDATE ad_ref_list_trl SET name='Call External System', description='Triggers a call to a configured external system during the job (e.g. hand data over to a connected system).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:10:01','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543331 AND ad_language='en_US';
UPDATE ad_ref_list_trl SET name='Externes System aufrufen', description='Löst während des Auftrags einen Aufruf an ein konfiguriertes externes System aus (z. B. Datenübergabe an ein angebundenes System).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:10:02','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543331 AND ad_language='de_DE';
UPDATE ad_ref_list_trl SET name='Externes System aufrufen', description='Löst während des Auftrags einen Aufruf an ein konfiguriertes externes System aus (z. B. Datenübergabe an ein angebundenes System).', istranslated='Y', updated=TO_TIMESTAMP('2026-06-22 12:10:03','YYYY-MM-DD HH24:MI:SS'), updatedby=100 WHERE ad_ref_list_id=543331 AND ad_language='de_CH';
