FROM node:18 as build

RUN npm install -g webpack webpack-cli

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* && localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8
ENV TZ=Europe/Berlin

WORKDIR /app 

COPY misc/services/mobile-webui/mobile-webui-frontend-testing/package.json* .
COPY misc/services/mobile-webui/mobile-webui-frontend-testing/yarn.lock* .

RUN yarn install

COPY misc/services/mobile-webui/mobile-webui-frontend-testing/ .

CMD ["yarn", "playwright", "test"]