ARG REFNAME=local
FROM metasfresh/metas-api:$REFNAME as api

RUN apt-get -y update && apt-get -y install netcat && rm -rf /var/lib/apt/lists/*

RUN mv /opt/metasfresh/metasfresh-webui-api /opt/metasfresh-webui-api