ARG REFNAME=local
FROM metasfresh/metas-api:$REFNAME as api

FROM eclipse-temurin:17.0.7_7-jdk as runtime

RUN apt-get -y update && apt-get -y install locales netcat && rm -rf /var/lib/apt/lists/*
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8
ENV TZ=Europe/Berlin

WORKDIR /opt/metasfresh-webui-api

RUN mkdir log && mkdir heapdump

COPY --from=api /opt/metasfresh-webui-api .