FROM node:14 as build

RUN npm install -g webpack webpack-cli

WORKDIR /app 
COPY misc/services/mobile-webui/mobile-webui-frontend/package.json .
# COPY yarn.lock .

RUN yarn install

COPY misc/services/mobile-webui/mobile-webui-frontend/ .

RUN yarn lint
# RUN yarn test --ci

RUN yarn build


FROM nginx:1.21.6 as runtime

COPY docker-builds/nginx/default.conf /etc/nginx/conf.d

WORKDIR /usr/share/nginx/html

COPY --from=build /app/build/ .