ARG REFNAME=local
FROM metasfresh/metas-mvn-backend:$REFNAME as backend


FROM eclipse-temurin:17.0.5_8-jre

RUN apt-get -y update && apt-get -y install locales zip netcat postgresql-client && rm -rf /var/lib/apt/lists/*
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8
ENV TZ=Europe/Berlin


WORKDIR /opt/metasfresh/metasfresh-report
RUN mkdir external-lib
RUN curl -o elastic-apm-agent.jar https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.12.0/elastic-apm-agent-1.12.0.jar
COPY --from=backend /backend/de.metas.report/metasfresh-report-service-standalone/target/docker/metasfresh-report-service-standalone.jar .
COPY --from=backend /backend/de.metas.report/metasfresh-report-service-standalone/target/docker/configs/logback.xml .
COPY --from=backend /backend/de.metas.report/metasfresh-report-service-standalone/target/docker/configs/metasfresh.properties .
COPY --from=backend --chmod=700 /backend/de.metas.report/metasfresh-report-service-standalone/target/docker/start_report_docker.sh .
RUN (unzip -q metasfresh-report-service-standalone.jar || echo "Ignore exit code $? because spring boot's uber jar starts with a shell script") && rm metasfresh-report-service-standalone.jar

WORKDIR /opt/metasfresh
COPY --from=backend /backend/de.metas.report/metasfresh-report-service-standalone/target/docker/dist dist
COPY --from=backend /backend/metasfresh-dist/dist/target/docker/app/reports/ reports/

COPY docker-builds/metadata metadata/

ENTRYPOINT ["/opt/metasfresh/metasfresh-report/start_report_docker.sh"]