ARG REFNAME=local
FROM metasfresh/metas-mvn-camel:$REFNAME as camel

FROM adoptopenjdk:14.0.2_8-jdk-hotspot

WORKDIR /app

COPY --from=camel /camel/de-metas-camel-edi/target/de-metas-camel-edi.jar .

CMD ["java", "-cp", "/app/de-metas-camel-edi-core.jar", "-Dloader.path=/app/libs", "org.springframework.boot.loader.PropertiesLauncher"]