FROM node:17

RUN npm install -g webpack webpack-cli

WORKDIR /app 
COPY misc/services/procurement-webui/procurement-webui-frontend/package.json .
# COPY yarn.lock .

RUN yarn install

COPY misc/services/procurement-webui/procurement-webui-frontend/ .

RUN yarn lint
RUN yarn build
