ARG REFNAME=local
ARG REGISTRY=
FROM ${REGISTRY}metasfresh/metas-mvn-camel:$REFNAME AS camel

COPY docker-builds/mvn/settings.xml /root/.m2/

WORKDIR /camel/de-metas-camel-externalsystems/dist

ARG VERSION=10.0.0-local
RUN mvn versions:set -DnewVersion=$VERSION

CMD mvn clean deploy