ARG REFNAME=local
ARG REGISTRY=
FROM ${REGISTRY}metasfresh/metas-mvn-backend:$REFNAME AS backend

COPY docker-builds/mvn/settings.xml /root/.m2/

WORKDIR /backend/extensionsupport

ARG VERSION=10.0.0-local
RUN mvn versions:set -DnewVersion=$VERSION

CMD mvn clean deploy