package org.adempiere.ad.expression.api.impl;

import com.google.common.collect.ImmutableSet;

/*
 * #%L
 * de.metas.adempiere.adempiere.base
 * %%
 * Copyright (C) 2018 metas GmbH
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/gpl-2.0.html>.
 * #L%
 */

public class LogicExpressionsDatabase
{
	public static ImmutableSet<String> VALID_EXPRESSIONS = ImmutableSet.of(
			"((@C_Order_ID@>0 | @C_OrderLine_ID@>0) & @IsOrderLineReadOnly@=N ) | @S_ResourceAssignment_ID@!0 | @C_Charge_ID@!0",
			"((@QtyToInvoice_Override/0@=0 | (@QtyToInvoice_Override/-1@=-1 & @QtyToInvoice/0@=0)) & @QtyOrdered/0@!0) | @IsToClear/N@=Y | @Processed/N@=Y | @IsError/N@=Y | @IsInDispute/N@=Y",
			"(@ComponentType@='VA'&@BOMType@='C'|@ComponentType@='OP')&@BOMType@='C'",
			"(@ElementType@=X1|@ElementType@=CO)&@$Element_X1@=Y",
			"(@ElementType@=X2|@ElementType@=CO)&@$Element_X2@=Y",
			"(@IsGroupCompensationLine/N@=Y & @GroupCompensationType/-@=D & @GroupCompensationAmtType/-@=P)"
					+ "\n| @IsPriceEditable@!Y",
			"(@OrderType@='OB' | @OrderType@='SO' | @OrderType@='WP') & @IsComment@=N",
			"(@OrderType@='OB' | @OrderType@='SO' | @Processed@='Y') & @IsComment@=N",
			"(@OrderType@='SO' | @Processed@=Y) & @IsComment@=N",
			"(@OrderType@='SO'|@OrderType@='PO')&@FreightCostRule@='F'",
			"(@TenderType@=C|@TenderType@=K)&@IsOnline@=Y",
			"(@Type@=FV|@Type@=CV)&@IsNullFieldValue@=N",
			"@#IsLiberoEnabled@=Y",
			"@$C_Currency_ID@!@C_Currency_ID@",
			"@$Element_AC@=Y ",
			"@$Element_AY@='Y'",
			"@$Element_AY@=Y",
			"@$Element_AY@=Y & @AnyActivity@=N",
			"@$Element_AY@=Y & @OverwriteActivity@=Y",
			"@$Element_BP@=Y",
			"@$Element_BP@=Y & @AnyBPartner@=N",
			"@$Element_BP@=Y & @OverwriteBPartner@=Y",
			"@$Element_LF@=Y",
			"@$Element_LF@=Y & @AnyLocFrom@=N",
			"@$Element_LF@=Y & @OverwriteLocFrom@=Y",
			"@$Element_LT@=Y",
			"@$Element_LT@=Y & @AnyLocTo@=N",
			"@$Element_LT@=Y & @OverwriteLocTo@=Y",
			"@$Element_MC@='Y'",
			"@$Element_MC@=Y",
			"@$Element_MC@=Y & @OverwriteCampaign@=Y",
			"@$Element_MC@=Y& @AnyCampaign@=N",
			"@$Element_OT@=Y",
			"@$Element_OT@=Y & @AnyOrgTrx@=N",
			"@$Element_OT@=Y & @OverwriteOrgTrx@=Y",
			"@$Element_PJ@='Y'",
			"@$Element_PJ@=Y",
			"@$Element_PJ@=Y & @AnyProject@=N",
			"@$Element_PJ@=Y & @C_Invoice_ID@=0 | @C_Invoice_ID@=''",
			"@$Element_PJ@=Y & @OverwriteProject@=Y",
			"@$Element_PR@=Y",
			"@$Element_PR@=Y & @AnyProduct@=N",
			"@$Element_PR@=Y & @OverwriteProduct@=Y",
			"@$Element_SA@=Y",
			"@$Element_SR@=Y",
			"@$Element_SR@=Y & @AnySalesRegion@=N",
			"@$Element_SR@=Y & @OverwriteSalesRegion@=Y",
			"@$Element_TO@=Y",
			"@$Element_U1@='Y'",
			"@$Element_U1@=Y",
			"@$Element_U1@=Y & @AnyUser1@=N",
			"@$Element_U1@=Y & @OverwriteUser1@=Y",
			"@$Element_U2@='Y'",
			"@$Element_U2@=Y",
			"@$Element_U2@=Y & @AnyUser2@=N",
			"@$Element_U2@=Y & @OverwriteUser2@=Y",
			"@$Element_X1@=Y",
			"@$Element_X2@=Y",
			"@$HasAlias@=Y",
			"@A_Accumdepreciation_Acct@!\"\"",
			"@A_Asset_Acct@!\"\"",
			"@A_Asset_CreateDate@!\"\"",
			"@A_Asset_ID@<1&@A_CreateAsset@='Y'",
			"@A_Asset_RevalDate@!\"\"",
			"@A_Asset_Spread_Type@!\"\"",
			"@A_CreateAsset@='Y'",
			"@A_CreateAsset@='Y'&@A_CapvsExp@='Cap'&@A_Asset_ID@<1",
			"@A_Depreciation_Acct@!\"\"",
			"@A_Depreciation_Calc_Type@!\"\"",
			"@A_Depreciation_ID@!1000007",
			"@A_Depreciation_ID@=1000005|@A_Depreciation_ID@=1000010",
			"@A_Depreciation_ID@=1000006",
			"@A_Depreciation_ID@=1000006|@A_Depreciation_ID@=1000007",
			"@A_Depreciation_ID@=1000007",
			"@A_Depreciation_Manual_Amount@!\"\"",
			"@A_Depreciation_Manual_Period@!\"\"",
			"@A_Depreciation_Table_Header_ID@!0",
			"@A_Depreciation_Variable_Perc@!\"\"",
			"@A_Disposal_Loss@!\"\"",
			"@A_Disposal_Revenue@!\"\"",
			"@A_Disposed_Method@=C | @A_Disposed_Method@=T2",
			"@A_Disposed_Method@=T1 | @A_Disposed_Method@=T2",
			"@A_Parent_Asset_ID@!0",
			"@A_Period_End@!\"\"",
			"@A_Period_Start@!\"\"",
			"@A_QTY_Current@!\"\"",
			"@A_QTY_Original@!\"\"",
			"@A_Reval_Accumdep_Offset_Cur@!\"\"",
			"@A_Reval_Accumdep_Offset_Prior@!\"\"",
			"@A_Reval_Cal_Method@!\"\"",
			"@A_Reval_Cost_Offset@!\"\"",
			"@A_Reval_Cost_Offset_Prior@!\"\"",
			"@A_Reval_Depexp_Offset@!\"\"",
			"@A_Salvage_Value@!\"\"",
			"@A_SourceType@='INV'",
			"@A_SourceType@='JRN'",
			"@A_Split_Percent@!\"\"",
			"@A_Split_Type@=AMT",
			"@A_Split_Type@=PER",
			"@A_Split_Type@=QTY",
			"@AccessTypeRule@=A",
			"@AccessTypeRule@=E",
			"@AccessTypeRule@=R",
			"@Action@!'I'",
			"@Action@!'W'",
			"@Action@!'X'",
			"@Action@!\"ST\"",
			"@Action@='I'",
			"@Action@='ST'",
			"@Action@='SU'",
			"@Action@='W'",
			"@Action@='X'",
			"@Action@=\"ST\"",
			"@Action@=\"SU\"",
			"@Action@=B",
			"@Action@=C | @Action@=W | @Action@=X | @Action@=B",
			"@Action@=D",
			"@Action@=D | @WorkflowType@!'M' | @WorkflowType@!'Q'",
			"@Action@=F",
			"@Action@=F | @Action@=L",
			"@Action@=K",
			"@Action@=M",
			"@Action@=P",
			"@Action@=P | @Action@=R",
			"@Action@=T",
			"@Action@=V",
			"@Action@=V | @Action@=C",
			"@Action@=W",
			"@Action@=X",
			"@Action@=Z",
			"@AD_Client_ID@>0",
			"@AD_Client_ID=0",
			"@AD_Element_ID/0@>0",
			"@AD_Element_ID\0@>0",
			"@AD_JavaClass_ID@>0",
			"@AD_MailBox_ID/0@!0",
			"@AD_Org_ID@!0",
			"@AD_PInstance_EndOfTerm_ID@!0",
			"@AD_Process_ID@!0",
			"@AD_Process_ID@>0 | @AD_Form_ID@>0 | @AD_Task_ID@>0 | @AD_Workflow_ID@>0",
			"@AD_Process_ID@>0 | @AD_Form_ID@>0 | @AD_Window_ID@>0 | @AD_Workflow_ID@>0",
			"@AD_Process_ID@>0 | @AD_Window_ID@>0 | @AD_Task_ID@>0 | @AD_Workflow_ID@>0",
			"@AD_Reference_ID@ = 13",
			"@AD_Reference_ID@ = 17",
			"@AD_Reference_ID@!15 & @AD_Reference_ID@!16",
			"@AD_Reference_ID@=10",
			"@AD_Reference_ID@=10 | @AD_Reference_ID@=14",
			"@AD_Reference_ID@=10 | @AD_Reference_ID@=14 | @AD_Reference_ID@=34 | @AD_Reference_ID@=36",
			"@AD_Reference_ID@=10 | @AD_Reference_ID@=30",
			"@AD_Reference_ID@=11 | @AD_Reference_ID@=12 | @AD_Reference_ID@=15 | @AD_Reference_ID@=22 | @AD_Reference_ID@=29",
			"@AD_Reference_ID@=11 | @AD_Reference_ID@=12 | @AD_Reference_ID@=15 | @AD_Reference_ID@=22 | @AD_Reference_ID@=29 | @AD_Reference_ID@=16 | @AD_Reference_ID@=37",
			"@AD_Reference_ID@=13 | @AD_Reference_ID@=18 | @AD_Reference_ID@=19 | @AD_Reference_ID@=30 | @AD_Reference_ID@=21 | @AD_Reference_ID@=31 | @AD_Reference_ID@=25 | @AD_Reference_ID@=33 | @AD_Reference_ID@=35 | @AD_Reference_ID@=32 | @AD_Reference_ID@=27",
			"@AD_Reference_ID@=17 | @AD_Reference_ID@=18",
			"@AD_Reference_ID@=17 | @AD_Reference_ID@=18 | @AD_Reference_ID@=19 | @AD_Reference_ID@=28 | @AD_Reference_ID@=30",
			"@AD_Reference_ID@=17 | @AD_Reference_ID@=18 | @AD_Reference_ID@=30 | @AD_Reference_ID@=28",
			"@AD_Reference_ID@=19 | @AD_Reference_ID@=30",
			"@AD_Reference_ID@=28",
			"@AD_Reference_ID@=30",
			"@AD_Table_ID@ = 318",
			"@AD_Table_ID@!0",
			"@AD_UI_ElementType@=F",
			"@AD_UI_ElementType@=L",
			"@Ad_User_ID@!0",
			"@AD_Window_ID@>0 | @AD_Form_ID@>0 | @AD_Task_ID@>0 | @AD_Workflow_ID@>0",
			"@AD_Window_ID@>0 | @AD_Process_ID@>0 | @AD_Form_ID@>0 | @AD_Task_ID@>0",
			"@AD_Workflow_ID@>0 | @AD_Process_ID@>0 | @AD_Form_ID@>0 | @AD_Task_ID@>0",
			"@AllFields@=N",
			"@AnyAcct@=N",
			"@AnyOrg@=N",
			"@AssetAccumDepreciationAmt@!\"\"",
			"@AssetBookValueAmt@!\"\"",
			"@AssetDepreciationDate@!\"\"",
			"@AssetDisposalDate@!\"\"",
			"@AssetMarketValueAmt@!\"\"",
			"@AssetServiceDate@!\"\"",
			"@AssetValueAmt@!\"\"",
			"@AttributeValueType/-@=L",
			"@AttributeValueType@ = 'L'",
			"@AttributeValueType@=L",
			"@AttributeValueType@=N",
			"@AutoPeriodControl@='Y'",
			"@BinaryData@!''",
			"@BOMProductType@=D | @BOMProductType@=A",
			"@BOMType@!O",
			"@BOMType@=O",
			"@BOMUse@='P'",
			"@BPAccessType@=D",
			"@BPAccessType@=R",
			"@C_Bank_ID@=0",
			"@C_BP_Group_ID@!0",
			"@C_Bpartner_ID@!0",
			"@C_BPartner_ID@!0",
			"@C_BPartner_Location_ID@!0",
			"@C_BPartner_Override_ID@!0",
			"@C_Charge_ID@!0",
			"@C_Charge_ID@=0",
			"@C_Currency_ID@ ! @$C_Currency_ID@",
			"@C_Currency_ID@!@$C_Currency_ID@",
			"@C_DocType_ID@!0",
			"@C_DocTypeTarget_ID@=1000004",
			"@C_DocTypeTarget_ID@=1000027",
			"@C_DocTypeTarget_ID@=1000027&@Ref_Proposal_ID@=0&@DocStatus@='CO'",
			"@C_Flatrate_Term_ID@ > 0",
			"@C_FlatrateTerm_Next_ID@!0",
			"@C_Invoice_Candidate_Corr_ID@!0",
			"@C_Invoice_ID/0@=0",
			"@C_Invoice_ID@!0",
			"@C_Invoice_ID@!0 & @IsMultiplePaymentOrInvoice@='N' |  @C_Order_ID@!0",
			"@C_Invoice_ID@!0 | @C_Charge_ID@!0",
			"@C_Invoice_ID@!0 | @C_Order_ID@!0",
			"@C_Invoice_ID@!0 | @C_Payment_ID@!0",
			"@C_Invoice_ID@<1",
			"@C_Invoice_ID@=0",
			"@C_Location_ID@!0",
			"@C_Order_ID@!0",
			"@C_Order_ID@!0 | @C_Charge_ID@!0",
			"@C_Order_ID@=0",
			"@C_Order_ID@>0",
			"@C_Order_Term_ID@!0",
			"@C_OrderLine_ID@!0",
			"@C_OrderLine_MTO_ID/0@>0",
			"@C_OrderLine_Term_ID@!0",
			"@C_OrderLine_TermChange_ID@!0",
			"@C_Payment_ID@!0",
			"@C_Payment_ID@!0 | @Processed@='N'",
			"@C_Payment_ID@=0",
			"@C_Payment_ID@=0  & @IsMultiplePaymentOrInvoice@='N'",
			"@C_Payment_ID@=0 | @C_Invoice_ID@=0",
			"@C_PrepayOrder_ID@!0",
			"@C_PrepayOrder_ID@=0",
			"@C_Project_ID@!'' | @C_Project_ID@!0",
			"@C_RfQLineQty_ID/-1@ > 0",
			"@C_Tax_ID@ = 100",
			"@CashType@=C",
			"@CashType@=I",
			"@CashType@=I & @IsGenerated@=N",
			"@CashType@=T",
			"@ChangeAmt@!\"\"",
			"@ChangeType@=\"CRT\"|@ChangeType@=\"UPD\"|@ChangeType@=\"IMP\"",
			"@ChargeAmt@!0",
			"@ChargeFee@='Y'",
			"@ChargeInterest@='Y'",
			"@ColorType@=G",
			"@ColorType@=G | @ColorType@=L",
			"@ColorType@=L",
			"@ColorType@=P",
			"@ColumnType@ = 'A'",
			"@ColumnType@ = 'A' & @Type@! 'E'",
			"@ColumnType@ = 'D'",
			"@ColumnType@ = 'Q'",
			"@ColumnType@ = 'Q'  & @Type@! 'E'",
			"@ColumnType@ = 'R'",
			"@ColumnType@ = 'T'",
			"@ColumnType@=C",
			"@ColumnType@=R",
			"@ColumnType@=S",
			"@ColumnType@=T",
			"@ContactLimitation@!'A'  & @ContactLimitation@!''",
			"@ContainerType@=L & @IsSummary@=N",
			"@ContainerType@=U & @IsSummary@=N",
			"@ContractStatus@ = 'Qu'",
			"@ConventionType@!\"\"",
			"@CostingMethod@!S",
			"@CostingMethod@!x & @CostingMethod@!S",
			"@CostingMethod@=F | @CostingMethod@=I | @CostingMethod@=L",
			"@CostingMethod@=S",
			"@CostingMethod@=x",
			"@CR_AutoTaxAccount@=Y",
			"@CreditCardType@=P & @IsOnline@=Y",
			"@DataType@!C",
			"@DataType@!C & @FormatType@=F",
			"@DataType@=C",
			"@DataType@=D",
			"@DataType@=N",
			"@DateAcct@!\"\"",
			"@DateLastRun@!''",
			"@DeliveryViaRule@='S'",
			"@DeliveryViaRule@='S' & @FreightCostRule@='F'",
			"@DeliveryViaRule@='S' & @OrderType@='SO'",
			"@DeliveryViaRule@='Y' ",
			"@DeliveryViaRule@=S",
			"@DepreciationType@!\"\"",
			"@DepreciationType@=1000005|@DepreciationType@=1000010",
			"@DepreciationType@=1000006",
			"@DepreciationType@=1000006|@DepreciationType@=1000007",
			"@DepreciationType@=1000007",
			"@DirectShip@='N'",
			"@DirectShip@='N' & @OrderType@='OB' | @OrderType@='SO'",
			"@DirectShip@='N' & @OrderType@='OB' | @OrderType@='SO' | @Processed@='Y'",
			"@Discontinued@='Y'",
			"@DiscountType/X@=B",
			"@DiscountType/X@=B & @BreakValueType/X@=T",
			"@DiscountType@=B",
			"@DiscountType@=F",
			"@DiscountType@=F & @IsBPartnerFlatDiscount@=N",
			"@DiscountType@=P",
			"@DiscountType@=P & @Limit_Base@!F",
			"@DiscountType@=P & @Limit_Base@=F",
			"@DiscountType@=P & @List_Base@!F",
			"@DiscountType@=P & @List_Base@=F",
			"@DiscountType@=P & @Std_Base@!F",
			"@DiscountType@=P & @Std_Base@=F",
			"@DiscountType@=S",
			"@DocBaseType@='ARC'",
			"@DocBaseType@='MMM'",
			"@DocBaseType@='MMR' | @DocBaseType@='MMS'",
			"@DocBaseType@='SOO'",
			"@DocBaseType@='SOO' & @HasProforma@='Y'",
			"@DocBaseType@='SOO' | @DocBaseType@='POO'",
			"@DocBaseType@='SOO' | @DocBaseType@='POO' | @DocBaseType@='ARI' | @DocBaseType@='ARC' | @DocBaseType@='MOP' | @DocBaseType@='MMR' | @DocBaseType@='MMS' | @DocBaseType@='API' | @DocBaseType@='MMI' | @DocBaseType@ = 'APC'",
			"@DocBaseType@='SOO' | @DocBaseType@='POO' | @DocBaseType@='MMR' | @DocBaseType@='MMS' | @DocBaseType@='API' | @DocBaseType@='APC' | @DocBaseType@='ARI' | @DocBaseType@='ARC'",
			"@DocBaseType@='SOO' | @DocBaseType@='POO' | @DocBaseType@='MMR' | @DocBaseType@='MMS' | @DocBaseType@='API' | @DocBaseType@='APC' | @DocBaseType@='ARI' | @DocBaseType@='ARC' | @DocBaseType@='ARR' | @DocBaseType@='APP'",
			"@DocBaseType@=SOO | @DocBaseType@=POO | @DocBaseType@=ARI | @DocBaseType@=ARC | @DocBaseType@=API | @DocBaseType@=ARC",
			"@DocStatus@ ! CO & @DocStatus@ ! CL",
			"@DocStatus@!=CO",
			"@DocStatus@!CO",
			"@DocStatus@='CO'&@C_FlatrateTerm_Next_ID@=0",
			"@DocStatus@=CO | @DocStatus@=CL & @IsEdiEnabled@=Y",
			"@DocStatus@=CO | @DocStatus@=CL & @IsEdiEnabled@=Y & @EDI_Desadv_ID@>0",
			"@DR_AutoTaxAccount@=Y",
			"@EDI_Desadv_ID@!0",
			"@EDI_ExportStatus@!E & @EDI_ExportStatus@!I",
			"@EDI_ExportStatus@!P & @EDI_ExportStatus@!E & @EDI_ExportStatus@!I",
			"@EDI_ExportStatus@!P & @EDI_ExportStatus@!E & @EDI_ExportStatus@!I  | @EDI_DESADV_SumPercentage@ < @EDI_DESADV_MinimumSumPercentage@",
			"@EDI_ExportStatus@='E'",
			"@EDI_ExportStatus@='E' & @IsEdiEnabled@='Y'",
			"@ElementType@!U",
			"@ElementType@='AC' | @ElementType@='U1' | @ElementType@='U2'",
			"@ElementType@='AY'",
			"@ElementType@='BP'",
			"@ElementType@='LF' | @ElementType@='LT'",
			"@ElementType@='MC'",
			"@ElementType@='OO' | @ElementType@='OT'",
			"@ElementType@='PJ'",
			"@ElementType@='PR' ",
			"@ElementType@='SR' ",
			"@ElementType@='X1' | @ElementType@='X2'",
			"@ElementType@=A",
			"@ElementType@=A & @IsSummary@='N'",
			"@ElementType@=A & @IsSummary@=N",
			"@ElementType@=A & @IsSummary@=N & @IsBankAccount@=Y",
			"@ElementType@=AC | @ElementType@=U1 | @ElementType@=U2 | @ElementType@=CO",
			"@ElementType@=AY | @ElementType@=CO",
			"@ElementType@=BP | @ElementType@=CO",
			"@ElementType@=CO",
			"@ElementType@=CO & @$Element_X1@=Y",
			"@ElementType@=CO & @$Element_X2@=Y",
			"@ElementType@=LF | @ElementType@=LT | @ElementType@=CO",
			"@ElementType@=MC | @ElementType@=CO",
			"@ElementType@=OO | @ElementType@=OT | @ElementType@=CO",
			"@ElementType@=PJ | @ElementType@=CO",
			"@ElementType@=PR | @ElementType@=CO",
			"@ElementType@=SR | @ElementType@=CO",
			"@ElementType@=U",
			"@EMail_To@!''",
			"@ErrorMsg@ =''  | @C_Payment_ID@ > 0 | @ESR_Payment_Action@ = 'R'",
			"@ErrorMsg@!''",
			"@ESR_Document_Status@!'T'",
			"@ESR_IsManual_ReferenceNo@='N'",
			"@ESR_Payment_Action@ = F | @ESR_Payment_Action@ = C  | @C_Payment_ID@ < 1 | @Processed@ = Y"
					+ "\n| (@ESR_Payment_Action@ = A & @ESR_Invoice_Openamt@ = 0) ",
			"@EventType@='DE'",
			"@EventType@=DE",
			"@ExtensionType/None@='EA' | @ExtensionType/None@='EO'",
			"@FieldGroupType@='C'",
			"@FreightCostRule@!'F'",
			"@FreightCostRule@='F'",
			"@FreightCostRule@='L'",
			"@FrequencyType@='M'",
			"@GoalRestrictionType@=B",
			"@GoalRestrictionType@=C",
			"@GoalRestrictionType@=G",
			"@GoalRestrictionType@=O",
			"@GoalRestrictionType@=P",
			"@GraphType@!P",
			"@GroupBy@='N' | @AD_Reference_OLCand_ID@=10 | @AD_Reference_OLCand_ID@=18 | @AD_Reference_OLCand_ID@=19 | @AD_Reference_OLCand_ID@=20 | @AD_Reference_OLCand_ID@=30",
			"@HasCharges@='Y'",
			"@HasContracts/N@='N'",
			"@HasPostal_Add@=Y",
			"@HasRegion@='Y'",
			"@HasRegion@=Y",
			"@HR_Concept_ID@!0",
			"@ImageIsAttached@='N'",
			"@ImageURL@!''",
			"@Included_Tab_ID@!0",
			"@Incoterm@!''",
			"@InventoryType@=C",
			"@InvoiceFrequency@!T",
			"@InvoiceFrequency@=B",
			"@InvoiceFrequency@=M",
			"@InvoiceFrequency@=W",
			"@InvoiceRule@='S'",
			"@InvoiceScheduleAmtStatus/@!'OK'",
			"@InvoiceScheduleAmtStatus@!'OK'",
			"@Is_AD_User_InCharge_UI_Setting@='Y'",
			"@IsAccessAllOrgs@=N",
			"@IsACH@=N",
			"@IsACH@=Y",
			"@IsACH@=Y & @C_Bank_ID@=0",
			"@IsADRCustomer@ = Y",
			"@IsADRVendor@ = Y",
			"@IsAllNodes@=Y",
			"@IsAllowAccountCR@=N",
			"@IsAllowAccountCR@=N | @Type@=T",
			"@IsAllowAccountDR@=N",
			"@IsAllowAccountDR@=N | @Type@=T",
			"@IsAllowAnyProduct@='N'",
			"@IsAllowAnyProduct@=N",
			"@IsAmount@='Y'",
			"@IsApproved@=Y",
			"@IsAttributeDependant/N@=Y",
			"@IsAttributeDependant@=Y",
			"@IsAutoResetEnabled@ = Y",
			"@IsAutoSequence@='N'",
			"@IsAutoSequence@=Y",
			"@IsAutoSequence@=Y & @IsTableID@=N",
			"@IsAutoSequence@=Y & @IsTableID@=N & @StartNewYear@=Y",
			"@IsAutoTaxAccount@=Y",
			"@IsBaseLanguage@=N",
			"@IsBillToDefault@='Y'",
			"@IsBOM@='Y'",
			"@IsBPartnerAddress_Override@='N'",
			"@IsBPartnerFlatDiscount@=N",
			"@IsCalculated@=Y",
			"@IsCancelDeliveryDay@='Y'",
			"@IsClosed@=Y",
			"@IsClosingWithActualSum@='Y'",
			"@IsClosingWithActualSum@='Y' & @Type_Conditions@='FlatFee' & @Type_Flatrate/'NONE'@!'NONE'",
			"@IsClosingWithActualSum@='Y'&@Type_Conditions@='FlatFee'",
			"@IsClosingWithActualSum@='Y'&@Type_Flatrate@!'NONE'",
			"@IsClosingWithActualSum@='Y'&@Type_Flatrate@!'NONE'&@Type_Conditions@='FlatFee'",
			"@IsClosingWithCorrectionSum@='Y' & @DocStatus@='CO'",
			"@IsClosingWithCorrectionSum@='Y'&@IsClosingWithActualSum@='Y'&@Type_Flatrate@!'NONE'&@Type_Conditions@='FlatFee'",
			"@IsClosingWithCorrectionSum@='Y'&@Type_Conditions@='FlatFee'",
			"@IsComment@=N",
			"@IsComment@=N & @$Element_AY@='Y'",
			"@IsComment@=N & @$Element_MC@='Y'",
			"@IsComment@=N & @$Element_OT@=Y",
			"@IsComment@=N & @$Element_PJ@='Y'",
			"@IsComment@=N & @$Element_U1@='Y'",
			"@IsComment@=N & @$Element_U2@='Y'",
			"@IsComment@=N & @DeliveryViaRule@='S'",
			"@IsComment@=N & @FreightCostRule@='L'",
			"@IsComment@=N & @IsComment@=N",
			"@IsComment@=N & @OrderType@='OB' | @OrderType@='SO' | @OrderType@='WP'",
			"@IsComment@=N & @Processed@=Y",
			"@IsCommitment@=Y",
			"@IsCompany/N@=N",
			"@IsCompany@='Y'",
			"@IsCompany@=Y",
			"@IsCreateCounter@=Y",
			"@IsCreateDefaultPOReference@='Y'",
			"@IsCreateNew/N@=Y",
			"@IsCreateSingleOrder@=Y",
			"@IsCustomer@ = 'N'",
			"@IsCustomer@='Y'",
			"@IsCustomer@=Y",
			"@IsDateFactOverridable@='N'",
			"@IsDateSlot@=Y",
			"@IsDisposed@=Y",
			"@IsDocNoControlled@='Y'",
			"@IsDocNoControlled@='Y' & @IsOverwriteSeqOnComplete@='Y'",
			"@IsDropShip/'N'@='Y'",
			"@IsDropShip@='Y'",
			"@IsDropShip@=N",
			"@IsDropShip@=Y",
			"@IsDropShip@=Y'",
			"@IsDueFixed@='N'",
			"@IsDueFixed@='Y'",
			"@IsDynamic@=Y",
			"@IsEdiEnabled@='Y'",
			"@IsEdiEnabled@='Y' & (@DocStatus@='CO' | @DocStatus@='CL' )",
			"@IsEdiRecipient/N@ = N",
			"@IsEdiRecipient/N@=N",
			"@IsEdiRecipient@ = N",
			"@IsEdiRecipient@=N",
			"@IsEdiRecipient@=Y",
			"@IsEmployee@ ! Y",
			"@IsEmployee@!Y",
			"@IsEmployee@='N'",
			"@IsEmployee@='Y'",
			"@IsEmployee@= 'Y'",
			"@IsEmployee@=N",
			"@IsEMUMember@=N",
			"@IsEMUMember@=Y",
			"@IsError@='N'",
			"@IsError@='Y'",
			"@IsError@=Y",
			"@IsEsrAccount@=Y",
			"@IsExcludedFromSale/N@=Y",
			"@IsExcludedFromSale@ = 'Y'",
			"@IsExportXMLBackup@=Y",
			"@IsForAllDistribution@=N",
			"@IsForAllDistribution@=N&@IsSameDistribution@=N",
			"@IsForAllDistribution@=Y",
			"@IsForAllDistribution@=Y|@IsSameDistribution@=Y",
			"@IsForm@=N & @IsNextLine@=Y",
			"@IsForm@=N & @PrintFormatType@=F",
			"@IsForm@=Y",
			"@IsForm@=Y & @IsRelativePosition@=N",
			"@IsForm@=Y & @IsRelativePosition@=Y",
			"@IsForm@=Y & @IsStandardHeaderFooter@=N",
			"@IsGenerateComparation/N@=Y",
			"@IsGenerated@=Y",
			"@IsGenericZoomOrigin@='Y'",
			"@IsGroupBy/N@=N",
			"@IsGroupCompensationLine@=Y",
			"@IsGuaranteeDate@=Y",
			"@IsIdentifier@=Y",
			"@IsIndividualDescription@='Y'",
			"@IsInfiniteCapacity@=N",
			"@IsInfiniteCapacity@=Y",
			"@IsInPosession@=N",
			"@IsInPosession@=Y",
			"@IsInvoiced@=Y",
			"@IsKey@=Y | @IsParent@=Y | @IsIdentifier@=Y | @IsEncrypted@=Y | @IsTranslated@=Y | @ColumnName@=AD_Client_ID | @ColumnName@=AD_Client_ID | @ColumnName@=AD_Org_ID | @ColumnName@=IsActive | @ColumnName@=Created | @ColumnName@=Updated | @ColumnName@=DocumentNo",
			"@IsLot@=Y",
			"@IsManageDunnableDocGraceDate@='Y'",
			"@IsManual@ = 'N'",
			"@IsManual@='N'",
			"@IsManual@='Y'",
			"@IsManual@='Y'|@Description/@!''",
			"@IsManual@=N",
			"@IsManual@=Y",
			"@IsManual_IPA_SSCC18@='N'",
			"@IsManualCalibration@='N'",
			"@IsManualDiscount@='Y'",
			"@IsManualRank@='N'",
			"@IsManufactured@='Y'",
			"@IsManufacturingResource@='Y' & @ManufacturingResourceType@='PT'",
			"@IsMenuAvailable@=Y",
			"@IsMFProcurementUser/N@=Y",
			"@IsMonthly@='N' & @EveryMonth@=0",
			"@IsMonthly@='N' & @IsWeekly@='N' & @EveryWeek@=0",
			"@IsMoveDeliveryDay@='Y'",
			"@IsMultiLine/N@=Y",
			"@IsMultiplePayment@='N' | @IsMultiplePaymentOrInvoice@='N'",
			"@IsMultiplePayment@='Y'",
			"@IsMultiplePaymentOrInvoice@='N'",
			"@IsMultiplePaymentOrInvoice@='Y'",
			"@IsMultiplePaymentOrInvoice@='Y' | @C_Payment_ID@!0",
			"@IsOfferQty@=Y",
			"@IsOneInstanceOnly@=Y",
			"@IsOnline@=Y",
			"@IsOrderLineReadOnly@=N",
			"@IsOrderLineReadOnly@=Y",
			"@IsOverUnderPayment@='Y'",
			"@IsOverUnderPayment@=Y & @C_Invoice_ID@!0",
			"@IsOwned@=N & @IsInPosession@=Y",
			"@IsOwned@=Y",
			"@IsOwned@=Y & @IsDepreciated@=Y",
			"@IsPackagingMaterial@=N",
			"@IsPackagingMaterial@=N & @IsManualPackingMaterial@=N & @IsManual@ = N",
			"@IsPackagingMaterial@=Y",
			"@IsPackagingMaterial@=Y | @IsManualPackingMaterial@=N",
			"@IsPaidTo3Party@='Y'",
			"@IsPaintHeaderLines@=Y",
			"@IsPercentWithholding@='N'",
			"@IsPercentWithholding@='Y'",
			"@IsPickQAConfirm@=Y | @IsShipConfirm@=Y",
			"@IsPostcodeLookup@ = 'Y'",
			"@IsPriceEditable@!Y",
			"@IsPurchaseContact@ = 'N'",
			"@IsPurchaseContact@ = 'Y'",
			"@IsPurchased@=N",
			"@IsQtyPercentage@ = N",
			"@IsQtyPercentage@ = Y",
			"@IsQtyReadOnly@=Y",
			"@IsQueryCriteria@='Y'",
			"@IsQueryCriteria@=Y",
			"@IsRange@=Y",
			"@IsReadOnly@=N",
			"@IsReadOnlyValues@=Y",
			"@IsReadyForInvoicing@='Y'",
			"@IsRelativePosition@=Y",
			"@IsRepeat/N@=Y",
			"@IsReport@='Y'",
			"@IsReport@=N",
			"@IsReport@=Y",
			"@IsRouting@='N'",
			"@IsSalesContact@ = 'N'",
			"@IsSalesContact@ = 'Y' ",
			"@IsSalesRep@ = 'Y'",
			"@IsSalesRep@='Y'",
			"@IsSelectionColumn@=Y",
			"@IsSendNotification@='N'",
			"@IsSendNotification@='Y'",
			"@IsSerNo@=Y",
			"@IsServerProcess@=Y",
			"@IsSetPaymentTerm@=Y",
			"@IsSharedPrinterConfig@='N'",
			"@IsShipToDefault@='Y'",
			"@IsSimulation@='N'",
			"@IsSimulation@=N",
			"@IsSmtpAuthorization@=Y",
			"@IsSold@='Y'",
			"@IsSortTab@=N",
			"@IsSortTab@=Y",
			"@IsSOTrx@='Y'",
			"@IsSOTrx@=Y",
			"@IsSplitWhenDifference@=Y",
			"@IsStaled@=Y",
			"@IsSubcontracting@='Y'",
			"@IssueMethod@=1",
			"@IssueSource@=R | @IssueSource@=P",
			"@IssueSource@=W",
			"@IssueSource@=X",
			"@IsSummary@='N'",
			"@IsSummary@='N' & @Discontinued@='Y'",
			"@IsSummary@='N' & @IsBOM@='Y'",
			"@IsSummary@='N' & @IsBOM@='Y' & @IsVerified@='N'",
			"@IsSummary@='N' & @ProductType@=I",
			"@IsSummary@='N' & @ProductType@=I & @IsStocked@=Y",
			"@IsSummary@='N' & @ProductType@=I | @ProductType@=S",
			"@IsSummary@=N",
			"@IsSummary@=N & @$Element_MC@=Y",
			"@IsSummary@=N & @IsCommitment@=Y",
			"@IsSummary@=N & @MediaType@!CSS",
			"@IsSummary@=N & @MediaType@=CSS",
			"@IsSummary@=N & @ProductType@=I & @IsStocked@=Y",
			"@IsSystemUser@ = 'Y'",
			"@IsSystemUser@=Y",
			"@IsTableID@=N",
			"@IsTableRecordIdTarget @='N'",
			"@IsTableRecordIdTarget @='Y'",
			"@IsTemporaryExempt@='Y'",
			"@IsTimeBased@=Y",
			"@IsTimeReport@=N | @IsInvoiced@=Y",
			"@IsTimeReport@=Y & @IsInvoiced@=N",
			"@IsTimeSlot@=Y",
			"@IsToClear@='N'",
			"@IsUpdateable@=Y",
			"@IsUseBillToAddress@='N'",
			"@IsUseBPartnerAddress@='N'",
			"@IsUseDeliveryToAddress@='N'",
			"@IsUseHandOver_Location@='Y'",
			"@IsValid/X@=N",
			"@IsValid@=N",
			"@IsValueAggregate@='Y'",
			"@IsVendor@='Y'",
			"@IsVendor@=Y",
			"@IsView@='N' ",
			"@IsWebCanUpdate@=Y",
			"@IsWeekly@='N' & @EveryWeek@=0",
			"@IsWeekly@='N' & @IsMonthly@='N' & @EveryMonth@=0",
			"@IsXYPosition@=Y",
			"@ItemType@ = HU",
			"@ItemType@ = PM",
			"@ItemType@=PM",
			"@JasperProcess_ID@>0",
			"@LabelFormatType@=F",
			"@LabelFormatType@=T",
			"@LifeUseUnits@!\"\"",
			"@LineType@=C",
			"@LineType@=I",
			"@LineType@=S",
			"@ListSources@=Y",
			"@LockedBy@!\"\"",
			"@Lot@!\"\"",
			"@M_HU_PI_Item_Product_ID@ = 101",
			"@M_HU_PI_Item_Product_ID@!0 & @IsInfiniteCapacity@='N'",
			"@M_InOutLine_ID@!0",
			"@M_Inventory_ID@ = 0",
			"@M_PriceList_Version_ID/0@!0",
			"@M_PriceList_Version_ID@!0",
			"@M_Product_Category_ID@!0",
			"@M_Product_ID/0@ ! 0 & @QtyOrdered@ ! 0",
			"@M_Product_ID/0@=0 | @QtyOrdered@=0 | @QtyProvided@ ! 0",
			"@M_Product_ID@!0",
			"@M_Product_ID@=0",
			"@M_Product_Override_ID@!0",
			"@M_ProductOperation_ID@!0",
			"@M_RMA_ID@!0",
			"@M_Warehouse_ID@!0",
			"@ManufacturingResourceType@=PT",
			"@MeasureType@=C",
			"@MeasureType@=M",
			"@MeasureType@=P",
			"@MeasureType@=Q",
			"@MeasureType@=R",
			"@MeasureType@=U",
			"@MovementType@='C-' ",
			"@MovementType@='C+'",
			"@MovementType@='V-'",
			"@NotificationType@='O'",
			"@OldName@!'",
			"@OnFriday@='N'",
			"@OnMonday@='N'",
			"@OnSaturday@='N'",
			"@OnSunday@='N'",
			"@OnThursday@='N'",
			"@OnTuesday@='N'",
			"@OnWednesday@='N'",
			"@Operation@=AB",
			"@OrderType@!'SO'|@QtyReserved@>0",
			"@OrderType@='OB' | @OrderType@='SO'",
			"@OrderType@='OB' | @OrderType@='SO' | @OrderType@='WP'",
			"@OrderType@='OB' | @OrderType@='SO' | @Processed@='Y'",
			"@OrderType@='SO'",
			"@OrderType@='SO' ",
			"@OrderType@='SO' & @FreightCostRule@='F'",
			"@OrderType@='SO' &@IsDiverse@=N",
			"@OrderType@='SO' | @OrderType@='PO'",
			"@OrderType@='SO' | @OrderType@='WP'",
			"@OrderType@='SO' | @OrderType@='WP' | @OrderType@='PM'",
			"@OrderType@='SO' | @Processed@=Y",
			"@OrderType@='WP'",
			"@OrderType@=ON | @OrderType@=OB",
			"@OverwriteAcct@=Y",
			"@OverwriteOrg@=Y",
			"@PA_Goal_ID@!0",
			"@PaymentRule@='P'",
			"@PaymentRule@='P' | @PaymentRule@='D'",
			"@PaymentRule@='P' | @PaymentRule@='D' | @PaymentRule@='K'",
			"@POSKeyLayoutType@!'P'",
			"@POSKeyLayoutType@='G'",
			"@POSKeyLayoutType@='P'",
			"@PostingType@='B'",
			"@PostingType@=B",
			"@PriceActual@!null",
			"@PriceBase@ = F",
			"@PriceBase@ = P",
			"@PriceBase@ = P ",
			"@PrintFormatType@!P",
			"@PrintFormatType@=F",
			"@PrintFormatType@=F & @IsForm@=Y",
			"@PrintFormatType@=F & @IsGroupBy@=Y",
			"@PrintFormatType@=F & @IsOrderBy@=Y",
			"@PrintFormatType@=F & @IsRunningTotal@=Y & @IsSummarized@=Y",
			"@PrintFormatType@=F & @IsSummarized@=Y",
			"@PrintFormatType@=F | @PrintFormatType@=T",
			"@PrintFormatType@=F | @PrintFormatType@=T | @PrintFormatType@=R | @PrintFormatType@=L",
			"@PrintFormatType@=F|@PrintFormatType@=T",
			"@PrintFormatType@=I",
			"@PrintFormatType@=I & @ImageIsAttached@=N & @IsImageField@=N",
			"@PrintFormatType@=I & @IsImageField@=N",
			"@PrintFormatType@=L",
			"@PrintFormatType@=P",
			"@PrintFormatType@=P | @PrintFormatType@=F | @IsImageField@=Y",
			"@PrintFormatType@=R",
			"@PrintFormatType@=R & @ShapeType@=R",
			"@PrintQty@=N",
			"@Processed@ = 'Y'",
			"@Processed@ = 'Y' | @ESR_Payment_Action@ = 'R'",
			"@Processed@='Y'",
			"@Processed@='Y' & @C_Order_ID@=0 & @DocStatus@='CO' & @IsSOTrx@='N'",
			"@Processed@='Y' & @C_Order_ID@=0 & @DocStatus@='CO' & @IsSOTrx@='Y'",
			"@Processed@=Y",
			"@Processed@=Y & @#ShowAcct@=Y",
			"@Processing@ = Y",
			"@ProcessType/None@='DR'",
			"@ProcessType@='DR'",
			"@ProductType@='R'",
			"@ProductType@=E",
			"@ProductType@=R",
			"@ProductType@=R | @ProductType@=E | @ProductType@=O",
			"@ProductType@=R | @ProductType@=O",
			"@ProductTypeType@=E",
			"@ProjInvoiceRule@=P",
			"@PropagationType@='BOTU' | @PropagationType@='IVAL'",
			"@PropagationType@='TOPD' | @PropagationType@='IVAL'",
			"@Qty@!0",
			"@Qty@=0",
			"@Qty@=1",
			"@QtyEntered@>@QtyDeliveredInUOM@",
			"@QuoteType@!T",
			"@QuoteType@=A",
			"@R_Group_ID@!0",
			"@R_MailText_ID@=0 & @W_MailMsg_ID@=0",
			"@R_RequestType_InternalName/-1@ !'A_CustomerComplaint' & @R_RequestType_InternalName/-1@ ! 'B_VendorComplaint'",
			"@R_RequestType_InternalName/-1@ !'A_CustomerComplaint' & @R_RequestType_InternalName/-1@ ! 'B_VendorComplaint' & @R_RequestType_InternalName/-1@ ! 'C_ConsumerComplaint'",
			"@R_RequestType_InternalName/-1@ ='A_CustomerComplaint' | @R_RequestType_InternalName/-1@ = 'B_VendorComplaint' | @R_RequestType_InternalName/-1@ = 'C_ConsumerComplaint'",
			"@R_Resolution_ID@!0",
			"@RatioElementType@=A",
			"@RatioElementType@=C",
			"@RatioElementType@=R",
			"@RatioElementType@=X",
			"@ReceiptPermissionPharma@='B'",
			"@Record_ID@!0",
			"@Record_ID@=0",
			"@RecurringType@=G",
			"@RecurringType@=I",
			"@RecurringType@=J",
			"@RecurringType@=O",
			"@RecurringType@=P",
			"@Ref_AdjustmentCharge_ID@=0&@DocStatus@='CO'& (@C_DocTypeTarget_ID@=1000002 | @C_DocTypeTarget_ID@=1000003 | @C_DocTypeTarget_ID@=540899  | @C_DocTypeTarget_ID@=540900)",
			"@Ref_CreditMemo_ID@=0&@DocStatus@='CO'&@C_DocTypeTarget_ID@=1000002 | @C_DocTypeTarget_ID@=1000003 | @C_DocTypeTarget_ID@=1000049 | @C_DocTypeTarget_ID@=1000056",
			"@Ref_Invoice_ID@!0",
			"@Ref_Order_ID@!0",
			"@Ref_Proposal_ID@!0",
			"@Ref_Proposal_ID@!0&@C_DocTypeTarget_ID@=1000027",
			"@RefundBase/P@='F'",
			"@RefundBase/P@='P'",
			"@ReplenishType@=7",
			"@ReplicationType@!L",
			"@ResponsibleType@=H",
			"@ResponsibleType@=R",
			"@Reversal_ID/0@!0",
			"@Reversal_ID@!0",
			"@Reversal_ID@>0",
			"@ReversalLine_ID/0@>0",
			"@RewardMode@=CH",
			"@RfQType@=P",
			"@RoutingType@ ! L",
			"@RoutingType@ ! P",
			"@RoutingType@ = L",
			"@RoutingType@ = P",
			"@RuleType@=Q",
			"@S_ResourceAssignment_ID@!0",
			"@S_ResourceAssignment_ID@>0 | @C_Charge_ID@>0 | @IsGroupCompensationLine/N@=Y",
			"@Salesgroup/''@ ! ''",
			"@SalesRep_Min_Rank_ID@!0",
			"@SchedulerProcessType@=P | @SchedulerProcessType@=R",
			"@SchedulerProcessType@=T",
			"@ScheduleType@=C",
			"@ScheduleType@=F",
			"@ScheduleType@=M",
			"@ScheduleType@=W",
			"@SearchType@ = Q",
			"@SearchType@ = T",
			"@Serno@!\"\"",
			"@ShipmentPermissionPharma@='B'",
			"@ShowIntCurrency@ = 'Y'",
			"@StartNewYear@=Y",
			"@Status@!P",
			"@Status@!P | @EventType@!DE",
			"@Status@=STARTED",
			"@StepType@='AD'",
			"@StepType@='SQL'",
			"@StoreArchiveOnFileSystem@='Y'",
			"@StoreAttachmentsOnFileSystem@='Y'",
			"@T_Integer@=0",
			"@TenderType@ !'X' | @#CashAsPayment@=Y",
			"@TenderType@='X'",
			"@TenderType@=A | @TenderType@=K",
			"@TenderType@=C",
			"@TenderType@=C | @TenderType@=K",
			"@TenderType@=K",
			"@TenderType@=K & @IsOnline@=Y",
			"@TimeoutDays@!0",
			"@TreeType@=XX",
			"@Type/-@=F",
			"@Type/-@=R",
			"@Type/none@='tooltip'",
			"@Type@ ! 'J'",
			"@Type@ = 'J'",
			"@Type@! 'E'",
			"@Type@!Java",
			"@Type@='E'",
			"@Type@='E' | @Type@='A' | @Type@='R'",
			"@Type@='E' | @Type@='R'",
			"@Type@='IP' | @Type@='CP'",
			"@Type@='M' | @Type@='R'",
			"@Type@='P'",
			"@Type@=A",
			"@Type@=ATR",
			"@Type@=COL",
			"@Type@=CV",
			"@Type@=FV",
			"@Type@=FV | @Type@=CV",
			"@Type@=INC",
			"@Type@=JasperReports",
			"@Type@=P",
			"@Type@=R",
			"@Type@=S",
			"@Type@=SQL | @Type@=Excel | @Type@=JasperReports",
			"@Type@=SV",
			"@Type@=SV & @IsNullFieldValue@=N",
			"@Type_Conditions/'FlatFee'@='FlatFee'",
			"@Type_Conditions@!'FlatFee'",
			"@Type_Conditions@!'FlatFee' & @Type_Conditions@!'HoldingFee' & @Type_Conditions@!'Procuremnt' & @Type_Conditions@!'Refund'",
			"@Type_Conditions@!'Procuremnt'",
			"@Type_Conditions@!'Refund'",
			"@Type_Conditions@!'Refundable' & @Type_Conditions@!'Refund'",
			"@Type_Conditions@!'Subscr' & @Type_Conditions@!'Refund'",
			"@Type_Conditions@='FlatFee'",
			"@Type_Conditions@='FlatFee' & @Type_Flatrate/'NONE'@!'NONE'",
			"@Type_Conditions@='FlatFee' | @Type_Conditions@='HoldingFee'",
			"@Type_Conditions@='FlatFee'|@Type_Conditions@='Subscr'",
			"@Type_Conditions@='HoldingFee'",
			"@Type_Conditions@='Procuremnt' | @Type_Conditions@='Subscr' | @Type_Conditions@='Refund'",
			"@Type_Conditions@='QualityBsd'",
			"@Type_Conditions@='Subscr'",
			"@Type_Conditions@='Subscr'  | @Type_Conditions@='Refundable'",
			"@Type_Conditions@='Subscr' | @Type_Conditions@='Refund'",
			"@Type_Conditions@='Subscr' | @Type_Conditions@='Refundable'  | @Type_Conditions@='Procuremnt'",
			"@Type_Conditions@='Subscr'|@Type_Conditions@='QualityBsd'|@Type_Conditions@='Procuremnt'|@Type_Conditions@='Refund'",
			"@Type_Conditions@=Procuremnt",
			"@Type_Flatrate@='LIPE'",
			"@UseCurrencyBalancing@='Y'",
			"@UsedForCustomer@ = 'Y'",
			"@UsedForCustomer@=N",
			"@UsedForCustomer@=Y",
			"@UseLifeMonths@!\"\"",
			"@UseLifeYears@!\"\"",
			"@UseLineQty/N@=N",
			"@UserFlag@!''",
			"@UseScalePrice@=Y",
			"@UseSuspenseBalancing@='Y'",
			"@UseSuspenseError@='Y'",
			"@UseUnits@!\"\"",
			"@ValidationType@=L",
			"@ValidationType@=T",
			"@Versionno@!\"\"",
			"@WorkflowType/None@!'M' | @WorkflowType/None@!'Q'",
			"@WorkflowType/None@!G",
			"@WorkflowType@!'M' | @WorkflowType@!'Q'",
			"@WorkflowType@!G",
			"@WorkflowType@!G | @WorkflowType@!'M' | @WorkflowType@!'Q'",
			"@WorkflowType@='M' | @WorkflowType@='Q'",
			"@WorkflowType@='V'",
			"@WorkflowType@=V",
			"1=1",
			"1=2",
			"A_Depreciation_Manual_Period@=YR",
			"C_Sponsor_SalesRep_ID!0",
			// "N",
			"Processed=Y",
			"PropagationType='BOTU' | PropagationType='IVAL'",
			"PropagationType='TOPB' | PropagationType='IVAL'",
			"Y=N");
}
