//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.28 at 11:03:21 AM CEST 
//


package de.metas.postfinance.processprotocol;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.metas.postfinance.processprotocol package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.metas.postfinance.processprotocol
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionDetailType }
     * 
     */
    public TransactionDetailType createTransactionDetailType() {
        return new TransactionDetailType();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link PhysicalAddress }
     * 
     */
    public PhysicalAddress createPhysicalAddress() {
        return new PhysicalAddress();
    }

    /**
     * Create an instance of {@link POBoxAddress }
     * 
     */
    public POBoxAddress createPOBoxAddress() {
        return new POBoxAddress();
    }

    /**
     * Create an instance of {@link TransactionDetailType.RelocationAddress }
     * 
     */
    public TransactionDetailType.RelocationAddress createTransactionDetailTypeRelocationAddress() {
        return new TransactionDetailType.RelocationAddress();
    }

}
