// COMMENTS ENTITY ACTIONS
export const UPDATE_COMMENTS_PANEL = 'UPDATE_COMMENTS_PANEL';
export const UPDATE_COMMENTS_PANEL_TEXT_INPUT =
  'UPDATE_COMMENTS_PANEL_TEXT_INPUT';
export const UPDATE_COMMENTS_PANEL_OPEN_FLAG =
  'UPDATE_COMMENTS_PANEL_OPEN_FLAG';
// END OF COMMENT ACTIONS
