// FILTTER ACTIONS

export const CLEAR_ALL_FILTERS = 'CLEAR_ALL_FILTERS';

export const CREATE_FILTER = 'CREATE_FILTER';

export const DELETE_FILTER = 'DELETE_FILTER';

export const UPDATE_ACTIVE_FILTER = 'UPDATE_ACTIVE_FILTER';

export const UPDATE_WIDGET_SHOWN = 'UPDATE_WIDGET_SHOWN';

// END OF FILTER ACTIONS
