// FILTTER ACTIONS

export const SET_CLEAR_ALL_FILTER = 'SET_CLEAR_ALL_FILTER';

export const CREATE_FILTER = 'CREATE_FILTER';

export const DELETE_FILTER = 'DELETE_FILTER';

export const UPDATE_ACTIVE_FILTER = 'UPDATE_ACTIVE_FILTER';

// END OF FILTER ACTIONS
