import { initLayout, getAttributesInstance, topActionsRequest } from './window';
import {
  getViewLayout,
  getViewRowsByIds,
  browseViewRequest,
  locationSearchRequest,
  locationConfigRequest,
  deleteView,
  createViewRequest,
  filterViewRequest,
  deleteStaticFilter,
  quickActionsRequest,
} from './view';
import {
  loginRequest,
  localLoginRequest,
  loginCompletionRequest,
  logoutRequest,
  resetPasswordRequest,
  getResetPasswordInfo,
  resetPasswordComplete,
  resetPasswordGetAvatar,
  getAvatar,
  getUserSession,
  getUserLang,
  setUserLang,
  getAvailableLang,
} from './login';

export {
  initLayout,
  getAttributesInstance,
  topActionsRequest,
  getViewLayout,
  getViewRowsByIds,
  browseViewRequest,
  locationSearchRequest,
  locationConfigRequest,
  deleteView,
  createViewRequest,
  filterViewRequest,
  deleteStaticFilter,
  quickActionsRequest,
  loginRequest,
  localLoginRequest,
  loginCompletionRequest,
  logoutRequest,
  resetPasswordRequest,
  getResetPasswordInfo,
  resetPasswordComplete,
  resetPasswordGetAvatar,
  getAvatar,
  getUserSession,
  getUserLang,
  setUserLang,
  getAvailableLang,
};
