import { initLayout, getAttributesInstance } from './window';
import {
  getViewLayout,
  getViewRowsByIds,
  browseViewRequest,
  deleteView,
  createViewRequest,
  filterViewRequest,
  deleteStaticFilter,
  quickActionsRequest,
} from './view';
import {
  loginRequest,
  localLoginRequest,
  loginCompletionRequest,
  logoutRequest,
  resetPasswordRequest,
  getResetPasswordInfo,
  resetPasswordComplete,
  resetPasswordGetAvatar,
  getAvatar,
  getUserSession,
  getUserLang,
  setUserLang,
  getAvailableLang,
} from './login';

export {
  initLayout,
  getAttributesInstance,
  getViewLayout,
  getViewRowsByIds,
  browseViewRequest,
  deleteView,
  createViewRequest,
  filterViewRequest,
  deleteStaticFilter,
  quickActionsRequest,
  loginRequest,
  localLoginRequest,
  loginCompletionRequest,
  logoutRequest,
  resetPasswordRequest,
  getResetPasswordInfo,
  resetPasswordComplete,
  resetPasswordGetAvatar,
  getAvatar,
  getUserSession,
  getUserLang,
  setUserLang,
  getAvailableLang,
};
