/*
 * Patient - Warenwirtschaft (Basis)
 * Synchronisation der Patienten mit der Warenwirtschaft
 *
 * OpenAPI spec version: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;
import java.util.UUID;
/**
 * CustomerMapping
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-24T08:15:46.695Z[GMT]")
public class CustomerMapping {
  @SerializedName("_id")
  private UUID _id = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  public CustomerMapping _id(UUID _id) {
    this._id = _id;
    return this;
  }

   /**
   * Alberta-Id
   * @return _id
  **/
  @Schema(example = "a4adecb6-126a-4fa6-8fac-e80165ac4264", required = true, description = "Alberta-Id")
  public UUID getId() {
    return _id;
  }

  public void setId(UUID _id) {
    this._id = _id;
  }

  public CustomerMapping customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Id aus WaWi
   * @return customerId
  **/
  @Schema(example = "D32399", required = true, description = "Id aus WaWi")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerMapping updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Der Zeitstempel der letzten Änderung
   * @return updated
  **/
  @Schema(example = "2019-11-28T08:37:39.637Z", description = "Der Zeitstempel der letzten Änderung")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerMapping customerMapping = (CustomerMapping) o;
    return Objects.equals(this._id, customerMapping._id) &&
        Objects.equals(this.customerId, customerMapping.customerId) &&
        Objects.equals(this.updated, customerMapping.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, customerId, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerMapping {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
