/*
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.ebay.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CancelRequest
 */
public class CancelRequestTest {
    private final CancelRequest model = new CancelRequest();

    /**
     * Model tests for CancelRequest
     */
    @Test
    public void testCancelRequest() {
        // TODO: test CancelRequest
    }

    /**
     * Test the property 'cancelCompletedDate'
     */
    @Test
    public void cancelCompletedDateTest() {
        // TODO: test cancelCompletedDate
    }

    /**
     * Test the property 'cancelInitiator'
     */
    @Test
    public void cancelInitiatorTest() {
        // TODO: test cancelInitiator
    }

    /**
     * Test the property 'cancelReason'
     */
    @Test
    public void cancelReasonTest() {
        // TODO: test cancelReason
    }

    /**
     * Test the property 'cancelRequestedDate'
     */
    @Test
    public void cancelRequestedDateTest() {
        // TODO: test cancelRequestedDate
    }

    /**
     * Test the property 'cancelRequestId'
     */
    @Test
    public void cancelRequestIdTest() {
        // TODO: test cancelRequestId
    }

    /**
     * Test the property 'cancelRequestState'
     */
    @Test
    public void cancelRequestStateTest() {
        // TODO: test cancelRequestState
    }

}
