/*
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.metas.camel.externalsystems.ebay.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.metas.camel.externalsystems.ebay.api.model.Amount;
import de.metas.camel.externalsystems.ebay.api.model.Buyer;
import de.metas.camel.externalsystems.ebay.api.model.CancelStatus;
import de.metas.camel.externalsystems.ebay.api.model.FulfillmentStartInstruction;
import de.metas.camel.externalsystems.ebay.api.model.LineItem;
import de.metas.camel.externalsystems.ebay.api.model.PaymentSummary;
import de.metas.camel.externalsystems.ebay.api.model.PricingSummary;
import de.metas.camel.externalsystems.ebay.api.model.Program;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Order
 */
public class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    public void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    public void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'buyerCheckoutNotes'
     */
    @Test
    public void buyerCheckoutNotesTest() {
        // TODO: test buyerCheckoutNotes
    }

    /**
     * Test the property 'cancelStatus'
     */
    @Test
    public void cancelStatusTest() {
        // TODO: test cancelStatus
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'ebayCollectAndRemitTax'
     */
    @Test
    public void ebayCollectAndRemitTaxTest() {
        // TODO: test ebayCollectAndRemitTax
    }

    /**
     * Test the property 'fulfillmentHrefs'
     */
    @Test
    public void fulfillmentHrefsTest() {
        // TODO: test fulfillmentHrefs
    }

    /**
     * Test the property 'fulfillmentStartInstructions'
     */
    @Test
    public void fulfillmentStartInstructionsTest() {
        // TODO: test fulfillmentStartInstructions
    }

    /**
     * Test the property 'lastModifiedDate'
     */
    @Test
    public void lastModifiedDateTest() {
        // TODO: test lastModifiedDate
    }

    /**
     * Test the property 'legacyOrderId'
     */
    @Test
    public void legacyOrderIdTest() {
        // TODO: test legacyOrderId
    }

    /**
     * Test the property 'lineItems'
     */
    @Test
    public void lineItemsTest() {
        // TODO: test lineItems
    }

    /**
     * Test the property 'orderFulfillmentStatus'
     */
    @Test
    public void orderFulfillmentStatusTest() {
        // TODO: test orderFulfillmentStatus
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'orderPaymentStatus'
     */
    @Test
    public void orderPaymentStatusTest() {
        // TODO: test orderPaymentStatus
    }

    /**
     * Test the property 'paymentSummary'
     */
    @Test
    public void paymentSummaryTest() {
        // TODO: test paymentSummary
    }

    /**
     * Test the property 'pricingSummary'
     */
    @Test
    public void pricingSummaryTest() {
        // TODO: test pricingSummary
    }

    /**
     * Test the property 'program'
     */
    @Test
    public void programTest() {
        // TODO: test program
    }

    /**
     * Test the property 'salesRecordReference'
     */
    @Test
    public void salesRecordReferenceTest() {
        // TODO: test salesRecordReference
    }

    /**
     * Test the property 'sellerId'
     */
    @Test
    public void sellerIdTest() {
        // TODO: test sellerId
    }

    /**
     * Test the property 'totalFeeBasisAmount'
     */
    @Test
    public void totalFeeBasisAmountTest() {
        // TODO: test totalFeeBasisAmount
    }

    /**
     * Test the property 'totalMarketplaceFee'
     */
    @Test
    public void totalMarketplaceFeeTest() {
        // TODO: test totalMarketplaceFee
    }

}
