
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.mail }}
    server: {{ .Values.server }}
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-prod-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx

