INSERT INTO AD_InputDataSource (
    ad_client_id, -- numeric(10,0) NOT NULL,
    ad_inputdatasource_id, -- numeric(10,0) NOT NULL,
    ad_org_id, -- numeric(10,0) NOT NULL,
    created, -- timestamp with time zone NOT NULL,
    createdby, -- numeric(10,0) NOT NULL,
    description, -- character varying(255) COLLATE pg_catalog."default",
    isactive, -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Y'::bpchar,
    name, -- character varying(60) COLLATE pg_catalog."default" NOT NULL,
    updated, -- timestamp with time zone NOT NULL,
    updatedby, -- numeric(10,0) NOT NULL,
    internalname, -- character varying(150) COLLATE pg_catalog."default",
    isdestination, -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'N'::bpchar,
    entitytype, -- character varying(512) COLLATE pg_catalog."default" NOT NULL DEFAULT 'de.metas.swat'::character varying,
    isedienabled -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'N'::bpchar,
) SELECT
      0 AS ad_client_id, -- numeric(10,0) NOT NULL,
      540228, -- numeric(10,0) NOT NULL,
      0 AS ad_org_id, -- numeric(10,0) NOT NULL,
      '2022-06-21 21:10:10' AS created, -- timestamp with time zone NOT NULL,
      100 AS createdby, -- numeric(10,0) NOT NULL,
      'DataSource for Ebay OCL imports.' AS description, -- character varying(255) COLLATE pg_catalog."default",
      'Y' AS isactive, -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Y'::bpchar,
      'Ebay' AS name, -- character varying(60) COLLATE pg_catalog."default" NOT NULL,
      '2022-06-21 21:10:10' AS updated, -- timestamp with time zone NOT NULL,
      0 AS updatedby, -- numeric(10,0) NOT NULL,
      'Ebay' AS internalname, -- character varying(150) COLLATE pg_catalog."default",
      'N' AS isdestination, -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'N'::bpchar,
      'de.metas.swat' AS entitytype, -- character varying(512) COLLATE pg_catalog."default" NOT NULL DEFAULT 'de.metas.swat'::character varying,
      'N' AS isedienabled -- character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'N'::bpchar,
;