apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "metasfresh-esb-camel"
  labels:
    de.metas.deployment.name: "metasfresh-esb-camel"
    de.metas.deployment.type:  metasfresh-esb-camel
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        de.metas.deployment.name: "metasfresh-esb-camel"
        de.metas.deployment.type:  metasfresh-esb-camel
    spec:
      containers:
      - name: metasfresh-esb-camel
        image: metasfresh-esb-camel:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8184
          - containerPort: 8792
        envFrom:
          - configMapRef:
              name: esb-camel-properties
        resources: 
          requests:
            memory: 128M
#            cpu: 500m
