
ALTER TABLE PMM_WeekReport_Event DROP CONSTRAINT IF EXISTS PMMWeek_PMMWeekReportEvent;
ALTER TABLE PMM_WeekReport_Event DROP CONSTRAINT IF EXISTS PMMProduct_PMMWeekReportEvent;
ALTER TABLE C_Flatrate_Term DROP CONSTRAINT IF EXISTS PMMProduct_CFlatrateTerm;
ALTER TABLE PMM_PurchaseCandidate_OrderLine DROP CONSTRAINT IF EXISTS PMMPurchaseCandidate_PMMPurcha;
ALTER TABLE PMM_QtyReport_Event DROP CONSTRAINT IF EXISTS PMMProduct_PMMQtyReportEvent;
ALTER TABLE C_OrderLine DROP CONSTRAINT IF EXISTS PMMContractASI_COrderLine;

ALTER TABLE PMM_WeekReport_Event ADD CONSTRAINT PMMWeek_PMMWeekReportEvent FOREIGN KEY (PMM_Week_ID) REFERENCES PMM_Week DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PMM_WeekReport_Event ADD CONSTRAINT PMMProduct_PMMWeekReportEvent FOREIGN KEY (PMM_Product_ID) REFERENCES PMM_Product DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE C_Flatrate_Term ADD CONSTRAINT PMMProduct_CFlatrateTerm FOREIGN KEY (PMM_Product_ID) REFERENCES PMM_Product DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PMM_PurchaseCandidate_OrderLine ADD CONSTRAINT PMMPurchaseCandidate_PMMPurcha FOREIGN KEY (PMM_PurchaseCandidate_ID) REFERENCES PMM_PurchaseCandidate DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PMM_QtyReport_Event ADD CONSTRAINT PMMProduct_PMMQtyReportEvent FOREIGN KEY (PMM_Product_ID) REFERENCES PMM_Product DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE C_OrderLine ADD CONSTRAINT PMMContractASI_COrderLine FOREIGN KEY (PMM_Contract_ASI_ID) REFERENCES M_AttributeSetInstance DEFERRABLE INITIALLY DEFERRED;

