@from:cucumber
@ghActions:run_on_executor1
Feature: AD_Process validation

  Background:
    Given infrastructure and metasfresh are running

  @from:cucumber
  @Id:S0250_100
  Scenario: Check AD_Processes
    Given all AD_Processes
    But exclude AD_Processes
      | AD_Process_ID | Value                                                               | EntityType                          | Classname                                                                                                        | Reason          |
      | *             |                                                                     | de.metas.ui.web                     |                                                                                                                  |                 |
      | 540953        | WEBUI_SalesOrder_PricingConditionsView_Launcher                     | D                                   | de.metas.ui.web.order.pricingconditions.process.WEBUI_SalesOrder_PricingConditionsView_Launcher                  | Class not found |
      | 540954        | PricingConditionsView_CopyRowToEditable                             | D                                   | de.metas.ui.web.order.pricingconditions.process.PricingConditionsView_CopyRowToEditable                          | Class not found |
      | 540955        | PricingConditionsView_SaveEditableRow                               | D                                   | de.metas.ui.web.order.pricingconditions.process.PricingConditionsView_SaveEditableRow                            | Class not found |
      | 541039        | WEBUI_BPartner_ProductsProposal_Launcher                            | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_BPartner_ProductsProposal_Launcher                         | Class not found |
      | 541046        | WEBUI_ProductsProposal_AddProductFromBasePriceList                  | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_AddProductFromBasePriceList               | Class not found |
      | 541047        | WEBUI_ProductsProposal_ShowProductsToAddFromBasePriceList           | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_ShowProductsToAddFromBasePriceList        | Class not found |
      | 541049        | WEBUI_ProductsProposal_SaveProductPriceToCurrentPriceListVersion    | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_SaveProductPriceToCurrentPriceListVersion | Class not found |
      | 541053        | WEBUI_ProductsProposal_ShowProductsSoldToOtherCustomers             | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_ShowProductsSoldToOtherCustomers          | Class not found |
      | 541061        | WEBUI_ProductsProposal_Delete                                       | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_Delete                                    | Class not found |
      | 541124        | WEBUI_UserGroupRecordAccess_Grant                                   | D                                   | de.metas.security.process.WEBUI_UserGroupRecordAccess_Grant                                                      | Class not found |
      | 541125        | WEBUI_UserGroupRecordAccess_Revoke                                  | D                                   | de.metas.security.process.WEBUI_UserGroupRecordAccess_Revoke                                                     | Class not found |
      | 541139        | C_BPartner_Window_AreaSearchProcess                                 | D                                   | de.metas.location.geocoding.process.C_BPartner_Window_AreaSearchProcess                                          | Class not found |
      | 541167        | M_DiscountSchemaBreak_CopyToOtherSchema                             | D                                   | de.metas.ui.web.pricing.process.M_DiscountSchemaBreak_CopyToOtherSchema                                          | Class not found |
      | 541188        | M_DiscountSchemaBreak_CopyToOtherSchema_Product                     | D                                   | de.metas.ui.web.pricing.process.M_DiscountSchemaBreak_CopyToOtherSchema_Product                                  | Class not found |
      | 541203        | PackageablesView_PrintPicklist                                      | D                                   | de.metas.ui.web.pickingV2.packageable.process.PackageablesView_PrintPicklist                                     | Class not found |
      | 541225        | AddShipmentToTransportationOrderProcess_SingleView                  | D                                   | de.metas.ui.web.inout.process.M_InOut_AddToTransportationOrderProcess_SingleView                                 | Class not found |
      | 541233        | AddShipmentToTransportationOrderProcess_GridView                    | D                                   | de.metas.ui.web.inout.process.M_InOut_AddToTransportationOrderProcess_GridView                                   | Class not found |
      | 584643        | C_BankStatement_ReconcileWithSinglePayment                          | D                                   | de.metas.banking.process.C_BankStatement_ReconcileWithSinglePayment                                              | Class not found |
      | 584646        | C_BankStatement_PaymentAllocation                                   | D                                   | de.metas.banking.process.C_BankStatement_AllocatePayment                                                         | Class not found |
      | 584681        | Fact_Acct_OpenLinkedFacts_SingleView                                | D                                   | de.metas.ui.web.accounting.process.Fact_Acct_OpenLinkedFacts_SingleView                                          | Class not found |
      | 584682        | Fact_Acct_OpenLinkedFacts_GridView                                  | D                                   | de.metas.ui.web.accounting.process.Fact_Acct_OpenLinkedFacts_GridView                                            | Class not found |
      | 584690        | M_ShipmentSchedule_Recompute                                        | D                                   | de.metas.ui.web.inoutcandidate.process.M_ShipmentSchedule_Recompute                                              | Class not found |
      | 584691        | C_Invoice_Candidate_Recompute                                       | D                                   | de.metas.ui.web.invoicecandidate.process.C_Invoice_Candidate_Recompute                                           | Class not found |
      | 584699        | PaymentView_Launcher_From_C_Invoice_SingleDocument                  | D                                   | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_From_C_Invoice_SingleDocument                    | Class not found |
      | 584708        | PaymentView_Launcher_From_C_Invoice_View                            | D                                   | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_From_C_Invoice_View                              | Class not found |
      | 584720        | WEBUI_CloneLine                                                     | D                                   | de.metas.ui.web.process.WEBUI_CloneLine                                                                          | Class not found |
      | 584722        | ProductsToPick_PickAndPackSelected                                  | D                                   | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_PickAndPackSelected                              | Class not found |
      | 584734        | WEBUI_PickingSlotsClearingView_TakeOutTUsAndAddToNewLUs             | D                                   | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutTUsAndAddToNewLUs             | Class not found |
      | 584751        | PP_Order_ChangeExportStatus                                         | D                                   | de.metas.ui.web.pporder.process.WEBUI_PP_Order_ChangeExportStatus                                                | Class not found |
      | 584753        | ChangeEDI_ExportStatus_EDI_Desadv_SingleView                        | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_EDI_Desadv_SingleView                                          | Class not found |
      | 584754        | ChangeEDI_ExportStatus_EDI_Desadv_GridView                          | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_EDI_Desadv_GridView                                            | Class not found |
      | 584755        | ChangeEDI_ExportStatus_C_Invoice_SingleView                         | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_C_Invoice_SingleView                                           | Class not found |
      | 584756        | ChangeEDI_ExportStatus_C_Invoice_GridView                           | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_C_Invoice_GridView                                             | Class not found |
      | 584757        | ChangeEDI_ExportStatus_C_Doc_Outbound_Log_SingleView                | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_C_Doc_Outbound_Log_SingleView                                  | Class not found |
      | 584758        | ChangeEDI_ExportStatus_C_Doc_Outbound_Log_GridView                  | D                                   | de.metas.ui.web.edi_desadv.ChangeEDI_ExportStatus_C_Doc_Outbound_Log_GridView                                    | Class not found |
      | 584820        | C_Invoice_Candidate_RejectFromInvoicing                             | D                                   | de.metas.ui.web.invoicecandidate.process.C_Invoice_Candidate_RevokeApprovalForInvoicing                          | Class not found |
      | 584890        | Assign Attachments                                                  | D                                   | de.metas.ui.web.order.attachmenteditor.process.C_Order_AttachmentView_Launcher                                   | Class not found |
      | 584999        | M_Warehouse_PrintLocatorQRCodes                                     | D                                   | de.metas.warehouse.process.M_Warehouse_PrintLocatorQRCodes                                                       | Class not found |
      | 585002        | Simulation aufrufen                                                 | D                                   | de.metas.ui.web.simulation.process.C_Order_ProductionSimulationView_Launcher                                     | Class not found |
      | 585028        | WEBUI_PP_Order_Pick_ReceivedHUs                                     | D                                   | de.metas.ui.web.pporder.process.WEBUI_PP_Order_Pick_ReceivedHUs                                                  | Class not found |
      | 585102        | WEBUI_ProductsProposal_QuotationHistory                             | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_QuotationHistory                          | Class not found |
      | 585103        | WEBUI_ProductsProposal_ZoomToQuotations                             | D                                   | de.metas.ui.web.order.products_proposal.process.WEBUI_ProductsProposal_ZoomToQuotations                          | Class not found |
      | 585106        | C_BankStatement_ReconcileBankTransfer                               | D                                   | de.metas.banking.process.C_BankStatement_ReconcileBankTransfer                                                   | Class not found |
      | 585107        | C_BankStatement_ChangeCurrencyRate                                  | D                                   | de.metas.banking.process.C_BankStatement_ChangeCurrencyRate                                                      | Class not found |
      | 585150        | S_Resource_PrintSingleQRCode                                        | D                                   | de.metas.resource.process.S_Resource_PrintSingleQRCode                                                           | Class not found |
      | 585151        | S_Resource_PrintQRCodes                                             | D                                   | de.metas.resource.process.S_Resource_PrintQRCodes                                                                | Class not found |
      | 585186        | C_Order_AllocateToForexContract                                     | D                                   | de.metas.forex.webui.process.C_Order_AllocateToForexContract                                                     | Class not found |
      | 585192        | M_Delivery_Planning_GenerateReceipt                                 | D                                   | de.metas.deliveryplanning.webui.process.M_Delivery_Planning_GenerateReceipt                                      | Class not found |
      | 585194        | M_Delivery_Planning_GenerateShipment                                | D                                   | de.metas.deliveryplanning.webui.process.M_Delivery_Planning_GenerateShipment                                     | Class not found |
      | 585214        | C_Order_CreateCost                                                  | D                                   | de.metas.ui.web.order.costs.C_Order_CreateCost                                                                   | Class not found |
      | 585218        | C_Invoice_InOutCostsView_Launcher                                   | D                                   | de.metas.ui.web.invoice.match_inout_costs.C_Invoice_InOutCostsView_Launcher                                      | Class not found |
      | 585220        | InOutCostsView_CreateMatchInv                                       | D                                   | de.metas.ui.web.invoice.match_inout_costs.InOutCostsView_CreateMatchInv                                          | Class not found |
      | 585246        | Resolve hours                                                       | D                                   | de.metas.ui.web.project.step.process.C_Project_WO_Step_ResolveHours                                              | Class not found |
      | 585247        | Undo reservation resolution                                         | D                                   | de.metas.ui.web.project.step.process.C_Project_WO_Step_UndoResolution                                            | Class not found |
      | 585279        | SAP_GLJournal_OpenItems_Launcher                                    | D                                   | de.metas.acct.gljournal_sap.select_open_items.SAP_GLJournal_OpenItems_Launcher                                   | Class not found |
      | 585280        | OIView_Select                                                       | D                                   | de.metas.acct.gljournal_sap.select_open_items.OIView_Select                                                      | Class not found |
      | 585281        | OIView_AddToJournal                                                 | D                                   | de.metas.acct.gljournal_sap.select_open_items.OIView_AddToJournal                                                | Class not found |
      | 585282        | C_Order_UnallocateFromForexContract                                 | D                                   | de.metas.forex.webui.process.C_Order_UnallocateFromForexContract                                                 | Class not found |
      | 585310        | AD_WF_Approval_Request_Approve                                      | D                                   | de.metas.workflow.process.AD_WF_Approval_Request_Approve                                                         | Class not found |
      | 585311        | AD_WF_Approval_Request_ApproveSelection                             | D                                   | de.metas.workflow.process.AD_WF_Approval_Request_ApproveSelection                                                | Class not found |
      | 585332        | C_Workplace_PrintQRCode                                             | D                                   | de.metas.workplace.qrcode.process.C_Workplace_PrintQRCode                                                        | Class not found |
      | 585333        | C_Workplace_PrintQRCode_ViewSelection                               | D                                   | de.metas.workplace.qrcode.process.C_Workplace_PrintQRCode_ViewSelection                                          | Class not found |
      | 585336        | AD_WF_Approval_Request_Download_File                                | D                                   | de.metas.workflow.process.AD_WF_Approval_Request_Download_File                                                   | Class not found |
      | 585337        | AD_WF_My_Approvals_Download_File                                    | D                                   | de.metas.workflow.process.AD_WF_Approval_Request_Download_File                                                   | Class not found |
      | 540911        | WEBUI_Fact_Acct_Repost_ViewRows                                     | de.metas.acct                       | de.metas.ui.web.accounting.process.WEBUI_Fact_Acct_Repost_ViewRows                                               | Class not found |
      | 541209        | WEBUI_Fact_Acct_Repost_SingleDocument                               | de.metas.acct                       | de.metas.ui.web.accounting.process.WEBUI_Fact_Acct_Repost_SingleDocument                                         | Class not found |
      | 585293        | C_Invoice_AcctSimulation_Launcher                                   | de.metas.acct                       | de.metas.acct.acct_simulation.C_Invoice_AcctSimulation_Launcher                                                  | Class not found |
      | 585295        | AcctSimulationView_AddRow                                           | de.metas.acct                       | de.metas.acct.acct_simulation.AcctSimulationView_AddRow                                                          | Class not found |
      | 585296        | AcctSimulationView_RemoveRows                                       | de.metas.acct                       | de.metas.acct.acct_simulation.AcctSimulationView_RemoveRows                                                      | Class not found |
      | 585297        | AcctSimulationView_UpdateSimulation                                 | de.metas.acct                       | de.metas.acct.acct_simulation.AcctSimulationView_UpdateSimulation                                                | Class not found |
      | 585298        | AcctSimulationView_Save                                             | de.metas.acct                       | de.metas.acct.acct_simulation.AcctSimulationView_Save                                                            | Class not found |
      | 585303        | SAP_GLJournal_AcctSimulation_Launcher                               | de.metas.acct                       | de.metas.acct.acct_simulation.SAP_GLJournal_AcctSimulation_Launcher                                              | Class not found |
      | 584667        | C_BankStatement_ReconcileWithPaySelection                           | de.metas.banking                    | de.metas.banking.process.C_BankStatement_ReconcileWithPaySelection                                               | Class not found |
      | 584669        | PaymentsToReconcileView_Reconcile                                   | de.metas.banking                    | de.metas.ui.web.bankstatement_reconciliation.process.PaymentsToReconcileView_Reconcile                           | Class not found |
      | 584670        | C_BankStatement_ReconcileESRImport                                  | de.metas.banking                    | de.metas.banking.process.C_BankStatement_ReconcileESRImport                                                      | Class not found |
      | 584671        | C_BankStatement_UnReconcileLine                                     | de.metas.banking                    | de.metas.banking.process.C_BankStatement_UnReconcileLine                                                         | Class not found |
      | 584993        | PrintDeviceQRCodes                                                  | de.metas.device.scales              | de.metas.devices.webui.process.PrintDeviceQRCodes                                                                | Class not found |
      | 540458        | M_ShipmentSchedule_EnqueueSelection                                 | de.metas.handlingunits              | de.metas.ui.web.shipmentschedule.process.M_ShipmentSchedule_EnqueueSelection                                     | Class not found |
      | 540820        | WEBUI_M_HU_MoveToAnotherWarehouse                                   | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_MoveToAnotherWarehouse_ExclQuarantined                          | Class not found |
      | 540937        | M_Product_LotNumber_Quarantine                                      | de.metas.handlingunits              | de.metas.ui.web.product.process.WEBUI_M_Product_LotNumber_Quarantine                                             | Class not found |
      | 540980        | WEBUI_C_OrderLineSO_Launch_HUEditor                                 | de.metas.handlingunits              | de.metas.ui.web.order.sales.hu.reservation.process.WEBUI_C_OrderLineSO_Launch_HUEditor                           | Class not found |
      | 540983        | WEBUI_C_OrderLineSO_Make_HUReservation                              | de.metas.handlingunits              | de.metas.ui.web.order.sales.hu.reservation.process.WEBUI_C_OrderLineSO_Make_HUReservation                        | Class not found |
      | 540985        | WEBUI_C_OrderLineSO_Delete_HUReservation                            | de.metas.handlingunits              | de.metas.ui.web.order.sales.hu.reservation.process.WEBUI_C_OrderLineSO_Delete_HUReservation                      | Class not found |
      | 541006        | WEBUI_M_HU_MoveToAnotherWarehouse_QA                                | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_MoveToAnotherWarehouse_InclQuarantined                          | Class not found |
      | 584819        | WEBUI_M_HU_MoveToGarbage_2                                          | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_MoveToGarbage                                                   | Class not found |
      | 584826        | WEBUI_M_HU_MoveToGarbage_Partial                                    | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_MoveToGarbage_Partial                                           | Class not found |
      | 584982        | M_HU_Assign_QRCode                                                  | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Assign_QRCode                                                   | Class not found |
      | 585070        | M_Picking_Job_ApproveAndComplete                                    | de.metas.handlingunits              | de.metas.handlingunits.picking.job.process.M_Picking_Job_ApproveAndComplete                                      | Class not found |
      | 585326        | WEBUI_M_HU_ReceiveAdditionalHUs_UsingConfig                         | de.metas.handlingunits              | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_ReceiveAdditionalHUs_UsingConfig                                | Class not found |
      | 541179        | ShipmentCandidatesView_Launcher                                     | de.metas.inoutcandidate             | de.metas.ui.web.shipment_candidates_editor.process.ShipmentCandidatesView_Launcher                               | Class not found |
      | 540910        | MD_Cockpit_DocumentDetail_Display                                   | de.metas.material.cockpit           | de.metas.ui.web.material.cockpit.process.MD_Cockpit_DocumentDetail_Display                                       | Class not found |
      | 540966        | MD_Cockpit_PricingConditions                                        | de.metas.material.cockpit           | de.metas.ui.web.material.cockpit.process.MD_Cockpit_PricingConditions                                            | Class not found |
      | 585342        | MD_Cockpit_SetProcurementStatus                                     | de.metas.material.cockpit           | de.metas.ui.web.material.cockpit.process.MD_Cockpit_SetProcurementStatus                                         | Class not found |
      | 540993        | MD_Cockpit_ShowStockDetails                                         | de.metas.material.cockpit           | de.metas.ui.web.material.cockpit.process.MD_Cockpit_ShowStockDetails                                             | Class not found |
      | 541038        | WEBUI_Order_ProductsProposal_Launcher                               | de.metas.order                      | de.metas.ui.web.order.products_proposal.process.WEBUI_Order_ProductsProposal_Launcher                            | Class not found |
      | 541214        | PaymentView_Launcher_FromPayment                                    | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_FromPayment                                      | Class not found |
      | 541215        | PaymentsView_Allocate                                               | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentsView_Allocate                                                 | Class not found |
      | 541221        | PaymentsView_AddAdditionalPayment                                   | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentsView_AddAdditionalPayment                                     | Class not found |
      | 541222        | InvoicesView_AddAdditionalInvoice                                   | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.InvoicesView_AddAdditionalInvoice                                     | Class not found |
      | 541223        | PaymentView_Launcher_From_BPartnerView                              | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_From_BPartnerView                                | Class not found |
      | 541224        | PaymentView_Launcher_From_BPartnerSingleDocument                    | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_From_BPartnerSingleDocument                      | Class not found |
      | 584806        | InvoicesView_MarkPreparedForAllocation                              | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.InvoicesView_MarkPreparedForAllocation                                | Class not found |
      | 584807        | InvoicesView_UnMarkPreparedForAllocation                            | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.InvoicesView_UnMarkPreparedForAllocation                              | Class not found |
      | 585029        | PaymentsView_InvoiceDiscount                                        | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentsView_InvoiceDiscount                                          | Class not found |
      | 585030        | PaymentsView_InvoiceWriteOff                                        | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentsView_InvoiceWriteOff                                          | Class not found |
      | 585031        | PaymentsView_PaymentWriteOff                                        | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentsView_PaymentWriteOff                                          | Class not found |
      | 585082        | PaymentView_Launcher_From_PaySelection                              | de.metas.payment                    | de.metas.ui.web.payment_allocation.process.PaymentView_Launcher_From_PaySelection                                | Class not found |
      | 540807        | WEBUI_Picking_PickQtyToNewHU                                        | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_PickQtyToNewHU                                         | Class not found |
      | 540810        | WEBUI_Picking_M_Picking_Candidate_Process                           | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_M_Picking_Candidate_Process                            | Class not found |
      | 540874        | WEBUI_PickingSlotsClearingView_TakeOutHU                            | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutHU                            | Class not found |
      | 540894        | WEBUI_HUsToPick_PickCU                                              | de.metas.picking                    | de.metas.ui.web.picking.husToPick.process.WEBUI_HUsToPick_PickCU                                                 | Class not found |
      | 540899        | WEBUI_PackingHUsView_AddHUsToShipperTransportation                  | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PackingHUsView_AddHUsToShipperTransportation                  | Class not found |
      | 540901        | WEBUI_PickingSlotsClearingView_TakeOutCUsAndAddToTU                 | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutCUsAndAddToTU                 | Class not found |
      | 540902        | WEBUI_PickingSlotsClearingView_TakeOutHUAndAddToNewHU               | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutHUAndAddToNewHU               | Class not found |
      | 540904        | WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice    | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PackingHUsView_AddHUsToShipperTransportationShipAndInvoice    | Class not found |
      | 540917        | WEBUI_PickingSlotsClearingView_TakeOutTUAndAddToLU                  | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutTUAndAddToLU                  | Class not found |
      | 540927        | WEBUI_PickingSlotsClearingView_TakeOutMultiHUsAndAddToNewHU         | de.metas.picking                    | de.metas.ui.web.pickingslotsClearing.process.WEBUI_PickingSlotsClearingView_TakeOutMultiHUsAndAddToNewHU         | Class not found |
      | 540948        | WEBUI_Picking_TU_Label_For_HU                                       | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_TU_Label                                               | Class not found |
      | 541007        | PackageablesView_OpenProductsToPick                                 | de.metas.picking                    | de.metas.ui.web.pickingV2.packageable.process.PackageablesView_OpenProductsToPick                                | Class not found |
      | 541009        | ProductsToPick_PickSelected                                         | de.metas.picking                    | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_PickSelected                                     | Class not found |
      | 541012        | ProductsToPick_Request4EyesReview                                   | de.metas.picking                    | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_Request4EyesReview                               | Class not found |
      | 541013        | PackageablesView_UnlockFromLoggedUser                               | de.metas.picking                    | de.metas.ui.web.pickingV2.packageable.process.PackageablesView_UnlockFromLoggedUser                              | Class not found |
      | 541014        | PackageablesView_UnlockAll                                          | de.metas.picking                    | de.metas.ui.web.pickingV2.packageable.process.PackageablesView_UnlockAll                                         | Class not found |
      | 541017        | ProductsToPick_MarkWillNotPickSelected                              | de.metas.picking                    | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_MarkWillNotPickSelected                          | Class not found |
      | 541021        | ProductsToPick_4EyesReview_ProcessAll                               | de.metas.picking                    | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_4EyesReview_ProcessAll                           | Class not found |
      | 541024        | ProductsToPick_SetPackingInstructions                               | de.metas.picking                    | de.metas.ui.web.pickingV2.productsToPick.process.ProductsToPick_SetPackingInstructions                           | Class not found |
      | 584710        | WEBUI_HUsToPick_Weight                                              | de.metas.picking                    | de.metas.ui.web.picking.husToPick.process.WEBUI_HUsToPick_Weight                                                 | Class not found |
      | 584719        | WEBUI_Picking_ForcePickToNewHU                                      | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_ForcePickToNewHU                                       | Class not found |
      | 585165        | WEBUI_Picking_PickQtyToComputedHU                                   | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_PickQtyToComputedHU                                    | Class not found |
      | 585166        | WEBUI_Picking_ForcePickToComputedHU                                 | de.metas.picking                    | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_ForcePickToComputedHU                                  | Class not found |
      | 540876        | PMM_Purchase_Candidate_CreatePurchaseOrder                          | de.metas.procurement                | de.metas.ui.web.procurement.process.PMM_Purchase_Candidate_CreatePurchaseOrder                                   | Class not found |
      | 540887        | WEBUI_SalesOrder_PurchaseView_Launcher                              | de.metas.purchasecandidate          | de.metas.ui.web.order.sales.purchasePlanning.process.WEBUI_SalesOrder_PurchaseView_Launcher                      | Class not found |
      | 540916        | WEBUI_SalesOrder_Apply_Availability_Row                             | de.metas.purchasecandidate          | de.metas.ui.web.order.sales.purchasePlanning.process.WEBUI_SalesOrder_Apply_Availability_Row                     | Class not found |
      | 540972        | WEBUI_PurchaseCandidates_PurchaseView_Launcher                      | de.metas.purchasecandidate          | de.metas.ui.web.order.sales.purchasePlanning.process.WEBUI_PurchaseCandidates_PurchaseView_Launcher              | Class not found |
      | 584735        | WEBUI_ServicesCompanies_Toggle_Processed                            | de.metas.serviceprovider            | de.metas.ui.web.issues.WEBUI_ServicesCompanies_Toggle_Processed                                                  | Class not found |
      | 584771        | CustomerReturns_OpenHUToReturn                                      | de.metas.servicerepair              | de.metas.servicerepair.customerreturns.process.CustomerReturns_OpenHUToReturn                                    | Class not found |
      | 584774        | HUsToReturn_SelectHU                                                | de.metas.servicerepair              | de.metas.servicerepair.customerreturns.process.HUsToReturn_SelectHU                                              | Class not found |
      | 584776        | CustomerReturns_AddSpareParts                                       | de.metas.servicerepair              | de.metas.servicerepair.customerreturns.process.CustomerReturns_AddSpareParts                                     | Class not found |
      | 584779        | de.metas.servicerepair.request.process.R_Request_StartProject       | de.metas.servicerepair              | de.metas.servicerepair.request.process.R_Request_StartProject                                                    | Class not found |
      | 584781        | C_Project_CreateQuotation                                           | de.metas.servicerepair              | de.metas.servicerepair.project.process.C_Project_CreateQuotation                                                 | Class not found |
      | 584783        | de.metas.servicerepair.project.process.C_Project_OpenHUsToIssue     | de.metas.servicerepair              | de.metas.servicerepair.project.process.C_Project_OpenHUsToIssue                                                  | Class not found |
      | 584784        | de.metas.servicerepair.project.process.HUsToIssueView_IssueHUs      | de.metas.servicerepair              | de.metas.servicerepair.project.process.HUsToIssueView_IssueHUs                                                   | Class not found |
      | 584785        | de.metas.servicerepair.project.process.C_Project_ReleaseReservedHUs | de.metas.servicerepair              | de.metas.servicerepair.project.process.C_Project_ReleaseReservedHUs                                              | Class not found |
      | 584786        | de.metas.servicerepair.project.process.C_Project_StartRepairOrder   | de.metas.servicerepair              | de.metas.servicerepair.project.process.C_Project_StartRepairOrder                                                | Class not found |
      | 584790        | de.metas.servicerepair.project.process.C_Project_RecalculateSummary | de.metas.servicerepair              | de.metas.servicerepair.project.process.C_Project_RecalculateSummary                                              | Class not found |
      | 584813        | HUsToReturn_CreateShippedHU                                         | de.metas.servicerepair              | de.metas.servicerepair.customerreturns.process.HUsToReturn_CreateShippedHU                                       | Class not found |
      | 540950        | WEBUI_C_BPartner_UpdateCustomerPharmaPermissions                    | de.metas.vertical.pharma            | de.metas.ui.web.pharma.process.WEBUI_C_BPartner_UpdateCustomerPharmaPermissions                                  | Class not found |
      | 540951        | WEBUI_C_BPartner_UpdateVendorPharmaPermissions                      | de.metas.vertical.pharma            | de.metas.ui.web.pharma.process.WEBUI_C_BPartner_UpdateVendorPharmaPermissions                                    | Class not found |
      | 541103        | WEBUI_M_HU_SecurPharmScan                                           | de.metas.vertical.pharma.securpharm | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_SecurPharmScan                                                  | Class not found |
      | 584700        | HU Editor öffnen                                                    | EE01                                | de.metas.ui.web.ddorder.process.WEBUI_MoveHUs_HUEditor_Launcher                                                  | Class not found |
      | 584703        | Produkte umlagern                                                   | EE01                                | de.metas.ui.web.ddorder.process.WEBUI_DD_OrderLine_MoveSelected_HU                                               | Class not found |
      | 584792        | PP_Order_RecordWork                                                 | EE01                                | de.metas.ui.web.pporder.process.PP_Order_RecordWork                                                              | Class not found |
      | 585148        | M_HU_AddPPOrderSourceHU                                             | EE01                                | de.metas.handlingunits.pporder.source_hu.process.M_HU_AddPPOrderSourceHU                                         | Class not found |
      | 540815        | WEBUI_Picking_M_Picking_Candidate_Unprocess                         | U                                   | de.metas.ui.web.picking.pickingslot.process.WEBUI_Picking_M_Picking_Candidate_Unprocess                          | Class not found |
      | 584767        | WEBUI_PP_Order_PrintLabel                                           | U                                   | de.metas.ui.web.pporder.process.WEBUI_PP_Order_PrintLabel                                                        | Class not found |
      | 584808        | M_DiscountSchemaBreak_CopyToSelectedRows                            | U                                   | de.metas.ui.web.pricing.process.M_DiscountSchemaBreak_CopyToSelectedSchema_Product                               | Class not found |
      | 584852        | WEBUI_M_HU_PrintFinishedGoodsLabel                                  | U                                   | de.metas.ui.web.handlingunits.process.WEBUI_M_HU_PrintFinishedGoodsLabel                                         | Class not found |
      | 585316        | C_Order_Generate_Shipping_Notification                              | de.metas.shippingnotification       | de.metas.inoutcandidate.process.C_Order_Generate_Shipping_Notification                                       | webui           |
      | 585344        | C_Order_Generate_Shipping_Notification_ViewSelection                | de.metas.shippingnotification       | de.metas.inoutcandidate.process.C_Order_Generate_Shipping_Notification_ViewSelection                        | webui           |
      | 585350        | AuthTokenPrintQrCode                                                | D                                   | de.metas.security.process.AuthTokenPrintQrCode                                                                   | webui           |


    Then assert selected AD_Processes are valid
