export const UPDATE_MANUFACTURING_ISSUE_QTY = 'UPDATE_MANUFACTURING_ISSUE_QTY';

export const UPDATE_MANUFACTURING_RECEIPT_TARGET = 'UPDATE_MANUFACTURING_RECEIPT_TARGET';
export const UPDATE_MANUFACTURING_RECEIPT_QTY = 'UPDATE_MANUFACTURING_RECEIPT_QTY';
