-- VAT-ID online check: create the VATaxID_Config id sequence, because a LATER MIGRATION consumes it.
--
-- READ THIS BEFORE "SIMPLIFYING" IT AWAY. The metasfresh-db skill documents, with a Review-rule, that a
-- migration creating a new table must NOT hand-write CREATE SEQUENCE or an AD_Sequence row: native PK
-- sequences are auto-created by public.dba_seq_check_native(), and flagging their absence is a known false
-- positive. That rule is correct and this script is NOT an exception to it for the usual reason.
--
-- It exists because of TIMING, which that rule does not cover. dba_seq_check_native() runs from
-- after_migration(), i.e. AFTER the whole migration batch. Script 5819340 seeds a default VATaxID_Config
-- row and calls nextval('vataxid_config_seq') to do it — MID-batch, long before after_migration() gets a
-- chance to create anything. On a freshly migrated database the sequence therefore does not exist yet at
-- that moment, and db-apply-migrations failed with exactly that: 'relation "vataxid_config_seq" does not
-- exist'. Locally it passed, because a dev database has had an application running against it and the
-- sequence was created lazily on first insert.
--
-- So the rule of thumb is: a migration that merely CREATES a table needs nothing; a migration that itself
-- INSERTS a row and draws the id from the table's native sequence has to make sure the sequence is there
-- first.
--
-- Only VATaxID_Config is created here. VATaxID_CheckLog deliberately gets nothing: no migration inserts
-- into it, so dba_seq_check_native() at the end of the batch is in time for it, exactly as the documented
-- convention says. And no AD_Sequence row is written for either — that row is unused by the
-- native-sequence path and the skill calls it legacy belt-and-suspenders.
--
-- IF NOT EXISTS keeps this a no-op wherever the sequence already exists; Postgres does not restart or
-- alter an existing sequence, and rows an application already created drew from this same sequence, so
-- START 1000000 cannot collide with them retroactively. Parameters match DB.createTableSequence's own
-- defaults.
--
-- IDs from idserver.metas.de: AD_MigrationScript 5819290.

CREATE SEQUENCE IF NOT EXISTS VATaxID_Config_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1000000
;
