apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "metasfresh-esb-camel-mf15-dev"
  labels:
    de.metas.deployment.name: "metasfresh-esb-camel-mf15-dev"
    de.metas.deployment.type:  metasfresh-esb-camel
    de.metas.deployment.stage: "dev"
    de.metas.deployment.user: "mf15"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        de.metas.deployment.name: "metasfresh-esb-camel-mf15-dev"
        de.metas.deployment.type:  metasfresh-esb-camel
        de.metas.deployment.stage: "dev"
        de.metas.deployment.user: "mf15"
    spec:
      containers:
      - name: metasfresh-esb-camel
        image: docker.metasfresh.com/metasfresh/de-metas-edi-esb-camel:master_LATEST
        imagePullPolicy: Always
        ports:
          - containerPort: 8184
          - containerPort: 8792
        envFrom:
          - configMapRef:
              name: esb-camel-properties
        resources: 
          requests:
            memory: 128M
#            cpu: 500m
        volumeMounts:
          - mountPath: $(ARCHIVE_TO_METASFRESH_DIR)
            name: archive-to-dir
          - mountPath: $(ARCHIVE_FROM_METASFRESH_DIR)
            name: archive-from-dir
          - mountPath: $(EDI_LOCAL_DIR)
            name: edi-dir
      restartPolicy: Always
      volumes:
        - name: archive-to-dir
          hostPath:
            path: $(ARCHIVE_TO_METASFRESH_DIR)
        - name: archive-from-dir
          hostPath:
            path: $(ARCHIVE_FROM_METASFRESH_DIR)
        - name: edi-dir
          hostPath:
            path: $(EDI_LOCAL_DIR)
