apiVersion: v1
kind: Service
metadata:
  name: "metasfresh-esb-camel-mf15-dev"
  labels:
    de.metas.deployment.type: metasfresh-esb-camel
    de.metas.deployment.stage: "dev"
    de.metas.deployment.user: "mf15"
spec:
  ports:
  - name: http
    port: 8184
    protocol: TCP
    targetPort: 8184
    nodePort: 30010
  - name: remote-debug
    port: 8792
    protocol: TCP
    targetPort: 8792
    nodePort: 30011
  selector:
    de.metas.deployment.stage: "dev"
    de.metas.deployment.type: metasfresh-esb-camel
    de.metas.deployment.user: "mf15"
  sessionAffinity: None
# use nodeport such that we can also use metasfresh-esb-camel as part of the developement environment
# see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  type: NodePort
