productNo=ArtikelNr.
P_Name=Artikel
Unit=Einheit
Qty=Menge
Page=Seite
BaseListPrice=Std.Preis
BasePricePerUOM=Std.Einh.
BasePriceListVersion=Std.Liste
SpecialPrice=Sond.Preis
SpecialPricePerUOM=Sond.Einh.
SpecialPriceListVersion=Sond.Liste
DateFrom=Datum von:
DateTo=Datum bis:
BP_Value=Geschäftspartner-Nr.:
Title=Verkaufspreis-Auskunft
