INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (102, 'Mengen', 'Mengen', 'les montants');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (106, 'Produkt', 'Produkt', 'produit');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (107, 'Geschäftspartner', 'Geschäftspartner', 'Associé');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (108, 'Lager', 'Lager', 'entrepôt');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (109, 'Bank', 'Bank', 'Banque');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (110, 'Kassenbuch', 'Kassenbuch', 'Livre de caisse');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (111, 'Steuer', 'Steuer', 'Impôt');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (112, 'Projekt', 'Projekt', 'Projet');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (113, 'Allgemein', 'Allgemein', 'Général');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (115, 'Standardkosten', 'Standardkosten', 'Coûts standard');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (116, 'Aktual-Kosten', 'Aktual-Kosten', 'Coûts actuels');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (117, 'Statistik', 'Statistik', 'statistiques');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (118, 'Standardwerte', 'Standardwerte', 'Valeurs standard');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (119, 'Anfrage-Management', 'Anfrage-Management', 'Gestion des demandes');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (120, 'Webshop', 'Webshop', 'Boutique en ligne');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (121, 'Intern', 'Intern', 'Intérieurement');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (122, 'Extern', 'Extern', 'Externe');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (123, 'Gemeinsam', 'Gemeinsam', 'Ensemble');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (124, 'Lieferschein', 'Lieferschein', 'Bon de livraison');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (127, 'Simulation', 'Simulation', 'simulation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (128, 'Berechnungen', 'Berechnungen', 'Calculs');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (129, 'Proxy', 'Proxy', 'Procuration');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (132, 'Nur ..', 'Nur ..', 'Seulement ..');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (133, 'Auswahl', 'Auswahl', 'sélection');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (134, 'Workflow', 'Workflow', 'Flux de travail');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (135, 'Berechtigung', 'Berechtigung', 'autorisation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50001, 'Accounts', 'Accounts', 'Comptes');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50002, 'Setup', 'Setup', 'Mettre en place');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50003, 'Dates', 'Dates', 'Rendez-vous');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50004, 'Revaluation Accounts', 'Revaluation Accounts', 'Comptes de réévaluation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50005, 'Contract', 'Contract', 'Contracter');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50006, 'Options', 'Options', 'Options');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50007, 'General Ledger', 'General Ledger', 'Grand livre général');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50008, 'Machines', 'Machines', 'Machines');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50009, 'Database', 'Database', 'Base de données');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540079, 'Kundenanforderungen', 'Kundenanforderungen', 'Les exigences des clients');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (1000001, 'Weitere Funktionen', 'Weitere Funktionen', 'Plus de fonctions');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (131, 'Rechnungsstellung', 'Rechnungsstellung', 'Facturation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (1000002, 'Text', 'Text', 'texte');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (130, 'Lieferung', 'Lieferung', 'livraison');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (101, 'Status', 'Status', 'statut');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (126, 'Position', 'Position', 'position');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (1000004, 'Einstellungen', 'Einstellungen', 'réglages');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (1000003, 'Kunde', 'Kunde', 'client');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (1000005, 'Schnellerfassung', 'Schnellerfassung', 'Version rapide');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540000, 'Zahlung', 'Zahlung', 'Paiement');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540001, 'Mahnung', 'Mahnung', 'Attention');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540002, 'Lieferant', 'Lieferant', 'le fournisseur');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (103, 'Beträge', 'Beträge', 'Les montants');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (125, 'Beleg', 'Beleg', 'reçu');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540003, 'Verlauf', 'Verlauf', 'Cours');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50000, 'Zugriff für Info-Fenster', 'Zugriff für Info-Fenster', 'Accès pour les informations Windows');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (114, 'Aktion', 'Aktion', 'action');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50012, 'Logo', 'Logo', 'logo');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (505000, 'Schnellerfassung', 'Schnellerfassung', 'Version rapide');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540005, 'Verlauf', 'Verlauf', 'Cours');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540007, 'Wichtige Infos', 'Wichtige Infos', 'Informations importantes');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (105, 'Anfrage- Historie', 'Anfrage- Historie', 'Demander l''historique');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (104, 'Referenz', 'Referenz', 'référence');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540009, 'Vertriebspartner', 'Vertriebspartner', 'Partenaire de vente');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540010, 'Auftrag', 'Auftrag', 'ordre');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540011, 'Rechnung', 'Rechnung', 'facture d''achat');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540012, 'Mahnung', 'Mahnung', 'Attention');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540013, 'Konditionen', 'Konditionen', 'Les conditions');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540014, 'Einkauf', 'Einkauf', 'Achat');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540015, 'Memo', 'Memo', 'note');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540006, 'optionale Angaben', 'optionale Angaben', 'Information optionnelle');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540024, 'Portal', 'Portal', 'portail');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540025, 'Auftragskopf', 'Auftragskopf', 'Chef de commande');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540032, 'Vertragspartner', 'Vertragspartner', 'Partenaire contractuel');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540030, 'Disposition - Menge', 'Disposition - Menge', 'Disposition - Quantité');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540008, 'Weitere Bearbeitung', 'Weitere Bearbeitung', 'Traitement ultérieur');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540031, 'Disposition - Lieferort', 'Disposition - Lieferort', 'Disposition - Lieu de livraison');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540054, 'Account Locks', 'Account Locks', 'Verrous de compte');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540055, 'Description', 'Description', 'La description');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540058, 'Packvorschrift-Produkt Zuordnung', 'Packvorschrift-Produkt Zuordnung', 'Affectation de produit de provision de pack');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540059, 'Handling Units', 'Handling Units', 'Unités de manipulation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540060, 'Abladeort', 'Abladeort', 'Lieu de déchargement');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540067, 'Aggregation', 'Aggregation', 'Agrégation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540069, 'Rechnungsstellung (detail)', 'Rechnungsstellung (detail)', 'Position de facture (détail)');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540070, 'Rechnungsstellung', 'Rechnungsstellung', 'Facturation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540073, 'Status', 'Status', 'statut');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540066, 'Beschreibungen', 'Beschreibungen', 'Descriptions');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540068, 'Rechnungskandidat', 'Rechnungskandidat', 'Candidat à la facture');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540074, 'Preis (Detail)', 'Preis (Detail)', 'Prix');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (50010, 'Produktion', 'Produktion', 'production');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540076, 'Detail', 'Detail', 'détail');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540077, 'MRP', 'MRP', 'MRP');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540078, 'IBAN', 'IBAN', 'Iban');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540080, 'Filterkriterien', 'Filterkriterien', 'Critères de filtre');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540081, 'Drucker-Zuordnung', 'Drucker-Zuordnung', 'Affectation de l''imprimante');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540075, 'Material-Vorgang', 'Material-Vorgang', 'Processus matériel');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540082, 'Kontoinhaber', 'Kontoinhaber', 'propriétaire du compte');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540083, 'EDI', 'EDI', 'Edi');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540084, 'Procurement', 'Procurement', 'Approvisionnement');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540085, 'EMail', 'EMail', 'E-mail');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540086, 'WebUI', 'WebUI', 'Webui');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540033, 'Abschluss', 'Abschluss', 'Diplôme');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540034, 'Abrechnung', 'Abrechnung', 'facture d''achat');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540037, 'Verrechnung', 'Verrechnung', 'facturation');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540038, 'Vertragsverlängerung', 'Vertragsverlängerung', 'extension de contrat');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540039, 'Vertragsbedingungen', 'Vertragsbedingungen', 'Termes contractuels');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540041, 'Belegverarbeitung', 'Belegverarbeitung', 'Traitement des documents');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540044, 'Maßeinheit', 'Maßeinheit', 'Unité de mesure');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540040, 'Vor Vertragsablauf', 'Vor Vertragsablauf', 'Avant le contrat');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540051, 'Lieferung (nur bei Abos)', 'Lieferung (nur bei Abos)', 'Livraison (uniquement avec des abonnements)');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540088, 'Master', 'Master', 'Maître');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540090, 'Pharma', 'Pharma', 'Pharmaceutique');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540091, 'Filtering', 'Filtering', 'Filtration');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540094, 'AWS credentials', 'AWS credentials', 'Contaliens AWS');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540095, 'AWS credentials provider', 'AWS credentials provider', 'Fournisseur d''identification AWS');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540096, 'LWA credentials', 'LWA credentials', 'LWA');
INSERT INTO migration_data."AD_FieldGroup_trad" (ad_fieldgroup_id, name_de, name_trad, name_trl) VALUES (540097, 'API', 'API', 'API');
