apiVersion: v1
kind: Secret
metadata:
  name: metasfresh-{{ .Release.Name }}-pgadmin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  default-email: {{ .Values.pgadmin.defaultEmail | b64enc }}
  default-password: {{ .Values.pgadmin.defaultPassword | b64enc }}
  