{{ if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: metasfresh-{{ .Release.Name }}-tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  {{ (.Files.Glob "files/tls.crt").AsSecrets | indent 2 }}
  {{ (.Files.Glob "files/tls.key").AsSecrets | indent 2 }}
{{ end }}