-- Oct 27, 2016 6:04 PM
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE WEBUI_Dashboard (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, IsDefault CHAR(1) DEFAULT 'N' CHECK (IsDefault IN ('Y','N')) NOT NULL, Name VARCHAR(40) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WEBUI_Dashboard_ID NUMERIC(10) NOT NULL, CONSTRAINT WEBUI_Dashboard_Key PRIMARY KEY (WEBUI_Dashboard_ID))
;

-- Oct 27, 2016 6:05 PM
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE WEBUI_DashboardItem (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, URL VARCHAR(2000) DEFAULT NULL , WEBUI_Dashboard_ID NUMERIC(10) NOT NULL, WEBUI_DashboardItem_ID NUMERIC(10) NOT NULL, X NUMERIC(10) NOT NULL, Y NUMERIC(10) NOT NULL, CONSTRAINT WEBUI_DashboardItem_Key PRIMARY KEY (WEBUI_DashboardItem_ID))
;

ALTER TABLE WEBUI_DashboardItem ADD CONSTRAINT WEBUIDashboard_WEBUIDashboardI FOREIGN KEY (WEBUI_Dashboard_ID) REFERENCES WEBUI_Dashboard DEFERRABLE INITIALLY DEFERRED;

