-- Feb 25, 2017 6:55 PM
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE WEBUI_KPI (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, ChartType VARCHAR(2) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(2000), ES_Index VARCHAR(255) NOT NULL, ES_Query TEXT, ES_TimeRange VARCHAR(255), ES_Type VARCHAR(255) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WEBUI_KPI_ID NUMERIC(10) NOT NULL, CONSTRAINT WEBUI_KPI_Key PRIMARY KEY (WEBUI_KPI_ID))
;

-- Feb 25, 2017 6:55 PM
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE WEBUI_KPI_Field (AD_Client_ID NUMERIC(10) NOT NULL, AD_Element_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Reference_ID NUMERIC(10) NOT NULL, Created TIMESTAMP WITH TIME ZONE NOT NULL, CreatedBy NUMERIC(10) NOT NULL, ES_FieldPath VARCHAR(255) NOT NULL, ES_TimeField CHAR(1) DEFAULT 'N' CHECK (ES_TimeField IN ('Y','N')) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN ('Y','N')) NOT NULL, Name VARCHAR(255) NOT NULL, Updated TIMESTAMP WITH TIME ZONE NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WEBUI_KPI_Field_ID NUMERIC(10) NOT NULL, WEBUI_KPI_ID NUMERIC(10) NOT NULL, CONSTRAINT ADElement_WEBUIKPIField FOREIGN KEY (AD_Element_ID) REFERENCES AD_Element DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ADReference_WEBUIKPIField FOREIGN KEY (AD_Reference_ID) REFERENCES AD_Reference DEFERRABLE INITIALLY DEFERRED, CONSTRAINT WEBUI_KPI_Field_Key PRIMARY KEY (WEBUI_KPI_Field_ID), CONSTRAINT WEBUIKPI_WEBUIKPIField FOREIGN KEY (WEBUI_KPI_ID) REFERENCES WEBUI_KPI DEFERRABLE INITIALLY DEFERRED)
;

-- Feb 25, 2017 6:56 PM
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
ALTER TABLE WEBUI_DashboardItem ADD CONSTRAINT WEBUIKPI_WEBUIDashboardItem FOREIGN KEY (WEBUI_KPI_ID) REFERENCES WEBUI_KPI DEFERRABLE INITIALLY DEFERRED
;

