/*
 * Selling Partner API for Orders
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.adekia.exchange.amazonsp.client.orders.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Contains information regarding the Shipping Settings Automation program, such as whether the order&#39;s shipping settings were generated automatically, and what those settings are.
 */
@Schema(description = "Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping settings were generated automatically, and what those settings are.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-02T14:17:07.399+02:00")
public class AutomatedShippingSettings {
  @SerializedName("HasAutomatedShippingSettings")
  private Boolean hasAutomatedShippingSettings = null;

  @SerializedName("AutomatedCarrier")
  private String automatedCarrier = null;

  @SerializedName("AutomatedShipMethod")
  private String automatedShipMethod = null;

  public AutomatedShippingSettings hasAutomatedShippingSettings(Boolean hasAutomatedShippingSettings) {
    this.hasAutomatedShippingSettings = hasAutomatedShippingSettings;
    return this;
  }

   /**
   * If true, this order has automated shipping settings generated by Amazon. This order could be identified as an SSA order.
   * @return hasAutomatedShippingSettings
  **/
  @Schema(description = "If true, this order has automated shipping settings generated by Amazon. This order could be identified as an SSA order.")
  public Boolean isHasAutomatedShippingSettings() {
    return hasAutomatedShippingSettings;
  }

  public void setHasAutomatedShippingSettings(Boolean hasAutomatedShippingSettings) {
    this.hasAutomatedShippingSettings = hasAutomatedShippingSettings;
  }

  public AutomatedShippingSettings automatedCarrier(String automatedCarrier) {
    this.automatedCarrier = automatedCarrier;
    return this;
  }

   /**
   * Auto-generated carrier for SSA orders.
   * @return automatedCarrier
  **/
  @Schema(description = "Auto-generated carrier for SSA orders.")
  public String getAutomatedCarrier() {
    return automatedCarrier;
  }

  public void setAutomatedCarrier(String automatedCarrier) {
    this.automatedCarrier = automatedCarrier;
  }

  public AutomatedShippingSettings automatedShipMethod(String automatedShipMethod) {
    this.automatedShipMethod = automatedShipMethod;
    return this;
  }

   /**
   * Auto-generated ship method for SSA orders.
   * @return automatedShipMethod
  **/
  @Schema(description = "Auto-generated ship method for SSA orders.")
  public String getAutomatedShipMethod() {
    return automatedShipMethod;
  }

  public void setAutomatedShipMethod(String automatedShipMethod) {
    this.automatedShipMethod = automatedShipMethod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutomatedShippingSettings automatedShippingSettings = (AutomatedShippingSettings) o;
    return Objects.equals(this.hasAutomatedShippingSettings, automatedShippingSettings.hasAutomatedShippingSettings) &&
        Objects.equals(this.automatedCarrier, automatedShippingSettings.automatedCarrier) &&
        Objects.equals(this.automatedShipMethod, automatedShippingSettings.automatedShipMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasAutomatedShippingSettings, automatedCarrier, automatedShipMethod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutomatedShippingSettings {\n");
    
    sb.append("    hasAutomatedShippingSettings: ").append(toIndentedString(hasAutomatedShippingSettings)).append("\n");
    sb.append("    automatedCarrier: ").append(toIndentedString(automatedCarrier)).append("\n");
    sb.append("    automatedShipMethod: ").append(toIndentedString(automatedShipMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

