services:
  db:
    build:
      context: db
      args:
        mfregistry: $mfregistry
        mfversion: $mfversion
    ports:
      - "15432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/initdata
    healthcheck:
      test: pg_isready -h localhost -U metasfresh -d metasfresh -t 1
      interval: 10s
      timeout: 10s
      start_period: 60s
      retries: 30

  migration:
    image: $mfregistry/metas-db-migration-tool:$mfversion
    depends_on:
      db:
        condition: service_healthy
