/*
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.metas.camel.externalsystems.ebay.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This type describes the VAT tax details. The eBay VAT tax type and the eBay VAT identifier number will be returned if a VAT tax is applicable for the order. Note: On January 31, 2022, the orders.fulfillmentStartInstructions.shippingStep.shipTo.contactAddress.addressLine2 will stop being used to return VAT information, so developers should make sure they integrate with the new fields before that
 * time.
 */
@ApiModel(description = "This type describes the VAT tax details. The eBay VAT tax type and the eBay VAT identifier number will be returned if a VAT tax is applicable for the order. Note: On January 31, 2022, the orders.fulfillmentStartInstructions.shippingStep.shipTo.contactAddress.addressLine2 will stop being used to return VAT information, so developers should make sure they integrate with the new fields before that time.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-20T14:45:55.981728+02:00[Europe/Berlin]")
public class EbayTaxReference
{
	public static final String SERIALIZED_NAME_NAME = "name";
	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_VALUE = "value";
	@SerializedName(SERIALIZED_NAME_VALUE)
	private String value;

	public EbayTaxReference name(String name)
	{

		this.name = name;
		return this;
	}

	/**
	 * This field value is returned to indicate the VAT tax type, which will vary by country/region. This string value will be one of the following: ABN: if this string is returned, the ID in the value field is an Australia tax ID IOSS: if this string is returned, the ID in the value field is an eBay EU or UK IOSS number IRD: if this string is returned, the ID in the value field is an eBay New
	 * Zealand tax ID OSS: if this string is returned, the ID in the value field is an eBay Germany VAT ID VOEC: if this string is returned, the ID in the value field is an eBay Norway tax ID
	 * 
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "This field value is returned to indicate the VAT tax type, which will vary by country/region. This string value will be one of the following: ABN: if this string is returned, the ID in the value field is an Australia tax ID IOSS: if this string is returned, the ID in the value field is an eBay EU or UK IOSS number IRD: if this string is returned, the ID in the value field is an eBay New Zealand tax ID OSS: if this string is returned, the ID in the value field is an eBay Germany VAT ID VOEC: if this string is returned, the ID in the value field is an eBay Norway tax ID")

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public EbayTaxReference value(String value)
	{

		this.value = value;
		return this;
	}

	/**
	 * The value returned in this field is the VAT identifier number (VATIN), which will vary by country/region. This field will be returned if VAT tax is applicable for the order. The name field indicates the VAT tax type, which will vary by country/region: ABN: eBay AU tax ID IOSS: eBay EU IOSS number / eBay UK IOSS number IRD: eBay NZ tax ID OSS: eBay DE VAT ID VOEC: eBay NO number
	 * 
	 * @return value
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "The value returned in this field is the VAT identifier number (VATIN), which will vary by country/region. This field will be returned if VAT tax is applicable for the order. The name field indicates the VAT tax type, which will vary by country/region: ABN: eBay AU tax ID IOSS: eBay EU IOSS number / eBay UK IOSS number IRD: eBay NZ tax ID OSS: eBay DE VAT ID VOEC: eBay NO number")

	public String getValue()
	{
		return value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	@Override
	public boolean equals(Object o)
	{
		if (this == o)
		{
			return true;
		}
		if (o == null || getClass() != o.getClass())
		{
			return false;
		}
		EbayTaxReference ebayTaxReference = (EbayTaxReference)o;
		return Objects.equals(this.name, ebayTaxReference.name) &&
				Objects.equals(this.value, ebayTaxReference.value);
	}

	@Override
	public int hashCode()
	{
		return Objects.hash(name, value);
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder();
		sb.append("class EbayTaxReference {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o)
	{
		if (o == null)
		{
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
