/*
 * Fulfillment API
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.19.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.metas.camel.externalsystems.ebay.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * This type defines the monetary value of the payment dispute, and the currency used.
 */
@ApiModel(description = "This type defines the monetary value of the payment dispute, and the currency used.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-20T14:45:55.981728+02:00[Europe/Berlin]")
public class SimpleAmount
{
	public static final String SERIALIZED_NAME_CURRENCY = "currency";
	@SerializedName(SERIALIZED_NAME_CURRENCY)
	private String currency;

	public static final String SERIALIZED_NAME_VALUE = "value";
	@SerializedName(SERIALIZED_NAME_VALUE)
	private String value;

	public SimpleAmount currency(String currency)
	{

		this.currency = currency;
		return this;
	}

	/**
	 * A three-letter ISO 4217 code (such as USD for US site) that indicates the currency of the amount in the value field. Both the value and currency fields are always returned with the amount container. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:CurrencyCodeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
	 * 
	 * @return currency
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "A three-letter ISO 4217 code (such as USD for US site) that indicates the currency of the amount in the value field. Both the value and currency fields are always returned with the amount container. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/ba:CurrencyCodeEnum'>eBay API documentation</a>")

	public String getCurrency()
	{
		return currency;
	}

	public void setCurrency(String currency)
	{
		this.currency = currency;
	}

	public SimpleAmount value(String value)
	{

		this.value = value;
		return this;
	}

	/**
	 * The monetary amount of the payment dispute. Both the value and currency fields are always returned with the amount container.
	 * 
	 * @return value
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "The monetary amount of the payment dispute. Both the value and currency fields are always returned with the amount container.")

	public String getValue()
	{
		return value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	@Override
	public boolean equals(Object o)
	{
		if (this == o)
		{
			return true;
		}
		if (o == null || getClass() != o.getClass())
		{
			return false;
		}
		SimpleAmount simpleAmount = (SimpleAmount)o;
		return Objects.equals(this.currency, simpleAmount.currency) &&
				Objects.equals(this.value, simpleAmount.value);
	}

	@Override
	public int hashCode()
	{
		return Objects.hash(currency, value);
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder();
		sb.append("class SimpleAmount {\n");
		sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o)
	{
		if (o == null)
		{
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
